### ISSUE TITLE
Mounting host volumes via hostPath

### ISSUE THREAD

**Issue by kanadaj** [crc-org/crc#1409]
### General information

  * OS: Fedora 31
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
CodeReady Containers version: 1.13.0+8070bae
OpenShift version: 4.5.1 (embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Running (v4.5.1)
Disk Usage:      14.3GB of 32.72GB (Inside the CRC VM)
Cache Usage:     11.78GB
Cache Directory: /home/kanadaj/.crc/cache
```

## CRC config
```bash
- cpus                                  : 24
- memory                                : 20480
```

## Host Operating System
```bash
NAME=Fedora
VERSION="31 (Server Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Server Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server
```

### Steps to reproduce

I am trying to mount volumes from the host machine into CRC. If I understand it right, hostPath is currently not working because the path would refer to the path inside the VM that runs CRC rather than the actual host. Is there any workaround for this?

### Expected

HostPath should mount a directory/file of the host machine, or the command line client should provide a way to mount a host folder into the VM.

### Actual

If there is a way to do this, it's not documented...

**Comment by kanadaj** [comment]
For now I've worked around by making an NFS share from the host machine... Not the best solution, but it's a solution...

**Comment by gbraad** [comment]
It is not possible to use shared folders with CRC at this moment. this would need something that works across all hypervisors, so likely something as NFS or SMB fit this better anyway.

**Comment by anjannath** [comment]
host folder share was added in #3269 and #3308
