### ISSUE TITLE
Add Windows and macOS CI for PR and master builds

### ISSUE THREAD

**Issue by guillaumerose** [crc-org/crc#1552]
Currently PRs and master builds are only end-to-end tested on Linux, and not on Windows and macOS. 
macOS and Windows are only tested in a private CI at release time. 

Having a complete CI on this repo would avoid this kind of bug happing during the release: https://github.com/code-ready/crc/issues/1549

**Comment by anjannath** [comment]
When we initially thought about this, we couldn't find a suitable free CI infra for doing this, Right now if we want to use the downstream resources, we could go that route by integrating it with github but not sure if that'd be possible, another way is to use the GCE resources. @guillaumerose do you have any ideas?
