### ISSUE TITLE
msi installer with location on different drive

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/crc#2420]
msi installer allows to select a different location, there is no restriction on the location, so a different drive can be used. In that case the installer end up failing. 

According to previous comments https://github.com/code-ready/crc/issues/1222#issuecomment-625006792 it is expected crc binary will be installed on same windows drive. In case this is still applicable the installer should deny or warning about select of different drive.

**Comment by anjannath** [comment]
or we can remove the drive selection step entirely and the default is always install in `$windrive\Program files\CodeReady Containers`

**Comment by anjannath** [comment]
install location selection was removed in #3928
