### ISSUE TITLE
Add configuration option for the preset in ~/.crc/crc.json

### ISSUE THREAD

**Issue by guillaumerose** [crc-org/crc#2525]
(task from epic https://github.com/code-ready/crc/issues/2167)

**Comment by anjannath** [comment]
Need to decide the following:
- [ ] Name of the config option (`preset`/`mode`) ?
- [ ] Names of the configurations

we can call the config option `mode` and the configurations `podman-mode`, `minimal-crc-mode`, `full-crc-mode`, WDYT?

**Comment by guillaumerose** [comment]
I think we can start with ` preset=podman|minimal|full`  ?

**Comment by anjannath** [comment]
presets have been part of crc since quite a few release now, closing
