### ISSUE TITLE
Ask for consent to send telemetry data in the trays

### ISSUE THREAD

**Issue by anjannath** [crc-org/crc#2575]
Right now we don't have a way to ask users for consent to send telemetry from the trays. This issue is to track and describe how we want to ask for this consent. During the installation phase from the installers or On first start of the trays

/cc @gbraad

**Comment by gbraad** [comment]
There are two solutions:

  * installer takes care of this
  * we have a welcome screen

**Comment by cfergeau** [comment]
Asking in the installer makes more sense to me, not clear when the welcome screen would appear? An additional popup showing up when the tray is started during installation? Imo better to avoid that additional window.

**Comment by cfergeau** [comment]
See also https://github.com/code-ready/crc/issues/2469
