### ISSUE TITLE
Unexpected end of JSON input upon installation

### ISSUE THREAD

**Issue by rupeshad81** [crc-org/crc#2811]
### General information

  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / Hyper-V / hyperkit
  * Did you run `crc setup` before starting it (Yes/No)?
  * Running CRC on: Laptop / Baremetal-Server / VM

## CRC version
```bash
# Put `crc version` output here
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```

## CRC config
```bash
# Put `crc config view` output here
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

While installing the crc 1.34.1, getting below issue:

[crc@eaas-crc ~]$ crc config set proxy-ca-file /tmp/amdocs-cert.crt
unexpected end of JSON input

**Comment by praveenkumar** [comment]
@rupeshad81 looks like you manually edited `~/.crc/crc.json` file which made it corrupted, try following.
```
$ crc delete
$ rm -fr ~/.crc/crc.json
$ crc setup
$ crc config set proxy-ca-file /tmp/amdocs-cert.crt
$ crc config set no-proxy <no_proxies>
```

Don't try to edit `~/.crc/crc.json` file manually.

**Comment by gbraad** [comment]
> While installing the crc 1.34.1, getting below issue:

As you can see: 
https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/1.34.1 this version does not exist. Take more care when filing an issue. The warning still stands.

**Comment by rupeshad81** [comment]
Hi,
Yes it was mistake. Correct version.

[crc@eaas-crc ~]$ crc version
CodeReady Containers version: 1.34.0+34c31851
OpenShift version: 4.9.0 (embedded in executable)

**Comment by gbraad** [comment]
Closed; marked as Invalid

> [crc@eaas-crc ~]$ crc setup

... finished correctly. Indicating the `crc.json` file was malformed.
