### ISSUE TITLE
Implement file sharing

### ISSUE THREAD

**Issue by cfergeau** [crc-org/crc#3180]
We need a way to share files/directories with the crc VM. The first use case would be for the podman preset, to implement `podman-remote -v localdir:remotedir`.
There are several options:
- virtiofs
- sshfs

**Comment by cfergeau** [comment]
The way podman does it is by mounting (on a mac) `/Users/teuf` to `/Users/teuf` inside its VM using 9p. Then `podman-remote -v /Users/teuf/localdir:remotedir` can be used successfully.

I've added virtiofs support to vfkit in https://github.com/cfergeau/vfkit/tree/virtiofs , though this depends on an unmerged PR in Code-Hex/vz

This is then used by https://github.com/cfergeau/crc/commits/macos-vf (various paths/tags are hardcoded at the moment). 

With these changes, I can start a VM using the podman bundle, and `/Users/teuf` is mounted to the same path in the VM. However /Users/teuf in the VM is owned by `root.root`.  Because of this, `podman -v /Users/teuf/localdir:remotedir` fails as rootless podman can't access `/Users/teuf`.
I did not have time to dig around mount options/... to understand if we can tweak this behaviour.

**Comment by cfergeau** [comment]
podman-machine has a trick to access /Users/teuf. Through 9p,  /Users/teuf is owned by a user with the same uid as I have on my mac. When podman-machine creates its VM, its ignition file creates a `core` user with the same uid as the one `teuf` has locally on the mac. This eases some of the permissions/ownership issues that might occur.

**Comment by anjannath** [comment]
closing this more updates in the epic
