### ISSUE TITLE
Move away from the `code-ready` namespace

### ISSUE THREAD

**Issue by cfergeau** [crc-org/crc#3264]
Since we are no longer called CodeReady Containers, it's odd to still be using the code-ready namespace on GitHub
We first need to decide on a new namespace (crc-team, crc-dev, ... were considered).

Once this is done, I would add the [owners](https://github.com/orgs/code-ready/people?query=role%3Aowner) of `github.com/code-ready` as owners of the new namespace.

One of these owners can then start moving small repos to see how much work this involves/how complicated it is. https://github.com/code-ready/vfkit, https://github.com/code-ready/admin-helper, https://github.com/code-ready/machine-driver-libvirt come to mind as small repos we could use for initial assesment of the work involved.

**Comment by anjannath** [comment]
New org: https://github.com/crc-org

**Comment by cfergeau** [comment]
I gave this a quick try, and moved vfkit to see how it goes.
I documented my findings so far in https://github.com/crc-org/vfkit/wiki/Moving-from-code-ready-to-crc-org

**Comment by cfergeau** [comment]
List of modules to be moved:
- [x] vfkit https://github.com/crc-org/vfkit/pull/9
- [x] snc
- [x] routes-controller https://github.com/crc-org/routes-controller/pull/9
- [x] admin-helper https://github.com/crc-org/admin-helper/pull/37
- [x] machine
- [x] machine-driver-libvirt
- [x] crc
- [x] tray-electron
- [x] blog
- [x] code-ready.github.io

I may have missed some (clicumber? tray-windows, tray-macos?), they'll need to be added as well.

**Comment by cfergeau** [comment]
Since the vfkit move went smoothly, I'll move soon a bigger set of modules if there are no objections. I'm thinking routes-controller/admin-helper/machine/machine-driver-libvirt, and once they are moved, file a PR against crc to make it stop using the legacy names. If this also goes smoothly, we can move crc/snc, and the few remaining modules.

**Comment by anjannath** [comment]
> I may have missed some (clicumber? tray-windows, tray-macos?), they'll need to be added as well.

tray-windows and tray-macos doesn't need to be moved, these two can be archived i think

**Comment by jorgemoralespou** [comment]
isn't it weird that:

**Comment by cfergeau** [comment]
OpenShift Local is a Red Hat product based on crc, but the upstream crc binary can also be used to run podman or okd runtimes, not just openshift. The openshift namespace/org was not a great fit because of that.
Now `crc` is just `crc`. Anyone remembering that `crc` can be expanded as an acronym (Code what?) must be misrembering ;)

**Comment by praveenkumar** [comment]
We have to check the internal RPM packaging side changes for this move, other than that everything is in place for this change.

**Comment by cfergeau** [comment]
github pages are broken

**Comment by praveenkumar** [comment]
> github pages are broken

You mean https://code-ready.github.io/ one?

**Comment by praveenkumar** [comment]
Now that is also redirected so now I think everything works as usual.

**Comment by cfergeau** [comment]
> > github pages are broken
> 
> You mean https://code-ready.github.io/ one?

docs.crc.dev was not working when I tried, bu you've fixed this already.

**Comment by praveenkumar** [comment]
Closing this issue since everything as part of the list is in place.
