### ISSUE TITLE
Proxy support to pull the bundle image from quay

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/crc#3354]
We don't have any test or even implementation around pulling the bundle images (podman/okd) from the quay in case user is behind the proxy. This will help us to move one step closer to have our OCP bundles also as part of quay.

**Comment by anjannath** [comment]
If system wide proxy is configured either using the OS default network manager or using the env variables `http_proxy` and `https_proxy` `crc setup` will be able to pull in the bundle image.

containers/image doesn't support customizing the `httpClient` used, it uses the system proxy configs, see: https://github.com/containers/image/issues/1194 and https://github.com/containers/image/pull/537

**Comment by anjannath** [comment]
If we add a scenario like below will it be enough? or maybe we should check the logs in the `squid` container as well to make sure the request actually went through it and not directly to the internet

```cucumber
Background: Setup the proxy container using podman
         * executing "podman run --name squid -d -p 3128:3128 quay.io/crcont/squid" succeeds

    Scenario: Setup CRC behind proxy
        * executing "export http_proxy='http://192.168.130.1:3128'" succeeds
        * executing "export https_proxy='http://192.168.130.1:3128'" succeeds
        Given executing "crc config set preset podman" succeeds
        Then executing crc setup command succeeds
        When executing "crc config get preset" succeeds
        Then stdout should contain "podman"
        # cleanup proxy and preset settings from config
        And executing "crc config unset http-proxy" succeeds
        And executing "crc config unset https-proxy" succeeds
        And executing "crc config unset preset" succeeds
```
cc @jsliacan

**Comment by jsliacan** [comment]
Sounds great, just a couple of comments.

- If we add this Scenario to `crc/test/e2e/features/proxy.feature`, then we can skip `Background` in your snippet.
- Maybe we need to make sure that there's no podman bundle in `~/.crc/cache` or wherever it lives. So the download happens for sure.
- Should we also do `crc start`? It takes no time with podman bundle anyways. If it exits with 0, it's a good confirmation. Probably not needed, but it's a one liner `And executing "crc start" succeeds`. 

Also, I need to check what `podman run <img>` does if that was done once already (return 1, 0, do I have 2 containers? etc.) The `Background` block in `proxy.feature` might not be robust to this and we'll have to add a check. 

Thanks!

**Comment by anjannath** [comment]
> If we add this Scenario to crc/test/e2e/features/proxy.feature, then we can skip Background in your snippet.

yeah the snippet is c&p from that feature file only, makes sense to include it there, but i am not sure if we should check if the pull happened through the squid container or directly.. 

this `Scenario` is a bit different from the existing proxy scenario for `openshift`, this scenario is checking the proxy config with the `crc setup` command during pulling the bundle image, the existing proxy feature tests that, connectivity from the cluster to the outside goes through the proxy

> Maybe we need to make sure that there's no podman bundle in ~/.crc/cache or wherever it lives. So the download happens for sure.

yeah 👍🏽 

> Should we also do crc start? It takes no time with podman bundle anyways. If it exits with 0, it's a good confirmation. Probably not needed, but it's a one liner And executing "crc start" succeeds.

yeah not needed, we just want to test the bundle pull happens successfully

**Comment by praveenkumar** [comment]
Closing this since proxy test case is already part of integration with #3417
