### ISSUE TITLE
[BUG] "Unable to determine VM's IP address, did it fail to boot?" on a RHEL 8.6 VM

### ISSUE THREAD

**Issue by Kerthal** [crc-org/crc#3395]
### General information

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: VM

## CRC version
```bash
CRC version: 2.10.1+426703d
OpenShift version: 4.11.7
Podman version: 4.2.0
```
  
## CRC status
```bash
DEBU CRC version: 2.10.1+426703d
DEBU OpenShift version: 4.11.7
DEBU Podman version: 4.2.0
DEBU Running 'crc status'
DEBU Checking file: /home/fmean/.crc/machines/crc/.crc-exist
DEBU Checking file: /home/fmean/.crc/machines/crc/.crc-exist
DEBU Found binary path at /home/fmean/.crc/bin/crc-driver-libvirt
DEBU Launching plugin server for driver libvirt
DEBU Plugin server listening at address 127.0.0.1:36273
DEBU () Calling .GetVersion
DEBU Using API Version 1
DEBU () Calling .SetConfigRaw
DEBU () Calling .GetMachineName
DEBU (crc) Calling .GetBundleName
DEBU (crc) Calling .GetState
DEBU (crc) DBG | time="2022-10-26T06:20:48Z" level=debug msg="Getting current state..."
DEBU (crc) DBG | time="2022-10-26T06:20:48Z" level=debug msg="Fetching VM..."
DEBU (crc) Calling .GetIP
DEBU (crc) DBG | time="2022-10-26T06:20:48Z" level=debug msg="GetIP called for crc"
DEBU (crc) DBG | time="2022-10-26T06:20:48Z" level=debug msg="Getting current state..."
DEBU (crc) Calling .GetIP
DEBU (crc) DBG | time="2022-10-26T06:20:48Z" level=debug msg="GetIP called for crc"
DEBU (crc) DBG | time="2022-10-26T06:20:48Z" level=debug msg="Getting current state..."
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1
DEBU Using ssh private keys: [/home/fmean/.crc/machines/crc/id_ecdsa /home/fmean/.crc/cache/crc_libvirt_4.11.7_amd64/id_ecdsa_crc]
DEBU SSH command results: err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain, output:
DEBU Cannot get root partition usage: ssh command error:
command : df -B1 --output=size,used,target /sysroot | tail -1
err     : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
DEBU cannot get OpenShift status: stat /home/fmean/.crc/machines/crc/kubeconfig: no such file or directory
DEBU Making call to close driver server
DEBU (crc) Calling .Close
DEBU Successfully made call to close driver server
DEBU Making call to close connection to plugin binary
DEBU (crc) DBG | time="2022-10-26T06:20:48Z" level=debug msg="Closing plugin on server side"
CRC VM:          Running
OpenShift:       Unreachable (v4.11.7)
Podman:
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     13.05GB
Cache Directory: /home/fmean/.crc/cache
```

## CRC config
```bash
- consent-telemetry                     : no
```

## Host Operating System
```bash
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"
```

### Steps to reproduce

  1. crc setup
  2. crc start --log-level debug

### Expected
VM created and ready to be used

### Actual
The CRC VM is not created at all. It does try 60 times then it exits but the error is not really helpful. I currently have no clue what could be the issue.
I am trying to install this on a RHEL 8.6 VM created via VMWare.
I see a "handshake failed" error when executing CRC status but I do not know if it is relevant since the VM is not created.

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```
I did those steps after the first failed attempt and it gives the same results.

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

https://gist.github.com/Kerthal/888dc38334bd3341b681c255159c31b6#file-crc-log-txt

**Comment by marcoshaw** [comment]
That errors seems to be related to the permissions on private keys.  Is this a vanilla install of Red Hat 8.6 or it may have any hardening done like a special umask?

**Comment by ClassANetwork** [comment]
> That errors seems to be related to the permissions on private keys. Is this a vanilla install of Red Hat 8.6 or it may have any hardening done like a special umask?

@marcoshaw I also have this issue after the more recent updates I pulled. This is a fresh 8.6 installation in VMWare Fusion. 

```
[xv8@rhel8-crc ~]$ crc start -m 12288 -p pull-secret
INFO Checking if running as non-root
INFO Checking if running inside WSL2
INFO Checking if crc-admin-helper executable is cached
INFO Checking for obsolete admin-helper executable
INFO Checking if running on a supported CPU architecture
INFO Checking minimum RAM requirements
INFO Checking if crc executable symlink exists
INFO Checking if Virtualization is enabled
INFO Checking if KVM is enabled
INFO Checking if libvirt is installed
INFO Checking if user is part of libvirt group
INFO Checking if active user/process is currently part of the libvirt group
INFO Checking if libvirt daemon is running
INFO Checking if a supported libvirt version is installed
INFO Checking if crc-driver-libvirt is installed
INFO Checking crc daemon systemd socket units
INFO Checking if systemd-networkd is running
INFO Checking if NetworkManager is installed
INFO Checking if NetworkManager service is running
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists
INFO Checking if /etc/NetworkManager/dnsmasq.d/crc.conf exists
INFO Checking if libvirt 'crc' network is available
INFO Checking if libvirt 'crc' network is active
INFO Loading bundle: crc_libvirt_4.11.7_amd64...
INFO Creating CRC VM for openshift 4.11.7...
INFO Generating new SSH key pair...
INFO Generating new password for the kubeadmin user
INFO Starting CRC VM for openshift 4.11.7...
Error starting machine: Error in driver during machine start: Unable to determine VM's IP address, did it fail to boot?
```

[https://gist.github.com/ClassANetwork/5467f82e765b5aabb2a852c0afe1139f](url)

**Comment by gbraad** [comment]
> The CRC VM is not created at all. 

Are you able to run a VM from `virsh` ?

> It is something to do with the VM itself in VMWare Fusion, so I think we can at least isolate the issue down to this.

We do not support nested virtualization setups. Especially not with VMware as we have no means to verify this. Why not run CRC on MacOS ???

**Comment by ClassANetwork** [comment]
> We do not support nested virtualization setups. Especially not with VMware as we have no means to verify this. Why not run CRC on MacOS ???

I have it. It works. However, I wanted podman and other tools native on Linux for my EX180/280 courses, and it's the closest I can get without running RHEL 8.6 bare metal.

**Comment by Kerthal** [comment]
Hello,

Sorry for the late reply, I was off last week.
I made a few more tests on my end and I am able to install this version of CRC on any RHEL 8.5 (or below) VM. But once I have a RHEL 8.6 VM, it fails to determine VM's IP address.

I compared the logs between a RHEL 8.5 and RHEL 8.6 installation and the only difference I could spot is in the crc start.
On RHEL 8.5, I have this part:
`DEBU Making call to close driver server`
`DEBU (crc) Calling .Close`
`DEBU (crc) DBG | time="2022-11-07T15:51:12Z" level=debug msg="Closing plugin on server side"`
`DEBU Successfully made call to close driver server`

Where on RHEL 8.6, I have the following:
`DEBU Making call to close driver server`
`DEBU (crc) Calling .Close`
`DEBU Successfully made call to close driver server`

As you can see, I am missing the third line on RHEL 8.6. Any idea if that could explain anything?

**Comment by cfergeau** [comment]
After this failed, can you take a closer look at the libvirt VM it should have created?
```
$ virsh -c qemu:///system list --all
$ virsh -c qemu:///system domifaddr crc
$ cat /var/log/libvirt/qemu/crc.log
$ virt-viewer -c qemu:///system crc
```
(the path to the log file might be slightly off)

**Comment by Kerthal** [comment]
Here is the output of the 3 first commands:
https://gist.github.com/Kerthal/e2b3097974d8ae49d08493ee4117783b#file-rhel-8-6-virsh

I can launch the 4th one but I have no clue which credentials I need as input on the new window that appears.

**Comment by cfergeau** [comment]
The logs have
```
[    6.883577] systemd-udevd[640]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
[    6.894122] systemd-udevd[639]: Using default interface naming scheme 'rhel-8.0'.
[    6.895207] virtio_net virtio1 enp2s0: renamed from eth0
[    6.897238] systemd-udevd[639]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
[  OK  ] Started Hostname Service.
         Starting Network Manager Script Dispatcher Service...
[   13.242240] IPv6: ADDRCONF(NETDEV_UP): enp2s0: link is not ready
```
and the `ip addr` runs show that `enp2s0` did not get any IP addresses. This is consistent with what `virsh domifaddr` is reporting. Why this happens is a different question though :) You are trying to run crc inside a RHEL 8.6 VM running on VMWare?

**Comment by Kerthal** [comment]
Yes because all my VMs (being REHL 8.6, 8.5 or any other version) are created with VMWare. This is how VMs are handled here at work.

**Comment by marcoshaw** [comment]
I have a theory that I can't follow up on right now.  I think this is related to SSH keys...  I'm reading here that it's possible that DSA keys are no longer supported:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/8.6_release_notes/index

I haven't downloaded the source to see if the keys created as part of the process are DSA, but I think that anyone with an actual working RHEL 8.5 can see what was used?

**Comment by cfergeau** [comment]
crc is using ecdsa keys for its ssh communication. In the logs Kerthal provided, the VM does not get an IP assigned, so crc does not even try to ssh into it.

**Comment by cfergeau** [comment]
> Yes because all my VMs (being REHL 8.6, 8.5 or any other version) are created with VMWare. This is how VMs are handled here at work.

Unfortunately, as Gerard mentioned before:

> We do not support nested virtualization setups. Especially not with VMware as we have no means to verify this. 

We don't test crc nested on VMWare, so I have no idea where this issue with networking is coming from. Maybe try user mode networking and see if that's better (`crc config set network-mode user`)

**Comment by Kerthal** [comment]
Hi @cfergeau ,

I tested installing crc on a RHEL 8.6 system with the network-mode command you provided and it worked! Thanks a lot.

My last question is: will this "workaround" always be applicable for VMs created with VMWare or is it "doomed" to fail at some point in time? Do not know if an answer can yet be provided to this question though....

**Comment by cfergeau** [comment]
user-mode networking is there to stay. Whether it will always work with vmware VMs or not, I cannot answer this question :)

**Comment by Kerthal** [comment]
> user-mode networking is there to stay. Whether it will always work with vmware VMs or not, I cannot answer this question :)

Ok thanks for the reply :)

I will close this ticket.

**Comment by imperialguy** [comment]
After running `crc config set network-mode user`, I tried starting `crc`. But I it fails with the following error towards the end:

```
......
INFO Starting kubelet service
INFO Waiting for kube-apiserver availability... [takes around 2min]
INFO Adding user's pull secret to the cluster...
INFO Updating SSH key to machine config resource...
INFO Waiting for user's pull secret part of instance disk...
INFO Changing the password for the kubeadmin user
INFO Updating cluster ID...
ssh command error:
command : timeout 30s oc apply -f /tmp/routes-controller.json --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 124
```

Anyone any ideas?

**Comment by cfergeau** [comment]
@imperialguy Can you open a new issues with more details about what you are doing? Thanks!
