### ISSUE TITLE
CRC do not work in circleci or travisci

### ISSUE THREAD

**Issue by kaovilai** [crc-org/crc#3401]
CRC do not work in circleci or travisci unlike _kind cluster_ which can be used in many CI environments.
https://app.circleci.com/pipelines/github/kaovilai/reliable-ci/15/workflows/e65e2e00-0e06-44da-9598-a0d1a0e593a3/jobs/22

**Comment by praveenkumar** [comment]
@kaovilai CRC needs virtualization enable to work with any platform. Since OCP only allow RHCOS for control nodes https://docs.openshift.com/container-platform/4.11/architecture/architecture.html#architecture-custom-os_architecture .

**Comment by gbraad** [comment]
OCP and therefore CRC depends on Red Hat CoreOS to be the base OS. For this reason you need nested virtualization to make this work. Unfortunately this means that most free tier CI services will not be sufficient.
