### ISSUE TITLE
Feature request: integrate `crc setup` functionality into `crc start`

### ISSUE THREAD

**Issue by bmaupin** [crc-org/crc#3419]
This scenario happens to me a lot:

1. Run `crc start`
2. It times out after 10 minutes:
   ```
   ERRO Cluster is not ready: cluster operators are still not stable after 10m0.415913626s
   ```
3. Realize I forgot to run `crc setup` first, then run `crc stop && crc setup && crc start`

I'm guessing it's timing out because my network changes regularly depending whether I'm in the office, on my home network, or on my home network using my office VPN.

It feels like there must be some awareness of this issue already because this is one of the first questions asked when creating a new bug report in this project:

>   * Did you run `crc setup` before starting it (Yes/No)?

If there's some "magic" that's part of `crc setup` that's required for `crc start` to run normally, why not improve the user experience and integrate that functionality into `crc start`? It seems like a small issue but I'm often multitasking and don't realize CRC has failed until 10 minutes later when it times out. Then I have to wait another ~8 minutes for it to start properly.

Here's the output when it fails to start:

```
$ crc start
INFO Checking if running as non-root              
INFO Checking if running inside WSL2              
INFO Checking if crc-admin-helper executable is cached 
INFO Checking for obsolete admin-helper executable 
INFO Checking if running on a supported CPU architecture 
INFO Checking minimum RAM requirements            
INFO Checking if crc executable symlink exists    
INFO Checking if Virtualization is enabled        
INFO Checking if KVM is enabled                   
INFO Checking if libvirt is installed             
INFO Checking if user is part of libvirt group    
INFO Checking if active user/process is currently part of the libvirt group 
INFO Checking if libvirt daemon is running        
INFO Checking if a supported libvirt version is installed 
INFO Checking if crc-driver-libvirt is installed  
INFO Checking crc daemon systemd socket units     
INFO Checking if AppArmor is configured           
INFO Checking if systemd-networkd is running      
INFO Checking if NetworkManager is installed      
INFO Checking if NetworkManager service is running 
INFO Checking if dnsmasq configurations file exist for NetworkManager 
INFO Checking if the systemd-resolved service is running 
INFO Checking if /etc/NetworkManager/dispatcher.d/99-crc.sh exists 
INFO Checking if libvirt 'crc' network is available 
INFO Checking if libvirt 'crc' network is active  
INFO Loading bundle: crc_libvirt_4.11.7_amd64...  
INFO Starting CRC VM for openshift 4.11.7...      
INFO CRC instance is running with IP 192.168.130.11 
INFO CRC VM is running                            
INFO Configuring shared directories               
INFO Check internal and public DNS query...       
INFO Check DNS query from host...                 
WARN Wildcard DNS resolution for apps-crc.testing does not appear to be working 
INFO Verifying validity of the kubelet certificates... 
INFO Starting kubelet service                     
INFO Waiting for kube-apiserver availability... [takes around 2min] 
INFO Waiting for user's pull secret part of instance disk... 
INFO Starting openshift instance... [waiting for the cluster to stabilize] 
INFO Operator authentication is not yet available 
INFO Operator authentication is not yet available 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
ERRO Cluster is not ready: cluster operators are still not stable after 10m0.415913626s 
INFO Adding crc-admin and crc-developer contexts to kubeconfig... 
ERRO Cannot update kubeconfig: Head "https://oauth-openshift.apps-crc.testing": dial tcp 192.168.130.11:443: connect: connection refused 
Started the OpenShift cluster.

The server is accessible via web console at:
  https://console-openshift-console.apps-crc.testing

Log in as administrator:
  Username: kubeadmin
  Password: xxxxxxxxxxxxx

Log in as user:
  Username: developer
  Password: developer

Use the 'oc' command line interface:
  $ eval $(crc oc-env)
  $ oc login -u developer https://api.crc.testing:6443
```

In case it helps, here's some more information (copied from https://github.com/crc-org/crc/issues/3414):

### General information

  * OS: Linux
  * Hypervisor: KVM? (I didn't configure anything)
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
CRC version: 2.10.2+1bc2e5a
OpenShift version: 4.11.7
Podman version: 4.2.0
```
  
## CRC status
```bash
DEBU CRC version: 2.10.2+1bc2e5a                  
DEBU OpenShift version: 4.11.7                    
DEBU Podman version: 4.2.0                        
DEBU Running 'crc status'                         
CRC VM:          Running
OpenShift:       Running (v4.11.7)
RAM Usage:       6.944GB of 9.399GB
Disk Usage:      17.92GB of 32.74GB (Inside the CRC VM)
Cache Usage:     16.43GB
Cache Directory: /home/user/.crc/cache
```

## CRC config
```bash
- consent-telemetry                     : yes
```

## Host Operating System
```bash
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

Thanks!

**Comment by bmaupin** [comment]
For now I'm just working around this with this hack in ~/.bashrc:

```bash
crc() {
    if [ "$1" == "start" ]; then
        crc setup && command crc "$@"
    else
        command crc "$@"
    fi
}
```

**Comment by anjannath** [comment]
@bmaupin from the logs you shared looks like the cluster started successfully

even though the logs say `ERRO Cluster is not ready: cluster operators are still not stable after 10m0.415913626s` the cluster keeps trying to reconcile and eventually gets to a usable state, sometimes due to network or resources constraints on the machine it takes more then 10mins 

did you try to access the cluster using `oc` after the start, and did that also fail?

> Realize I forgot to run crc setup first, then run crc stop && crc setup && crc start

`crc setup` is not needed to run every-time you want to start, its only needed when you upgrade/install crc or change some specific config options (these config options prints a message asking user to run `crc setup` when needed)

**Comment by bmaupin** [comment]
> the cluster keeps trying to reconcile and eventually gets to a usable state, sometimes due to network or resources constraints on the machine it takes more then 10mins

> did you try to access the cluster using oc after the start, and did that also fail?

It doesn't seem to be coming up. I just tried now and waited 30 minutes, and the console isn't working:

```
$ curl https://console-openshift-console.apps-crc.testing
curl: (7) Failed to connect to console-openshift-console.apps-crc.testing port 443 after 0 ms: Connection refused
```
It looks like `oc` is failing too:

```
$ oc login -u developer https://api.crc.testing:6443
The connection to the server oauth-openshift.apps-crc.testing was refused - did you specify the right host or port?
```

> `crc setup` is not needed to run every-time you want to start, its only needed when you upgrade/install crc or change some specific config options

Maybe I'm running into a weird case or something, but the only thing that's changing on my end that I'm aware of is my networking. I'm not touching `crc` in any way.

The only thing that works consistently is running `crc setup` every time before running `crc start`.

The big difference I'm seeing when it times out is that `operator-lifecycle-manager-packageserver` is repeated a lot more, maybe indicating it never finishes?

```
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
ERRO Cluster is not ready: cluster operators are still not stable after 10m0.624437061s
```

Whereas whenever it works, the output is different:

```
INFO Starting openshift instance... [waiting for the cluster to stabilize] 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator operator-lifecycle-manager-packageserver is progressing 
INFO Operator authentication is degraded          
INFO Operator authentication is degraded          
INFO Operator authentication is degraded          
INFO Operator authentication is degraded          
INFO Operator authentication is degraded          
INFO Operator authentication is degraded          
INFO Operator authentication is degraded          
INFO Operator authentication is degraded          
INFO Operator authentication is degraded          
INFO All operators are available. Ensuring stability... 
INFO Operators are stable (2/3)...                
INFO Operators are stable (3/3)...
```

Or sometimes I'll see this instead (when it works):

```
INFO Starting openshift instance... [waiting for the cluster to stabilize] 
INFO Operator openshift-apiserver is not yet available 
INFO Operator openshift-apiserver is not yet available 
INFO Operator openshift-apiserver is not yet available 
INFO Operator openshift-apiserver is not yet available 
INFO Operator openshift-apiserver is not yet available 
INFO Operator openshift-apiserver is not yet available 
INFO Operator openshift-apiserver is not yet available 
INFO Operator openshift-apiserver is not yet available 
INFO Operator openshift-apiserver is not yet available 
INFO Operator openshift-apiserver is not yet available 
INFO All operators are available. Ensuring stability... 
INFO Operators are stable (2/3)...                
INFO Operators are stable (3/3)...
```

**Comment by VGerris** [comment]
My 2 cents: crc setup is not needed usually and you indicate your network is changing. I would not expect the setup to deal with that without taking measures. As such, it is not viable to request a feature that only your case may benefit.
This could be considered a bug if this should not happen, but that is not clear either.

If running crc setup before start works, why don't you just create a simple bash file or alias that does that?
That would make it work and deal with the changes if it does at the moment.

**Comment by bmaupin** [comment]
@VGerris

> If running crc setup before start works, why don't you just create a simple bash file or alias that does that?

That's what I've done (https://github.com/crc-org/crc/issues/3419#issuecomment-1317642486)

> crc setup is not needed usually and you indicate your network is changing. I would not expect the setup to deal with that without taking measures. As such, it is not viable to request a feature that only your case may benefit.

If I'm the only one experiencing this then I agree it's not worth putting much effort into.

On the other hand, `crc setup` is needed to be run at least one time, correct? This is still one extra step compared to minishift, which just requires running `minishift start`. So if `crc setup` could be eliminated altogether it seems like it would be an improvement from a UX perspective.

Thanks!

**Comment by bmaupin** [comment]
I'll go ahead and close this; even with my workaround, `crc start` often fails the first time. Must be something else :/
