### ISSUE TITLE
http proxy error while trying to run dynamic plugin locally.

### ISSUE THREAD

**Issue by AjayJagan** [crc-org/crc#3425]
### General information

  * macOS M1
  * Hypervisor: Podman(qemu)
  * Did you run `crc setup` before starting it (Yes)
  * Running CRC on: Laptop
## CRC version
```bash
CRC version: 2.10.2+065f0741
OpenShift version: 4.11.7
Podman version: 4.2.0
```
  
## CRC status
```bash
DEBU CRC version: 2.10.2+065f0741
DEBU OpenShift version: 4.11.7
DEBU Podman version: 4.2.0
DEBU Running 'crc status'
CRC VM:          Running
OpenShift:       Running (v4.11.7)
RAM Usage:       8.943GB of 16.34GB
Disk Usage:      15.18GB of 32.74GB (Inside the CRC VM)
Cache Usage:     73.53GB
Cache Directory: /Users/ajay/.crc/cache
```

## CRC config
```bash
- consent-telemetry                     : no
```

## Host Operating System
```bash
ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400
```

### Steps to reproduce

  1. clone https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin.git
  2. `cd activemq-artemis-self-provisioning-plugin`
  3.  run `yarn run build` (should have yarn installed)
  4.  run `yarn run start` in a separate terminal
  5. run `yarn run start-console` in another terminal

### Expected
The UI should be accessible at `http://localhost:9000`

### Actual
The logs fail with a HTTP proxy error and UI is not accessible.

### Logs
Starting local OpenShift console...
API Server: https://api.crc.testing:6443
Console Image: quay.io/openshift/origin-console:latest
Console URL: http://localhost:9000
Trying to pull quay.io/openshift/origin-console:latest...
Getting image source signatures
Copying blob sha256:b1a581a9885c08c968f83a70f6d6940564f288cb9fc4b039e4743e7be8c9c8cc
Copying blob sha256:69788635f90cb66139f7d62ff431c784b4fd7b98632bb18e7cc10bebab55205e
Copying blob sha256:9578bde7a5452e36c2da7dca455705194e76d896b3d3371358fc3fc027e203d4
Copying blob sha256:dfaf6e5198c10186790f5f02d3d4e18941704c0f29b0dda3e7a1df12563a5c5a
Copying blob sha256:230a4f53a4a69f1aed929af369883fd1563117b0643f0c8bf1ad1578d41a895e
Copying config sha256:e47e7f353b8fa136ba24f53037156b0b6a5c735c5f9a638f575ca66f686becca
Writing manifest to image destination
Storing signatures
WARNING: image platform ({amd64 linux  [] }) does not match the expected platform ({arm64 linux  [] })
W1121 05:28:19.153195       1 main.go:228] Flag inactivity-timeout is set to less then 300 seconds and will be ignored!
I1121 05:28:19.155403       1 main.go:238] The following console plugins are enabled:
I1121 05:28:19.155896       1 main.go:240]  - activemq-artemis-self-provisioning-plugin
W1121 05:28:19.156592       1 main.go:351] cookies are not secure because base-address is not https!
W1121 05:28:19.158006       1 main.go:682] running with AUTHENTICATION DISABLED!
I1121 05:28:19.168760       1 main.go:798] Binding to 0.0.0.0:9000...
I1121 05:28:19.169235       1 main.go:803] not using TLS
2022/11/21 05:28:45 http: proxy error: dial tcp: lookup api.crc.testing on 192.168.127.1:53: no such host
2022/11/21 05:28:45 http: proxy error: dial tcp: lookup api.crc.testing on 192.168.127.1:53: no such host
2022/11/21 05:28:45 http: proxy error: dial tcp: lookup api.crc.testing on 192.168.127.1:53: no such host
2022/11/21 05:28:45 http: proxy error: dial tcp: lookup api.crc.testing on 192.168.127.1:53: no such host
2022/11/21 05:28:45 http: proxy error: dial tcp: lookup api.crc.testing on 192.168.127.1:53: no such host
2022/11/21 05:28:45 http: proxy error: dial tcp: lookup api.crc.testing on 192.168.127.1:53: no such host
2022/11/21 05:28:45 http: proxy error: dial tcp: lookup api.crc.testing on 192.168.127.1:53: no such host
Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@AjayJagan logs which you put in this issue is part of `yarn run start-console` which is running in a separate terminal?

**Comment by AjayJagan** [comment]
> @AjayJagan logs which you put in this issue is part of `yarn run start-console` which is running in a separate terminal?

yes it is

**Comment by praveenkumar** [comment]
@AjayJagan From crc prospective everything is working since you can hit the apiserver endpoint and also `crc status` show cluster is running, now what confuse us here `api.crc.testing on 192.168.127.1:53` one, why it is failing because as part of VM it is resolve correctly. Have you tried same with a production grade cluster and can you share the logs like how it resolve for `http: proxy` ?

```
<crc_vm> dig api.crc.testing

; <<>> DiG 9.11.36-RedHat-9.11.36-3.el8_6.1 <<>> api.crc.testing
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4891
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;api.crc.testing.		IN	A

;; ANSWER SECTION:
api.crc.testing.	0	IN	A	192.168.127.2

;; Query time: 3 msec
;; SERVER: 192.168.127.1#53(192.168.127.1)
;; WHEN: Mon Nov 21 11:26:59 UTC 2022
;; MSG SIZE  rcvd: 64
```

**Comment by AjayJagan** [comment]
closing this issue as it is not related to CRC .. and is related to the dynamic plugin.
