### ISSUE TITLE
[Question] Objection to the use of StaleBot

### ISSUE THREAD

**Issue by nhojpatrick** [crc-org/crc#3429]
### General information

  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / Hyper-V / hyperkit / vfkit
  * Did you run `crc setup` before starting it (Yes/No)?
  * Running CRC on: Laptop / Baremetal-Server / VM

## CRC version
```bash
# Put `crc version` output here
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```

## CRC config
```bash
# Put `crc config view` output here
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1. Raise Bug
  2. Waiting a maintainer to deal with issue
  3. StaleBot marks it as stale as no maintainer has dealt with issue
  4. StaleBot closes issue as no maintainer has dealt with issue

### Expected
StaleBot can't mark an issue as stale until a maintainer as reviewed and commented, it's fine to mark it as stale is the issue author doesn't get back to you. 

### Actual
Issues get closed within being addressed

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by gbraad** [comment]
If people attend to the bugs, like the maintainers, the use of a stalebot is not necessarily wrong. Many of the issues that get closed are those to which the reporter did not follow up on a request.

I understand the frustration if an issue gets closed after a while, but both sides are responsible for keeping the conversation happening.

Ouf team is disciplined to review the issues that have been closed and pin them accordingly or follow up if we were to blame. If this didn't happen to a bug of you, please let us know.
