### ISSUE TITLE
3scale installation from Operator fails on a CRC server that is not connected to the network.

### ISSUE THREAD

**Issue by ghost** [crc-org/crc#3434]
Introduced product：OpenShift Container Platform4.8

・detailed content

On the CRC server in the offline environment, place the Operator catalog in the mirror registry built on Podman and execute the contents of the Red hat official manual below.

4.9.2. Disabling the default OperatorHub sources → 4.9.3. Pruning an index image → 4.9.4. Mirroring an Operator catalog (Run with option B)
→4.9.5. Creating a catalog from an index image

After executing the above manual, the 3scale operator will be displayed on Operatorhub, so when you install it, the following message will be output and it will fail.

Error message : Failed to pull image "registry.redhat.io/3scale-amp2/3scale-rhel7
-operator-metadata@sha256:2b709b801c9d28b16e6dd3a4c4b1c529d03b07e51cca2556e4f9b6ab7c8248e4":rpc error: 
code=Unknown desc = error pinging docker registry registry.io:Get "https://registry.redhat.io/v2/": dial tcp: 
lookup registry.redhat.io.on XXX.XXX.XXX.XXX:53:server misbehaving

・Desired behavior
I want to reference 3scale images from an internal registry, not an external registry.
[20220705_3scale-install.log](https://github.com/crc-org/crc/files/10120307/20220705_3scale-install.log)
[crc.log](https://github.com/crc-org/crc/files/10120308/crc.log)

**Comment by gbraad** [comment]
@Nttdata2022 it seems this is resolved; what did you do to solve this?
