### ISSUE TITLE
[BUG] cluster operators are still not stable after 10m

### ISSUE THREAD

**Issue by T0MASD** [crc-org/crc#3455]
## CRC version
```bash
CRC version: 2.11.0+823e40d
OpenShift version: 4.11.13
Podman version: 4.2.0
```
  

## CRC config
```bash
- consent-telemetry                     : no
```

## Host Operating System
```bash
NAME="Fedora Linux"
VERSION="38 (Rawhide Prerelease)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Rawhide Prerelease)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=rawhide
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=rawhide
```

### Steps to reproduce

  1.  crc start
  
### Expected

crc has better retry logic that handles case when openshift start-up takes more than 10minutes

### Actual
```
ERRO Cluster is not ready: cluster operators are still not stable after 10m44.750430206s 
```

**Comment by cfergeau** [comment]
> crc has better retry logic that handles case when openshift start-up takes more than 10minutes

It's fairly easy to increase this in the code, the hard part is to decide how long we should be waiting before giving up (there might be an issue with the cluster preventing it from starting up). 10 minutes is already a very long time to wait for a cluster, but the time we have to wait keeps increasing :(

**Comment by T0MASD** [comment]
Looking at the startup procedure
```
INFO 3 operators are progressing: image-registry, openshift-controller-manager, operator-lifecycle-manager-packageserver 
INFO 3 operators are progressing: image-registry, openshift-controller-manager, operator-lifecycle-manager-packageserver 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
ERRO Cluster is not ready: cluster operators are still not stable after 10m25.430766427s 
```
the `operators are progressing` logic tracks number of operators pending, could the timer be reset every time there's a change in a number of pending operators? This way if startup process gets really stuck, timeout would still occur.

**Comment by praveenkumar** [comment]
@T0MASD Can you please try latest version of CRC and create new issue if it is still exist?

**Comment by bytewhisperer11** [comment]
Hi,

I'm facing same issue with the following configuration and version:

```
OS: Ubuntu 24 LTS
Architecture: x86_64( AMD Ryzen 7 )
CRC config: 8 cpus | 16 GB RAM 
```

```
CRC version: 2.55.1+6252bc
OpenShift version: 4.19.13
MicroShift version: 4.19.7
```

Is there a particular reason why it was happening for the previous versions? It seems to persist for newer version as well.

**Comment by praveenkumar** [comment]
Can you create an issue with all the info instead putting that on closed issue?
