### ISSUE TITLE
[BUG] - crc setup fails on setting up crc daemon in RHEL 8.7

### ISSUE THREAD

**Issue by desaidhr** [crc-org/crc#3471]
### General information

  * OS: Linux 
  * Hypervisor: KVM 
  * Did you run `crc setup` before starting it ? Yes
  * Running CRC on: Baremetal-Server

## CRC version
```bash
CRC version: 2.12.0+74565a6
OpenShift version: 4.11.18
Podman version: 4.2.0
```
  
## CRC status
```bash
DEBU CRC version: 2.12.0+74565a6
DEBU OpenShift version: 4.11.18
DEBU Podman version: 4.2.0
DEBU Running 'crc status'
crc does not seem to be setup correctly, have you run 'crc setup'?
```

## CRC config
```bash
- consent-telemetry                     : yes
- preset                                : podman
```

## Host Operating System
```bash
NAME="Red Hat Enterprise Linux"
VERSION="8.7 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.7 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"

```

### Steps to reproduce

  1.  Run crc setup
 
### Expected
Should exit without error

### Actual
Throws error

### Logs
DEBU CRC version: 2.12.0+74565a6
DEBU OpenShift version: 4.11.18
DEBU Podman version: 4.2.0
DEBU Running 'crc setup'
INFO Using bundle path /home/dhruvd/.crc/cache/crc_podman_libvirt_4.2.0_amd64.crcbundle
DEBU Checking if systemd-resolved.service is running
DEBU Running 'systemctl status systemd-resolved.service'
DEBU Command failed: exit status 3
DEBU stdout: * systemd-resolved.service - Network Name Resolution
   Loaded: loaded (/usr/lib/systemd/system/systemd-resolved.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:systemd-resolved.service(8)
           https://www.freedesktop.org/wiki/Software/systemd/resolved
           https://www.freedesktop.org/wiki/Software/systemd/writing-network-configuration-managers
           https://www.freedesktop.org/wiki/Software/systemd/writing-resolver-clients
DEBU stderr:
INFO Checking if running as non-root
INFO Checking if running inside WSL2
INFO Checking if crc-admin-helper executable is cached
DEBU Running '/home/dhruvd/.crc/bin/crc-admin-helper-linux --version'
DEBU Found crc-admin-helper-linux version 0.0.12
DEBU crc-admin-helper executable already cached
INFO Checking for obsolete admin-helper executable
DEBU Checking if an older admin-helper executable is installed
DEBU No older admin-helper executable found
INFO Checking if running on a supported CPU architecture
DEBU GOARCH is amd64 GOOS is linux
INFO Checking minimum RAM requirements
DEBU Total memory of system is 810669899776 bytes
INFO Checking if crc executable symlink exists
INFO Checking if Virtualization is enabled
DEBU Checking if the vmx/svm flags are present in /proc/cpuinfo
DEBU CPU virtualization flags are good
INFO Checking if KVM is enabled
DEBU Checking if /dev/kvm exists
DEBU /dev/kvm was found
INFO Checking if libvirt is installed
DEBU Checking if 'virsh' is available
DEBU 'virsh' was found in /usr/bin/virsh
DEBU Checking 'virsh capabilities' for libvirtd/qemu availability
DEBU Running 'virsh --readonly --connect qemu:///system capabilities'
DEBU Found x86_64 hypervisor with 'hvm' capabilities
INFO Checking if user is part of libvirt group
DEBU Checking if current user is part of the libvirt group
DEBU Current user is already in the libvirt group
INFO Checking if active user/process is currently part of the libvirt group
INFO Checking if libvirt daemon is running
DEBU Checking if libvirtd service is running
DEBU Running 'systemctl status virtqemud.socket'
DEBU Command failed: exit status 3
DEBU stdout: * virtqemud.socket - Libvirt qemu local socket
   Loaded: loaded (/usr/lib/systemd/system/virtqemud.socket; disabled; vendor preset: disabled)
   Active: inactive (dead)
   Listen: /run/libvirt/virtqemud-sock (Stream)
DEBU stderr:
DEBU virtqemud.socket is neither running nor listening
DEBU Running 'systemctl status libvirtd.socket'
DEBU libvirtd.socket is running
INFO Checking if a supported libvirt version is installed
DEBU Checking if libvirt version is >=3.4.0
DEBU Running 'virsh -v'
INFO Checking if crc-driver-libvirt is installed
DEBU Checking if crc-driver-libvirt is installed
DEBU Running '/home/dhruvd/.crc/bin/crc-driver-libvirt version'
DEBU Found crc-driver-libvirt version 0.13.5
DEBU crc-driver-libvirt is already installed
INFO Checking crc daemon systemd service
DEBU Checking crc daemon systemd service
DEBU Checking if crc-daemon.service is running
DEBU Running 'systemctl --user status crc-daemon.service'
DEBU Command failed: exit status 1
DEBU stdout:
DEBU stderr: Failed to get properties: Transport endpoint is not connected
DEBU Could not get crc-daemon.service  status: Executing systemctl action failed:  exit status 1: Failed to get properties: Transport endpoint is not connected
DEBU Checking if crc-daemon.service has the expected content
INFO Checking crc daemon systemd socket units
DEBU Checking crc daemon systemd socket units
DEBU Checking if crc-http.socket is running
DEBU Running 'systemctl --user status crc-http.socket'
DEBU Command failed: exit status 1
DEBU stdout:
DEBU stderr: Failed to get properties: Transport endpoint is not connected
DEBU Could not get crc-http.socket  status: Executing systemctl action failed:  exit status 1: Failed to get properties: Transport endpoint is not connected
DEBU crc-http.socket is not running
INFO Setting up crc daemon systemd socket units
DEBU Setting up crc daemon systemd socket units
DEBU Setting up crc-http.socket
DEBU Running 'systemctl --user status crc-http.socket'
DEBU Command failed: exit status 1
DEBU stdout:
DEBU stderr: Failed to get properties: Transport endpoint is not connected
DEBU Could not get crc-http.socket  status: Executing systemctl action failed:  exit status 1: Failed to get properties: Transport endpoint is not connected
DEBU Starting crc-http.socket
DEBU Running 'systemctl --user enable crc-http.socket'
DEBU Command failed: exit status 1
DEBU stdout:
DEBU stderr: Failed to enable unit: Transport endpoint is not connected
Executing systemctl action failed:  exit status 1: Failed to enable unit: Transport endpoint is not connected

**Comment by cfergeau** [comment]
Are you running this through ssh? or are you directly connected to that machine? I expect `systemctl --user status` returns the same error?

**Comment by desaidhr** [comment]
I am running this through ssh. systemctl --user status return the same error. That makes me think, is it not a crc issue?

**Comment by praveenkumar** [comment]
@desaidhr try workaround which is mentioned https://github.com/crc-org/crc/issues/2690#issuecomment-912505017 I think we do need to put that in the docs in case someone want to setup crc using ssh.

**Comment by desaidhr** [comment]
@praveenkumar I tried loginctl enable-linger $USER as suggested. Its not working. Gives the same error

**Comment by praveenkumar** [comment]
@desaidhr Does the `systemctl status` also fail on that system or it is only failing for `--user` context?

**Comment by desaidhr** [comment]
systemctl status works as expected.  systemctl --user status fails with 'Failed to read server status: Transport endpoint is not connected' error

**Comment by praveenkumar** [comment]
@desaidhr Can you check `systemctl status systemd-user-sessions.service` if it is running? If not then can you try to start and enable it?

**Comment by desaidhr** [comment]
yes the said service is active

```bash
 systemd-user-sessions.service - Permit User Sessions
   Loaded: loaded (/usr/lib/systemd/system/systemd-user-sessions.service; static; vendor preset: disabl>
   Active: active (exited) since Thu 2023-01-05 22:08:37 IST; 13h ago
     Docs: man:systemd-user-sessions.service(8)
 Main PID: 3698 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 3355442)
   Memory: 0B
   CGroup: /system.slice/systemd-user-sessions.service

Jan 05 22:08:37 localhost.localdomain systemd[1]: Starting Permit User Sessions...
Jan 05 22:08:37 localhost.localdomain systemd[1]: Started Permit User Sessions.
```

**Comment by cfergeau** [comment]
Can you paste the output of `loginctl user-status $USER` ?

**Comment by desaidhr** [comment]
Pasted below the output of loginctl user-status $USER

```bash
           Since: Thu 2023-01-05 22:15:03 IST; 17h ago
           State: active
        Sessions: *3
          Linger: yes
            Unit: user-1001.slice
                  ├─session-3.scope
                  │ ├─5837 gdm-session-worker [pam/gdm-password]
                  │ ├─5877 /usr/bin/gnome-keyring-daemon --daemonize --login
                  │ ├─5884 /usr/libexec/gdm-x-session --register-session --run-script gnome-session
                  │ ├─5887 /usr/libexec/Xorg vt2 -displayfd 3 -auth /run/user/1001/gdm/Xauthority -nolisten tcp -background none -noreset -keeptty -novtswitch -verbose 3
                  │ ├─5948 /usr/libexec/gnome-session-binary
                  │ ├─6118 /usr/bin/gnome-shell
                  │ ├─6179 ibus-daemon --xim --panel disable
                  │ ├─6183 /usr/libexec/ibus-dconf
                  │ ├─6184 /usr/libexec/ibus-extension-gtk3
                  │ ├─6186 /usr/libexec/ibus-x11 --kill-daemon
                  │ ├─6275 /usr/libexec/gsd-power
                  │ ├─6276 /usr/libexec/gsd-print-notifications
                  │ ├─6278 /usr/libexec/gsd-rfkill
                  │ ├─6279 /usr/libexec/gsd-screensaver-proxy
                  │ ├─6280 /usr/libexec/gsd-sharing
                  │ ├─6281 /usr/libexec/gsd-sound
                  │ ├─6283 /usr/libexec/gsd-xsettings
                  │ ├─6289 /usr/libexec/gsd-wacom
                  │ ├─6292 /usr/libexec/gsd-smartcard
                  │ ├─6293 /usr/libexec/gsd-account
                  │ ├─6299 /usr/libexec/gsd-subman
                  │ ├─6307 /usr/libexec/gsd-a11y-settings
                  │ ├─6310 /usr/libexec/gsd-clipboard
                  │ ├─6313 /usr/libexec/gsd-color
                  │ ├─6315 /usr/libexec/gsd-datetime
                  │ ├─6318 /usr/libexec/gsd-housekeeping
                  │ ├─6320 /usr/libexec/gsd-keyboard
                  │ ├─6323 /usr/libexec/gsd-media-keys
                  │ ├─6324 /usr/libexec/gsd-mouse
                  │ ├─6383 /usr/libexec/gsd-disk-utility-notify
                  │ ├─6385 /usr/bin/gnome-software --gapplication-service
                  │ ├─6393 /usr/libexec/tracker-miner-apps
                  │ ├─6394 /usr/libexec/tracker-miner-fs
                  │ ├─6442 /usr/libexec/ibus-engine-simple
                  │ └─6541 /usr/libexec/gsd-printer
                  └─user@1001.service
                    ├─at-spi-dbus-bus.service
                    │ ├─6010 /usr/libexec/at-spi-bus-launcher
                    │ ├─6016 /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-address 3
                    │ └─6019 /usr/libexec/at-spi2-registryd --use-gnome-session
                    ├─dbus.service
                    │ ├─5945 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
                    │ ├─6188 /usr/libexec/ibus-portal
                    │ ├─6206 /usr/libexec/gnome-shell-calendar-server
                    │ ├─6217 /usr/libexec/goa-daemon
                    │ ├─6241 /usr/libexec/goa-identity-service
                    │ └─6460 /usr/libexec/dconf-service
                    ├─evolution-addressbook-factory.service
                    │ ├─6465 /usr/libexec/evolution-addressbook-factory
                    │ └─6494 /usr/libexec/evolution-addressbook-factory-subprocess --factory all --bus-name org.gnome.evolution.dataserver.Subprocess.Backend.AddressBookx6465x2 --own-path /org/gnome/evolution/dataserver/Subprocess/Back>
                    ├─evolution-calendar-factory.service
                    │ ├─6367 /usr/libexec/evolution-calendar-factory
                    │ └─6435 /usr/libexec/evolution-calendar-factory-subprocess --factory all --bus-name org.gnome.evolution.dataserver.Subprocess.Backend.Calendarx6367x2 --own-path /org/gnome/evolution/dataserver/Subprocess/Backend/Ca>
                    ├─evolution-source-registry.service
                    │ └─6210 /usr/libexec/evolution-source-registry
                    ├─gvfs-afc-volume-monitor.service
                    │ └─6265 /usr/libexec/gvfs-afc-volume-monitor
                    ├─gvfs-daemon.service
                    │ ├─6157 /usr/libexec/gvfsd
                    │ └─6162 /usr/libexec/gvfsd-fuse /run/user/1001/gvfs -f -o big_writes
                    ├─gvfs-goa-volume-monitor.service
                    │ └─6261 /usr/libexec/gvfs-goa-volume-monitor
                    ├─gvfs-gphoto2-volume-monitor.service
                    │ └─6254 /usr/libexec/gvfs-gphoto2-volume-monitor
                    ├─gvfs-mtp-volume-monitor.service
                    │ └─6246 /usr/libexec/gvfs-mtp-volume-monitor
                    ├─gvfs-udisks2-volume-monitor.service
                    │ └─6230 /usr/libexec/gvfs-udisks2-volume-monitor
                    ├─init.scope
                    │ ├─5850 /usr/lib/systemd/systemd --user
                    │ └─5853 (sd-pam)
                    ├─pulseaudio.service
                    │ └─5872 /usr/bin/pulseaudio --daemonize=no --log-target=journal
                    ├─tracker-store.service
                    │ └─6386 /usr/libexec/tracker-store
                    └─xdg-permission-store.service
                      └─6196 /usr/libexec/xdg-permission-store
```

**Comment by praveenkumar** [comment]
@desaidhr did you make any kind of configuration setting because on a clean 8.7 installation this is not reproducible? Can you provide the info around how did you install and configure the system?

**Comment by desaidhr** [comment]
Other than a proxy setting to enable internet connectivity, the machine doesnot have anything custom. RHEL was installed from the iso downloaded from redhat site. It is registered and is updated.

**Comment by masayag** [comment]
I faced a similar issue with RHEL-8.9. Fixed by changing `/etc/ssh/sshd_config` to:
```
X11Forwarding yes
X11DisplayOffset 10
X11UseLocalhost yes
```
and using `ssh -X user@host` to log in to the RHEL server.
Then `systemctl --user status` state was changed to running and `crc setup` was completed successfully.

**Comment by cfergeau** [comment]
https://github.com/crc-org/crc/issues/2690#issuecomment-912505017 could also help with this.

**Comment by praveenkumar** [comment]
@desaidhr can you try https://github.com/crc-org/crc/issues/3471#issuecomment-1687715057 one if that fix your issue?

**Comment by desaidhr** [comment]
@praveenkumar Thanks for reaching out. I have moved on from this thread and no longer have the setup to validate.

**Comment by praveenkumar** [comment]
> I have moved on from this thread and no longer have the setup to validate.

@desaidhr In that case, I am going to close this issue, Please reopen if you hit it again.
