### ISSUE TITLE
[BUG] crc and snc don't use the same routes-controller image

### ISSUE THREAD

**Issue by cfergeau** [crc-org/crc#3502]
snc uses `quay.io/crcont/routes-controller:${image_tag}`
https://github.com/crc-org/snc/blob/4ada0a93e0e3de2b0fbd328ef43096c7563a7ed9/createdisk.sh#L79-L80

crc uses `quay.io/crcont/routes-controller:latest`
https://github.com/crc-org/crc/blob/32916615274dab8064a7a99b1de7fb4a063dff22/pkg/crc/machine/start.go#L835-L844

Not sure which one should be changed, the easiest would be to tag `quay.io/crcont/routes-controller:${image_tag}` as `latest` when pulling it in `snc`, but I'm not sure `crictl` supports setting tags.

**Comment by cfergeau** [comment]
I suspect because of this inconsistency crc pulls the routes-controller image from quay at cluster creation instead of reusing the cached one. If the cached image is still the latest one, it's not very important, but if the cached one is no longer also the latest, this is more problematic

**Comment by gbraad** [comment]
> If the cached image is still the latest one, it's not very important, 

inconsistencies like this can lead to hard to track issues. we can't assume these are both pointing to 'latest'. It would be better to use a tag that is identical on both ends.

**Comment by praveenkumar** [comment]
In case of openshift preset we should use the image tag as `openshift_version` since we are now building it for each openshift release and for `podman` preset we should use the `latest` tag. 

Edit: looks like we don't need this image for podman preset and we might put this logic to the snc side and in crc side just create the deployment/pod.

**Comment by praveenkumar** [comment]
This is fixed by https://github.com/crc-org/snc/commit/fe6a6d2ddb68e16942810644173b87b4cc95765a

/close
