### ISSUE TITLE
[Enhance] Remove tray from installation payload

### ISSUE THREAD

**Issue by gbraad** [crc-org/crc#3507]
The current installer for CRC includes the tray which has not been maintained for quite some time due to the introduction of Podman Desktop. Since effort will now be shifted to focus on the CRC extension, we have to consider removing the tray payload from the installer. For the following platforms.

  * [x] Windows (merged: 2023-03-01: https://github.com/crc-org/crc/pull/3512)
  * [x] macOS

This will have a side-effect for our onboarding experience. We need to decide if for the time being we will deliver two installers; with tray and onboarding and one without the tray, or just the installer without.

**Comment by anjannath** [comment]
The tray on-boarding flow (onboarding wizard) does the following things:

1. Enabling telemetry via crc config
2. Selection of the **Preset** (podman or openshift)
3. based on the Preset (if openshift is chosen) a pull-secret is configured to be used by crc
4. and finally running `crc setup` 

If the tray is removed, the expected user flow would be:

1. Install the msi and reboot
2. run `crc setup` from powershell/cmd
3. run `crc start` to start the instance

or if user wants to use a non-default preset, e.g the podman preset:

1. Install the msi and reboot
2. run `crc config set preset podman`
3. run `crc setup`
4. run `crc start` to start the podman instance

**Comment by cfergeau** [comment]
For macOS, I have this in one of my branches: https://github.com/cfergeau/crc/commit/9279e8dc3cb83c8409a7ff7ca10dfa025d8a1cf5

**Comment by gbraad** [comment]
Choco package; #762

**Comment by anjannath** [comment]
reopening as for the macOS pkg separating the tray component as a selectable feature is remaining

**Comment by gbraad** [comment]
Added a comment/task list at the top to reflect this

**Comment by gbraad** [comment]
@anjannath can you have a look at the macOS side for review? As I see, https://github.com/crc-org/crc/pull/3542 got merged. Can this be closed?
