### ISSUE TITLE
[BUG] After Update to 2.13.1 (from 2.11.0) crc does not work behind corporate proxy any more 

### ISSUE THREAD

**Issue by jochenr** [crc-org/crc#3510]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it? Yes
  * Running CRC on: Laptop

## CRC version
```bash
CRC version: 2.13.1+b5b864fd
OpenShift version: 4.12.0
Podman version: 4.3.1
```
  
## CRC status
```bash
time="2023-02-13T08:40:28+01:00" level=warning msg="Could not load system CA pool: crypto/x509: system root pool is not available on Windows"
DEBU CRC version: 2.13.1+b5b864fd
DEBU OpenShift version: 4.12.0
DEBU Podman version: 4.3.1
DEBU Running 'crc status'
CRC VM:          Running
OpenShift:       Degraded (v4.12.0)
RAM Usage:       7.613GB of 16.8GB
Disk Usage:      14.15GB of 32.74GB (Inside the CRC VM)
Cache Usage:     13.83GB
Cache Directory: C:\Users\XXX\.crc\cache
```

## CRC config
```bash
- consent-telemetry                     : no
- http-proxy                            : http://xxx:******@corporateproxy:8080
- https-proxy                           : http://xxx:******@corporateproxy:8080
- no-proxy                              : 127.0.0.1,localhost,.xxxxx.ads,.testing,openshift-image-registry.svc
- proxy-ca-file                         : C:\xxxx\crc\proxy-ca_2023.pem
- pull-secret-file                      : C:\xxxx\crc\pull-secret.txt
```

## Host Operating System
```bash
Hostname:                                        xxxxx
Betriebssystemname:                            Microsoft Windows 10 Enterprise
Betriebssystemversion:                         10.0.19044 Nicht zutreffend Build 19044
Betriebssystemhersteller:                      Microsoft Corporation
Betriebssystemkonfiguration:                   Mitglied der Domäne/Arbeitsgruppe
Betriebssystem-Buildtyp:                       Multiprocessor Free
Registrierter Benutzer:                        CColumbus
Registrierte Organisation:
Produkt-ID:                                    00329-00000-00003-AA425
Ursprüngliches Installationsdatum:             24.02.2021, 17:59:41
Systemstartzeit:                               13.02.2023, 07:38:56
Systemhersteller:                              LENOVO
Systemmodell:                                  20QT000HGE
Systemtyp:                                     x64-based PC
Prozessor(en):                                 1 Prozessor(en) installiert.
                                               [01]: Intel64 Family 6 Model 158 Stepping 13 GenuineIntel ~2592 MHz
BIOS-Version:                                  LENOVO N2OET47W (1.34 ), 06.08.2020
Windows-Verzeichnis:                           C:\WINDOWS
System-Verzeichnis:                            C:\WINDOWS\system32
Startgerät:                                    \Device\HarddiskVolume2
Systemgebietsschema:                           de;Deutsch (Deutschland)
Eingabegebietsschema:                          de;Deutsch (Deutschland)
Zeitzone:                                      (UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien
Gesamter physischer Speicher:                  32.543 MB
Verfügbarer physischer Speicher:               7.910 MB
Virtueller Arbeitsspeicher: Maximale Größe:    43.807 MB
Virtueller Arbeitsspeicher: Verfügbar:         13.875 MB
Virtueller Arbeitsspeicher: Zurzeit verwendet: 29.932 MB
```

### Steps to reproduce

  1. uninstall version 2.11.0 (which worked well)  (with delete, cleanup and manula deletion of ".crc" folder in user-profile
  2. reboot
  3. install 2.13.1
  4. set configs for proxy (a as shown above....exactly the same as I had for version 2.11.0)
  5. crc setup
  6. crc start
  7. oc-env...oc ....login.....
  8. oc new-project ad-hoc-container
  9. oc import-image ubi8/openjdk-17:1.14-4.1666624568 --from=registry.access.redhat.com/ubi8/openjdk-17:1.14-4.1666624568 --confirm
  10. oc run ad-hoc-java --image=ubi8/openjdk-17:1.14-4.1666624568 --command -- sleep 600s

### Expected
a pod with name "ad-hoc-java" should run

### Actual
the status of the pod stays "ImagePullBAckOff"

### Logs
[...]
time="2023-02-13T07:55:21+01:00" level=debug msg="CRC version: 2.13.1+b5b864fd\n"
time="2023-02-13T07:55:21+01:00" level=debug msg="OpenShift version: 4.12.0\n"
time="2023-02-13T07:55:21+01:00" level=debug msg="Podman version: 4.3.1\n"
time="2023-02-13T07:55:21+01:00" level=debug msg="Running 'crc daemon'"
time="2023-02-13T07:55:21+01:00" level=info msg="listening vsock://00000400-FACB-11E6-BD58-64006A7986D3"
time="2023-02-13T07:55:21+01:00" level=info msg="listening \\\\.\\pipe\\crc-http"
time="2023-02-13T08:05:36+01:00" level=info msg="new connection from 1606808b-0000-0000-0000-000000000000:5492b103-facb-11e6-bd58-64006a7986d3 to 00000000-0000-0000-0000-000000000000:00000400-facb-11e6-bd58-64006a7986d3"
time="2023-02-13T08:06:20+01:00" level=trace msg="net.Dial() = dial tcp 10.217.4.1:443: connectex: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat."
time="2023-02-13T08:06:20+01:00" level=trace msg="net.Dial() = dial tcp 10.217.4.1:443: connectex: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat."
time="2023-02-13T08:06:25+01:00" level=trace msg="net.Dial() = dial tcp 184.30.17.152:443: connectex: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat."
time="2023-02-13T08:06:38+01:00" level=trace msg="net.Dial() = dial tcp 184.30.17.152:443: connectex: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat."
time="2023-02-13T08:06:40+01:00" level=trace msg="net.Dial() = dial tcp 184.30.17.152:443: connectex: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat."
[...]
time="2023-02-13T09:05:51+01:00" level=debug msg="Stopping udp proxy (read udp 178.63.52.50:123: i/o timeout)"
time="2023-02-13T09:05:51+01:00" level=debug msg="Stopping udp proxy (read udp 178.63.52.31:123: i/o timeout)"
time="2023-02-13T09:05:55+01:00" level=debug msg="Stopping udp proxy (read udp 162.159.200.123:123: i/o timeout)"
time="2023-02-13T09:05:58+01:00" level=debug msg="Stopping udp proxy (read udp 129.70.132.34:123: i/o timeout)"
[...]

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```
...yes, I did that!

**Comment by cfergeau** [comment]
Thanks a lot for reporting this bug! I've been able to reproduce this bug with 4.12.1. This only happens when you configure a proxy, and when your network infrastructure drop direct http/https traffic. The main cause for this is a bug in OpenShift Machine Config Operator which is fixed in 4.12.3. The next crc release in a few weeks should work fine for your use case.

**Comment by jochenr** [comment]
Thank you very much👍😀

**Comment by gbraad** [comment]
any follow up? did the issue get fixed?

**Comment by jochenr** [comment]
I haven't tried with a current Version.
I'l try and tell here next week....

Greetings from Red Hat Summit,  Boston

**Comment by jochenr** [comment]
the bug seems to be solved in version

´´´
CRC version: 2.19.0+a71226
OpenShift version: 4.12.13
´´´
thank you

**Comment by phil123thi** [comment]
Im seeing this error in the latest version of CRC for linux CRC version 2.47 . anyone else has reported issue or found way to fix it
