### ISSUE TITLE
Improve bundle versioning

### ISSUE THREAD

**Issue by cfergeau** [crc-org/crc#3513]
At the moment, we use openshift version/podman version as the bundle version. This means we cannot easily ship an updated bundle based on the same podman version but with updated packages (bugfixes/CVEs). This is more noticeable with the podman bundles since the podman version is updated infrequently.
We could support an appended 'release' tag to the version to allow for this `crc_podman_4.3.1-2`,  `crc_podman_4.3.1-3`, ... or drastically change the version we use, and switch to the coreos version `crc_podman_37.20230122.3.0` instead of the podman version. Hopefully the exact podman version can become a non-important internal detail (ie no impactful bugs/breaking changes)

**Comment by praveenkumar** [comment]
@crc-org/crc-team since our plan is to discontinue podman preset so better to differ it and close?
