### ISSUE TITLE
[QE] Add custom disk size on basic scneario for e2e

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/crc#3518]
Previously `e2e` tested disk resize after the cluster was started with default values. Recently a [bug](https://github.com/crc-org/crc/issues/3496) was discovered and solved, as the disk resize did not take effect with hyper-v on first cluster start.

To cover this test case and avoid overtime running `e2e` we decide to setup a custom disk size for the initial start of the cluster in one of the scenarios.

**Comment by praveenkumar** [comment]
closing this issue since it is already fixed.
