### ISSUE TITLE
[BUG] go-toolset:1.19 not available yet

### ISSUE THREAD

**Issue by jsliacan** [crc-org/crc#3538]
`go-toolset:1.19` is not available yet, so these images need to be built with an older tag (I used `1.18` for the `2.15.0` release):

- https://github.com/crc-org/crc/blob/72256c3cb00ac01519b26658dd5cfb0dd09b37a1/images/build-e2e/Dockerfile#L1
- https://github.com/crc-org/crc/blob/72256c3cb00ac01519b26658dd5cfb0dd09b37a1/images/build-integration/Dockerfile#L1

Not sure how long before 1.19 exists. If soon, maybe there's no need to decrement the tag. This issue is meant to keep track of this.

**Comment by cfergeau** [comment]
Hrm, this is just weird, this should be `registry.access.redhat.com/ubi9/go-toolset:1.19 as builder` but even with ubi9 there is no such `1.19` tag, but pulling `registry.access.redhat.com/ubi9/go-toolset:1.17` or `registry.access.redhat.com/ubi9/go-toolset:1.18` gives me an image with go 1.19.6 in both cases.
We probably can just go with `registry.access.redhat.com/ubi8/go-toolset:latest` as the image

**Comment by jsliacan** [comment]
Interesting, it didn't occur to me to actually check what's in the image (was hoping it would be the same thing it says on the tin). I'm happy to go with anything that works :). 

EDIT: Actually, if we can go with `latest`, that'd probably be good as we wouldn't need to update these lines again (unless issues arise).

**Comment by praveenkumar** [comment]
>but pulling registry.access.redhat.com/ubi9/go-toolset:1.17 or registry.access.redhat.com/ubi9/go-toolset:1.18 gives me an image with go 1.19.6 in both cases. 

@cfergeau To me it does provide only 1.18.9 and 1.17.12 go version respective.
```
$ podman run --rm -it registry.access.redhat.com/ubi9/go-toolset:1.18 /usr/bin/go version
go version go1.18.9 linux/amd64

$ podman run --rm -it registry.access.redhat.com/ubi9/go-toolset:1.17 /usr/bin/go version
go version go1.17.12 linux/amd64
```

**Comment by praveenkumar** [comment]
>We probably can just go with registry.access.redhat.com/ubi8/go-toolset:latest as the image 

we avoided latest to make sure all the builders and CI have same major version of golang. Like till now we were using 1.17 because of oc mac issue but if we used latest then 1.18 version of golang is used and have issue for mac.

**Comment by cfergeau** [comment]
> @cfergeau To me it does provide only 1.18.9 and 1.17.12 go version respective

Ah yeah, I screwed up the test.

**Comment by cfergeau** [comment]
> > We probably can just go with registry.access.redhat.com/ubi8/go-toolset:latest as the image
> 
> we avoided latest to make sure all the builders and CI have same major version of golang. Like till now we were using 1.17 because of oc mac issue but if we used latest then 1.18 version of golang is used and have issue for mac.

The builders for the official releases are not using any of the go binaries from these images, so this is irrelevant here.

>  Like till now we were using 1.17 because of oc mac issue but if we used latest then 1.18 version of golang is used and have issue for mac.

But this is fixed upstream now, so we no longer have to build using go 1.17. The `go-toolset` images don't have fixed go versions yet though.

**Comment by praveenkumar** [comment]
>The builders for the official releases are not using any of the go binaries from these images, so this is irrelevant here.

Yes, but it at least uses same go version ( major one). In the past we observed that if every major go release have some effect on linting, deprecated library and mod side. So if we mismatch the major go version from CI to our official release builder then last moment we will find out something is failing because of different version. So I am favor to have same major version in CI which is also part of our official builders.

**Comment by jsliacan** [comment]
Oudated, we're on  go-toolset 1.20 now.
