### ISSUE TITLE
Always show uncompress progress for use with the podman-desktop Extension

### ISSUE THREAD

**Issue by gbraad** [crc-org/crc#3546]
When we download we will show the download progress, but for uncompress we suppress this behavior. For the PD extension we need this infornation in the UI and it is the easiest way for now to expose it.

https://github.com/crc-org/crc/blob/1425c16d6ca9ae043f4ddcb817f7317443aa70d2/pkg/extract/extract.go#L25-L31

We originally suppressed this due to the use in non-terminal environments, although this is now less relevant.

**Comment by praveenkumar** [comment]
if we want to always show it then just remove the `terminal.IsTerminal(int(os.Stdout.Fd())` terminal check which prevent it to show in case it is run in a non-terminal process.

**Comment by cfergeau** [comment]
The podman-desktop extension is running `crc` in a context where `terminal.IsTerminal(int(os.Stdout.Fd()))` is false if I understand correctly?
Might be better to add the same behaviour for the download progress (only show in terminal envs), together with a `--show-progress` flag? This way we keep the non-terminal behaviour, and allow the extension to get what it wants?

**Comment by gbraad** [comment]
The question in that case is; do we really want to add more complex behavior for something we might not even need anymore. We have not seen reports that the progress indicator for the download was giving errors. (Note; this only happens when `crc setup` is used).

**Comment by evidolob** [comment]
>The podman-desktop extension is running crc in a context where terminal.IsTerminal(int(os.Stdout.Fd())) is false if I understand correctly?

@cfergeau Yes, that is the case, I was wondering of inconsistency, we show progress for downloading, bud don't show for uncompress.

**Comment by gbraad** [comment]
For consistency I rather remove the complexity as it seems no issues have come from this.

To allow these bars to be hidden, we can solve that as part of an improvement in: #3550.
