### ISSUE TITLE
[BUG] CRC fails on macOS 12.6.3 (image from Github Actions)

### ISSUE THREAD

**Issue by danielmenezesbr** [crc-org/crc#3553]
CRC fails on macOS 12.6.3.

### General information

  * OS: macOS 12.6.3 (Image from Github Actiions: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md)
  * Hypervisor: vfkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
# Put `crc version` output here
CRC version: 2.15.0+72256c3c
OpenShift version: 4.12.5
Podman version: 4.3.1```

## CRC status
```bash
# Put `crc status --log-level debug` output here
DEBU CRC version: 2.15.0+72256c3c                 
DEBU OpenShift version: 4.12.5                    
DEBU Podman version: 4.3.1                        
DEBU Running 'crc status'                         
CRC VM:          Running
OpenShift:       Unreachable (v4.12.5)
RAM Usage:       5.078GB of 9.399GB
Disk Usage:      14.06GB of 32.74GB (Inside the CRC VM)
Cache Usage:     36.82GB
Cache Directory: /Users/vncuser/.crc/cache
```

## CRC config
```bash
# Put `crc config view` output here
- consent-telemetry                     : no
- pull-secret-file                      : /Users/vncuser/pull-secret
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
ProductName:	macOS
ProductVersion:	12.6.3
BuildVersion:	21G419
```

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Actual
Failed to update pull secret on the disk

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on https://gist.github.com/danielmenezesbr/13997ffd0e539dbdf73c7bea69c14483 and post the link in the issue.

```bash
Mac-1679343208412:~ vncuser$ ssh -i /Users/vncuser/.crc/machines/crc/id_ecdsa -p 2222 core@127.0.0.1
Red Hat Enterprise Linux CoreOS 412.86.202302170236-0  Part of OpenShift 4.12, RHCOS is a Kubernetes native operating system  managed by the Machine Config Operator (`clusteroperator/machine-config`).
WARNING: Direct SSH access to machines is not recommended; instead,make configuration changes via `machineconfig` objects:  https://docs.openshift.com/container-platform/4.12/architecture/architecture-rhcos.html
---
[core@crc-9ltqk-master-0 ~]$ KUBE_CONFIG=/opt/kubeconfig kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by cfergeau** [comment]
Is this running on bare metal? Or is this a macOS VM where you are trying to run crc?
This error from the end of the log is seen often in nested virtualization setups:
```
DEBU error: Temporary error: pull secret not updated to disk - sleeping 2s 
DEBU retry loop: attempt 94                       
DEBU Running SSH command: <hidden>                
DEBU SSH command succeeded                        
DEBU error: Temporary error: pull secret not updated to disk - sleeping 2s 
DEBU RetryAfter timeout after 95 tries            
Failed to update pull secret on the disk: Temporary error: pull secret not updated to disk (x95)
Mac-1679343208412:~ vncuser$ 
```

**Comment by danielmenezesbr** [comment]
> Is this running on bare metal? Or is this a macOS VM where you are trying to run crc? This error from the end of the log is seen often in nested virtualization setups:
> 
> ```
> DEBU error: Temporary error: pull secret not updated to disk - sleeping 2s 
> DEBU retry loop: attempt 94                       
> DEBU Running SSH command: <hidden>                
> DEBU SSH command succeeded                        
> DEBU error: Temporary error: pull secret not updated to disk - sleeping 2s 
> DEBU RetryAfter timeout after 95 tries            
> Failed to update pull secret on the disk: Temporary error: pull secret not updated to disk (x95)
> Mac-1679343208412:~ vncuser$ 
> ```

Not sure if this is an environment with nested virtualization. The environment is the same as the [CRC uses in Github Actions](https://github.com/crc-org/crc/actions/workflows/macos-installer.yml).

@cfergeau, do you know if CRC is ready to use after "crc start" used in [CRC build for MacOS](https://github.com/crc-org/crc/actions/runs/4478743132/jobs/7871887849#step:11:22)?

**Comment by cfergeau** [comment]
> do you know if CRC is ready to use after "crc start" used in [CRC build for MacOS](https://github.com/crc-org/crc/actions/runs/4478743132/jobs/7871887849#step:11:22)?

Note that in this link/action, the podman preset/bundle is used, not the openshift/okd preset. The error message about pull secret can only occur with an openshift cluster. If you are trying to run a full openshift cluster from a github action, I'd guess you'll need your own powerful runner?
