### ISSUE TITLE
[BUG] Status reports podman preset while microshift is running

### ISSUE THREAD

**Issue by evidolob** [crc-org/crc#3592]
### General information

  * OS: macOS
  * Hypervisor: hyperkit 
  * Did you run `crc setup` before starting it: Yes
  * Running CRC on: Laptop

## CRC version
```bash
CRC version: 2.16.0+05b62a75
OpenShift version: 4.12.9
Podman version: 4.4.1
```
  
## CRC status
```bash
DEBU CRC version: 2.16.0+05b62a75
DEBU OpenShift version: 4.12.9
DEBU Podman version: 4.4.1
DEBU Running 'crc status'
CRC VM:          Running
RAM Usage:       1.196GB of 3.913GB
Disk Usage:      4.746GB of 16.1GB (Inside the CRC VM)
Cache Usage:     72.04GB
Cache Directory: /Users/yevhen/.crc/cache
```

## CRC config
```bash
- consent-telemetry                     : no
- preset                                : microshift
```

## Host Operating System
```bash
ProductName:		macOS
ProductVersion:		13.3
BuildVersion:		22E252
```

### Steps to reproduce

  1.  Configure crc to use `microshift` bundle
  2. Start crc with `microshift` bundle
  3. Call `curl -GET -i --unix-socket <home>/.crc/crc-http.sock http://localhost/api/status` to get status in json 

### Expected
```json
{"CrcStatus":"Running", "Preset":"microshift", ...}
```

### Actual
```json
{"CrcStatus":"Running", "Preset":"podman",  ...}
```

**Comment by evidolob** [comment]
Looks like the problem there https://github.com/crc-org/crc/blob/0bce019118562bece4ac55fd99324bb59ee61d3a/pkg/crc/machine/status.go#L38-L45

**Comment by gbraad** [comment]
@praveenkumar This should be fixed.
