### ISSUE TITLE
Follow-up: Try to use ModifyConfig function as part of merging the kubeconfig file

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/crc#3602]
As of now to merge the 2 kubeconfig files we create separate objects of the config and the iterate second one and put all the cluster/auth/user info but kube go-client have `ModifyConfg`  function in  `tools/clientcmd/config.go` package, need to figure out if that also do same or not. 
 
discussion: https://github.com/crc-org/crc/pull/3597#discussion_r1164484184

**Comment by gbraad** [comment]
@praveenkumar it concerns this piece of code, right?

https://github.com/crc-org/crc/blob/2875a7441f467e630c62760b49a800f60857afbf/pkg/crc/machine/kubeconfig.go#L235-L264

**Comment by praveenkumar** [comment]
@gbraad yes this is piece of code we want to improve.

**Comment by anjannath** [comment]
done via #3910
