### ISSUE TITLE
[BUG] OperatorHub shows less number of operators

### ISSUE THREAD

**Issue by AjayJagan** [crc-org/crc#3607]
### General information

  * OS: macOS M1
  * Hypervisor: vfkit
  * Did you run `crc setup` before starting it: Yes
  * Running CRC on: Laptop

## CRC version
```bash
CRC version: 2.16.0+05b62a75
OpenShift version: 4.12.9
Podman version: 4.4.1
```
  
## CRC status
```bash
DEBU CRC version: 2.16.0+05b62a75
DEBU OpenShift version: 4.12.9
DEBU Podman version: 4.4.1
DEBU Running 'crc status'
CRC VM:          Running
OpenShift:       Running (v4.12.9)
RAM Usage:       10.11GB of 16.34GB
Disk Usage:      17.08GB of 32.74GB (Inside the CRC VM)
Cache Usage:     37.04GB
Cache Directory: /Users/ajay/.crc/cache
```

## CRC config
```bash
- consent-telemetry                     : no
- enable-cluster-monitoring             : true
```

## Host Operating System
```bash
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261
```

### Steps to reproduce

  1. `crc setup`
  2.  `crc start -c 8 -m 16000`
  3.  go to https://console-openshift-console.apps-crc.testing
  4.  log in as `kubeadmin`
  5. Go to Operators -> OperatorHub on the side pane.

### Expected
The operator list should be shown with 400+ operators

### Actual
The operator list consist of lesser number of operators. The count is 58.

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
Today I tried out on linux and able to see all the operators in the console also. Can you check if all the pods for the operator is running as expected?

```
 $ oc get pods -n openshift-marketplace
NAME                                    READY   STATUS    RESTARTS   AGE
certified-operators-r2q4r               1/1     Running   0          35d
community-operators-wzzmt               1/1     Running   0          35d
marketplace-operator-7b7f77bfdd-r9m7w   1/1     Running   0          35d
redhat-marketplace-nbzhx                1/1     Running   0          35d
redhat-operators-8h6kp                  1/1     Running   0          35d
```

![Screenshot from 2023-05-03 11-01-25](https://user-images.githubusercontent.com/410007/235839907-b836a495-457d-4608-8520-cd91aa6f7019.png)

**Comment by praveenkumar** [comment]
I talked with console team and figure out now operator hub on console filter out the platform/node arch. M1 is arm64 and there are only few operators which have images for it and that's the reason it is only showing `51` . More details around it can be found https://issues.redhat.com/browse/CONSOLE-3190 / https://github.com/openshift/enhancements/pull/1014 here.

Closing this now.
