### ISSUE TITLE
[BUG] [Mac] 2.17.0 release does not use admin-helper and vfkit binary from installer

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/crc#3608]
admin-helper and vfkit binary is downloading as part of setup instead using from the installer on Mac. Looks like we introduce some regression when we separated tray from the binary as part of package.

**Comment by cfergeau** [comment]
This is a regression introduced in https://github.com/crc-org/crc/commit/09de4978241d5f5715218c326a501fc7493f853b
```
-packagedir: clean embed-download-darwin macos-universal-binary
+packagedir: clean embed-download-darwin $(BUILD_DIR)/macos-universal/crc
```
We no longer build a release binary for the macos installer, so the binary does not use the installed vfkit/crc-admin-helper.

**Comment by cfergeau** [comment]
@anjannath

**Comment by cfergeau** [comment]
I suspect telemetry will also be broken on macos for this release.

**Comment by anjannath** [comment]
yes, telemetry is also broken :(

**Comment by anjannath** [comment]
> This is a regression introduced in [09de497](https://github.com/crc-org/crc/commit/09de4978241d5f5715218c326a501fc7493f853b)
> 
> ```
> -packagedir: clean embed-download-darwin macos-universal-binary
> +packagedir: clean embed-download-darwin $(BUILD_DIR)/macos-universal/crc
> ```
> 
> We no longer build a release binary for the macos installer, so the binary does not use the installed vfkit/crc-admin-helper.

This change was unnecessary, i thought since `macos-release-binary` was a `.PHONY` target it'll always run even if the `out/macos-universal/crc` was already present so made `packagedir` explicitly depend on the file at `out/macos-universal/crc` :(

**Comment by cfergeau** [comment]
Misc ways to detect this regression during release testing:
- run `rm -rf ~/.crc/bin` before the tests
- check if after `crc setup`, there are vfkit/crc-admin-helper* binaries in `~/.crc/bin`
- or check `crc setup` output for `INFO Caching crc-admin-helper executable` and `INFO Setting up virtualization with vfkit`

We could also add some banner when starting a non-release binary.

**Comment by anjannath** [comment]
We can also add a check in the installer generation jobs, to make sure that the `installerBuild=true` is set on the CRC binary its using, something like:
```
$ strings out/windows-amd64/crc | grep -e "-ldflags" | grep installerBuild=true
```

**Comment by jsliacan** [comment]
> run rm -rf ~/.crc/bin before the tests

We do remove the entire `~/.crc` folder each time. See [this](https://gitlab.cee.redhat.com/crc/qe-platform/-/blob/master/support/images/crc-support/scripts/linux/distributable-setup.sh#L7) - I think that's the right place (for linux)... After we do that though, we still need to introduce checks. Is that what you meant?

**Comment by cfergeau** [comment]
Yes, this is what I meant, the `rm` is a required preliminary step. The logs I mentioned won't be shown if the binaries are already cached in ~/.crc
