### ISSUE TITLE
[BUG] No bundle type check during `crc setup`

### ISSUE THREAD

**Issue by cfergeau** [crc-org/crc#3615]
### General information

  * OS: macOS (should affect all OSes the same)
  * Did you run `crc setup` before starting it (Yes/No)?
  * Running CRC on: Laptop
  * 
## CRC version
```bash
# Put `crc version` output here
Build from git, commit 2351a01dd
```  

### Steps to reproduce

  1. `crc config set preset openshift`
  2. `crc setup --bundle ~/crc_podman_vfkit_4.4.2_amd64.crcbundle`
```
Your system is correctly setup for using CRC. Use 'crc start' to start the instance
```
  3. `crc start --bundle ~/crc_podman_vfkit_4.4.2_amd64.crcbundle`
```
Preset openshift is used but bundle is provided for podman preset
```

### Expected

`crc setup` detects the bundle mismatch

### Actual

`crc setup` is successful, and tells me to run `crc start`

**Comment by gbraad** [comment]
The execution of `crc setup` should fail with an error message that the bundle does not match the configured preset type.

**Comment by jsliacan** [comment]
There's that warning:
```
$ crc config set preset microshift
Changes to configuration property 'preset' are only applied when the CRC instance is created.
If you already have a running CRC instance with different preset, then for this configuration change to take effect, delete the CRC instance with 'crc delete', setup it with `crc setup` and start it with 'crc start'.

$ crc setup -b ~/Downloads/crc_libvirt_4.12.9_amd64.crcbundle 
WARN Using crc_libvirt_4.12.9_amd64.crcbundle bundle, but crc_microshift_libvirt_4.12.9_amd64.crcbundle is expected for this release
.
.
.
```
I'm not suggesting that it's good as it is :), but for comparison `crc start` is successful even if some operators aren't running yet (exit code 0).

**Comment by redbeam** [comment]
Should the warning also be displayed together with the reason of failure? It would look like this:

```
$ crc setup --bundle crc_microshift_libvirt_4.16.7_amd64.crcbundle 
WARN Using crc_microshift_libvirt_4.16.7_amd64.crcbundle bundle, but crc_libvirt_4.16.7_amd64.crcbundle is expected for this release 
FATA Preset openshift is used but bundle is provided for microshift preset
```

The warning is displayed by this function:
https://github.com/crc-org/crc/blob/e6495fe7492eb0464bfb33c55be104272cd16547/pkg/crc/validation/validation.go#L105-L118

which I assume is meant for cases when the user supplies their custom bundles.

**Comment by praveenkumar** [comment]
Warning for custom bundle is non-fatal and we carry on but I think in case of different preset it should be fatal and we should error out.

**Comment by redbeam** [comment]
Merged
