### ISSUE TITLE
Improve 'status' API

### ISSUE THREAD

**Issue by evidolob** [crc-org/crc#3618]
### General information

In podman-desktop extension we ask crc status every second, the request is pretty heavy, and we don't need all information provided by `api/status` endpoint.

We could add query parameter for `api/status` which indicate that we need less info, like `api/status?light=true`, with that parameter is set `api/status` will return only:

```json
{
 "CrcStatus":   "",
}
```

just the status of crc vm itself.

**Comment by cfergeau** [comment]
Maybe `?fields=CrcStatus` which is going to be more extensible if needed.

**Comment by gbraad** [comment]
`light` suggests there is also a `dark` mode :smile:

the original issue I created for this had a `detailed` option, and in this case perhaps a `stateonly` ? or perhaps, we can do a selection option?

`?select=CrcStatus`

**Comment by praveenkumar** [comment]
@evidolob is working on server side event and with that this might not be required.
