### ISSUE TITLE
No differences between VM creation and VM start in microshift preset

### ISSUE THREAD

**Issue by cfergeau** [crc-org/crc#3619]
Most of the steps in [`startMicroshift`](https://github.com/crc-org/crc/blob/0d0590e18d239340431dc8801e22deab2a883180/pkg/crc/machine/start.go#L957-L984) only need to be done once after creating the microshift VM.
At the moment, they are done every time. In particular, the pull secret will be asked at every start if not cached.

**Comment by praveenkumar** [comment]
Yes we need to have something like `ensure` for those methods which first check if a condition is met then don't run otherwise run. Same what we have for openshift side where we ensure if pull secret is preset or kubeconfig file is present.

**Comment by cfergeau** [comment]
Hit this again today :-/

**Comment by gbraad** [comment]
> Hit this again today :-/

and in #3801, as when interactively it gets cancelled, the VM is already in a started stage, but the cluster is not finalized.

**Comment by praveenkumar** [comment]
https://github.com/crc-org/crc/pull/3805 should fixed it. closing this issue.
