### ISSUE TITLE
Wrong unit while downloading bundle during `crc setup`

### ISSUE THREAD

**Issue by jeffmaury** [crc-org/crc#3627]
While the bundle is downloaded, the unit us MiB p/s. What's the p ? Is this per second ?

![image](https://user-images.githubusercontent.com/695993/235973821-e6afe158-ce59-428f-bb16-2db7583eab33.png)

**Comment by gbraad** [comment]
It is not the unit, but the notation that is incorrect, right? This either needs to be `MiBps` or `MiB/s`.

**Comment by gbraad** [comment]
If this needs to be changed, it needs to be modified in CRC tooling itself
![image](https://user-images.githubusercontent.com/1894/236129548-375aff00-0898-4fdf-a54b-09d04cff3f52.png)

This is standard output as per: https://github.com/cheggaaa/pb/ => https://github.com/cheggaaa/pb/blob/224e0746e1e7b9c5309d6e2637264bfeb746d043/v3/speed.go#L74

```go
// ElementSpeed calculates current speed by EWMA
// Optionally can take one or two string arguments.
// First string will be used as value for format speed, default is "%s p/s".
// Second string will be used when speed not available, default is "? p/s"
// In template use as follows: {{speed .}} or {{speed . "%s per second"}} or {{speed . "%s ps" "..."}
var ElementSpeed ElementFunc = func(state *State, args ...string) string {
	sp := getSpeedObj(state).value(state)
	if sp == 0 {
		return argsHelper(args).getNotEmptyOr(1, "? p/s")
	}
	return fmt.Sprintf(argsHelper(args).getNotEmptyOr(0, "%s p/s"), state.Format(int64(round(sp))))
}
```
