### ISSUE TITLE
[BUG] CRC installer pkg on macOS fails with not enough memory 

### ISSUE THREAD

**Issue by romdalf** [crc-org/crc#3628]
### General information

  * OS: macOS
  * Hypervisor: vfkit
  * Did you run `crc setup` before starting it (Yes/No)? No
  * Running CRC on: Laptop / Baremetal-Server / VM

### Description
Installer fails due to system having less than 9GB of RAM. 
With microshift, the minimum requirement is 4GB.

### Steps to reproduce

  1. Download CRC installer pkg
  2. Run on a M1 with 8GB of RAM
  3. Installer will fail with message not enough RAM
  4. 

### Expected
Change the minimum requirements to install CRC to 4GB of RAM.

### Actual
Fails with message not enough RAM.

**Comment by gbraad** [comment]
@anjannath This needs to be revised:


https://github.com/crc-org/crc/blob/496d03e18f2f12aa2febc41670865fca611203db/packaging/darwin/Distribution.in#L15-L20

> Change the minimum requirements to install CRC to 4GB of RAM.

I proposed https://github.com/crc-org/crc/pull/3629 to remove this check. With the presets we offer, even including Podman, this limit is not reasonable. Even 4GB would be an arbitrary value ... and when checked, means 'nothing'. It should be enforced in `crc start` instead.
