### ISSUE TITLE
[BUG] Switching preset does not check for default values, which can end up being used as a config for other presets

### ISSUE THREAD

**Issue by gbraad** [crc-org/crc#3633]
> Also crc has strange behaviour on CPUS, when I switch preset, it keeps CPU configuration, so only RAM is changed.

`crc.json`
```
{
  "consent-telemetry": "yes",
  "cpus": "2",
  "preset": "microshift"
}
```

```
PS> crc config view
- consent-telemetry                     : yes
- preset                                : microshift
PS> crc config set preset openshift
PS> crc config view
- consent-telemetry                     : yes
- cpus                                  : 2
```

when you switch to the microshift preset, it does not clear same as default values... this means the `cpus` remains in the config file. when switching, the backend should do a lower than check and override

A preset is a combination of `bundle`, `cpus`, `memory`, `disksize`. this means that they should be enforced and checked for defaults. if you have 2 for microshift, for some reason (as it got there), and when you switch preset... we should either do a default check on all values... or just immediately do a check for lower than default and override

Note: even moving back to the default preset, should enforce all values to adhere to the default preset (openshift in this case)

---

example
```json
{
  "consent-telemetry": "yes",
  "cpus": "2",
  "preset": "microshift"
}
```

```powershell
ps> crc config unset preset
```

should result in:
```json
{
  "consent-telemetry": "yes",
}
```

---

Easy to reproduce with:

```
PS> crc config set preset microshift
PS> crc config set cpus 2
PS> crc config set preset openshift
PS> crc config view
```

regardless of what has been set before

While:
```
PS> crc config set preset openshift
PS> crc config set cpus 2
```
does report the correct error.

https://github.com/crc-org/crc-extension/pull/87#issuecomment-1536022679

**Comment by anjannath** [comment]
Fixed via #3636 a follow up for `disk-size` option is created #3638
