### ISSUE TITLE
[RFC] Way to switch the default preset at build time

### ISSUE THREAD

**Issue by anjannath** [crc-org/crc#3637]
This'll allow us to make a release with the default preset set to `okd`

**Comment by praveenkumar** [comment]
This is something for upstream releases?

**Comment by anjannath** [comment]
> This is something for upstream releases?

yeah, releases on choco, brew and on github (someday)

**Comment by anjannath** [comment]
done in https://github.com/crc-org/crc/commit/ab9136012d4ebe8bd2f9c9d55edcde0bab59dd46
