### ISSUE TITLE
[BUG] Add path validation for `proxy-ca-file`

### ISSUE THREAD

**Issue by jsliacan** [crc-org/crc#3641]
It seems that relative path causes problems. Absolute path works OK. The error message isn't great, but maybe just validating input for the path would help. 

Also, can we update the description for the `proxy-ca-file` argument? Currently it says:
```
* proxy-ca-file                              Path to an HTTPS proxy certificate authority (CA)
```
I think the following would more accurately describe the item:

> **Absolute** path to an HTTPS proxy certificate authority's **certificate file**

---

### General information
  * OS: Linux

## CRC version
```bash
# Put `crc version` output here
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```

## CRC config
```bash
- consent-telemetry                     : no
- host-network-access                   : true
- http-proxy                            : http://host.crc.testing:8888
- https-proxy                           : http://host.crc.testing:8888
- network-mode                          : user
- proxy-ca-file                         : test/testdata/pki/rootCA.crt
```

### Steps to reproduce

  1. `$ crc config set proxy-ca-file test/testdata/pki/rootCA.crt`
  2. `$ crc setup`
  3. `$ crc start -p ~/Downloads/crc-pull-secret`

### Expected
Start works OK.

### Actual
```
Is 'crc daemon' running? Cannot reach daemon API: Get "http://unix/api/version": read unix @->/home/jsliacan/.crc/crc-http.sock: read: connection reset by peer
```

**Comment by anjannath** [comment]
@jsliacan I was thinking it didn't have any validation, but the config option does have path validation, so it verifies the file exists.. wondering what else could've caused the daemon to error out and exit..

https://github.com/crc-org/crc/blob/bb69afc5f2e9a88d3e76a453ef39295090b788b9/pkg/crc/config/settings.go#L117

**Comment by cfergeau** [comment]
My guess is that if you use a relative path, and then move to a different directory, and then try to run crc from there, then it will fail
```
./crc config set proxy-ca-file rel/path/to/ca.crt
cd ../..
./out/linux-amd64/crc ...
```
At step 3., the relative path will no longer be valid as the working dir changed.

**Comment by jsliacan** [comment]
I am not sure I understand @cfergeau . I don't think I (knowingly) changed the dir between setting the `proxy-ca-file` var and starting `crc`. It happens when I try it with explicit location of the `crc` binary in a fixed working dir (`~/Github/crc`).

```
jsliacan ~/Github/crc (goproxy)$ ./crc version
CRC version: 2.18.0+73a4b9
OpenShift version: 4.12.13
Podman version: 4.4.1

jsliacan ~/Github/crc (goproxy)$ ./crc config set proxy-ca-file test/testdata/pki/rootCA.crt 
Successfully configured proxy-ca-file to test/testdata/pki/rootCA.crt

jsliacan ~/Github/crc (goproxy)$ ./crc setup
.
.
.
Your system is correctly setup for using CRC. Use 'crc start' to start the instance

jsliacan ~/Github/crc (goproxy)$ ./crc start -p ~/Downloads/crc-pull-secret 
Is 'crc daemon' running? Cannot reach daemon API: Get "http://unix/api/version": read unix @->/home/jsliacan/.crc/crc-http.sock: read: connection reset by peer
```

**Comment by cfergeau** [comment]
```
jsliacan ~/Github/crc (goproxy)$ ./crc start -p ~/Downloads/crc-pull-secret 
Is 'crc daemon' running? Cannot reach daemon API: Get "http://unix/api/version": read unix @->/home/jsliacan/.crc/crc-http.sock: read: connection reset by peer
```
The daemon won't be started as `./crc` from the `~/Github/crc` workdir, but through an absolute path (I think `~/.crc/bin/crc`) so it has no way of resolving `test/testdata/pki/rootCA.crt` as `~/Github/crc/test/testdata/pki/rootCA.crt`

**Comment by cfergeau** [comment]
This is being worked on in https://github.com/crc-org/crc/pull/3816
