### ISSUE TITLE
[Feature] Debug option to add a password for the core user on startup

### ISSUE THREAD

**Issue by gbraad** [crc-org/crc#3677]
This allows you to debug the environment in case of an OOM or other crash.
At the moment we only allow the use of the ssh-key to log in, but when the image is memory constrained or otherwise affect by a crash, the `sshd` process becomes unreachable. This prevents further debugging. I suggest adding a

```
$ crc config set emergency-login true    # or debug-login
```

which generates a random password on startup and allows you to login in case of an issue.

**Comment by anjannath** [comment]
Done in https://github.com/crc-org/crc/pull/3755
