### ISSUE TITLE
`crc config get` returns an error code when the setting has a default value

### ISSUE THREAD

**Issue by gbraad** [crc-org/crc#3678]
![image](https://github.com/crc-org/crc/assets/1894/bb262219-be20-4ac9-b8fd-fa8f74af3d70)

**Comment by cfergeau** [comment]
2.18.0 and 2.10.0 both have the same behaviour, so if this is a regression it's not a recent one.

**Comment by cfergeau** [comment]
https://github.com/crc-org/crc/blob/2468363c4b363da2f37a7bce1e1b4b4207b644d0/cmd/crc/cmd/config/get.go#L30-L32

**Comment by gbraad** [comment]
This seems to be an inconsistency. Defaults are not an error IMNSHO ;-)

**Comment by jsliacan** [comment]
> 2.18.0 and 2.10.0 both have the same behaviour, so if this is a regression it's not a recent one.

@cfergeau I think back then it was less obvious. It wouldn't have happened if you did [this](https://github.com/crc-org/crc/issues/3663#issuecomment-1557157577) I think. 
```
$ crc config set preset openshift
$ echo $?
0
$ crc config get preset
Configuration property 'preset' is not set. Default value is 'openshift'
$ echo $?
1
```

**Comment by gbraad** [comment]
It is maybe not a regression, but an inconsistency; it makes no sense to error out when it is the default
