### ISSUE TITLE
CRC Setup is failing with "unable to get verified hash for default bundle"

### ISSUE THREAD

**Issue by RamySabry** [crc-org/crc#3686]
Trying to setup a fresh CRC "crc setup" with the below environment but its failing with the mentioned error below

**Error** 
    "unable to get verified hash for default bundle: Get "https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/crc/bundles/openshift/4.12.13/sha256sum.txt.sig": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

**CR Version** : crc-linux-2.19.0-amd64
**Operating System** : CentOS-Stream-9-x86_64
**Over VMware** 16.1.0 build-17198959

Logs are attached "Setup Debug Logs.txt"

([Setup Debug Logs.txt](https://github.com/crc-org/crc/files/11597823/Setup.Debug.Logs.txt))

**Comment by jsliacan** [comment]
We've just seen this issue on M1 with pre-release bits (2.20.0) with `microshfit` preset. But on 2nd try it went away and we couldn't replicate. cc: @adrianriobo

**Comment by cfergeau** [comment]
Maybe this timeout which is too short? https://github.com/crc-org/crc/blob/f3a947bdffe0550c95a34b88c512c45e874193cd/pkg/crc/machine/bundle/metadata.go#L302-L305

**Comment by anjannath** [comment]
> Maybe this timeout which is too short?
> 
> https://github.com/crc-org/crc/blob/f3a947bdffe0550c95a34b88c512c45e874193cd/pkg/crc/machine/bundle/metadata.go#L302-L305

we have to increase this timeout duration, i reused the timeout from the call to check for new version, ~but the bundle signature file is bigger in size then the version-info.json~ (they are of same size)

it could also be related to delayed respose from dns, @RamySabry could you share what dns setup you are using

**Comment by anjannath** [comment]
as @jsliacan mentioned, work-arond is to run `crc setup` again.

**Comment by cfergeau** [comment]
> i reused the timeout from the call to check for new version

Might be useful to introduce a helper to get an io.Reader from an http URL instead of duplicating this code twice. Seems easy to do using the current code, but the go package we use in our `download` package also provides https://github.com/cavaliergopher/grab/blob/e06b719a377d74a18bdff0d0ffb9abf4a4afdbac/v3/response.go#L191-L204

**Comment by anjannath** [comment]
yeah, good idea, we can create a wrapper function to create a `grab.Request` that'd download in memory and then use the `resp.Open` for getting the content

**Comment by Matrejeur** [comment]
I downloaded the bundle as stated on the error link i.e https://mirror.openshift.com/pub/openshift-v4/clients/crc/bundles/openshift/ on my browser.
Copied it to my the cache directory inside the .crc directory i.e /home/nago/.crc/cache.
Ran the command: crc setup -b {The downloaded bundle} i.e 
crc setup -b crc_libvirt_4.13.0_amd64.crcbundle
