### ISSUE TITLE
[BUG] Invalid `proxy-ca-file` path prevents crc from starting

### ISSUE THREAD

**Issue by cfergeau** [crc-org/crc#3690]
### General information

  * OS: Linux
  * Hypervisor: KVM

## CRC version
```bash
# Put `crc version` output here
$ ./out/linux-amd64/crc version
FATA[0000] not able to read proxy CA data from /home/teuf/crc/crc/images/squid/pki/rootCA.crt: open /home/teuf/crc/crc/images/squid/pki/rootCA.crt: no such file or directory 
```
(yes it is that bad)
  
## CRC config
```bash
# Put `crc config view` output here
$ ./out/linux-amd64/crc view
FATA[0000] not able to read proxy CA data from /home/teuf/crc/crc/images/squid/pki/rootCA.crt: open /home/teuf/crc/crc/images/squid/pki/rootCA.crt: no such file or directory 
```

### Steps to reproduce

  1. set `proxy-ca-file` to a valid path
  2. remove the file

### Expected

`crc` errors out when it tries to configure a VM with a proxy

### Actual

All `crc` invocations (`config`, `version`, ...) print a proxy-ca-file related error message and exit.
The config file must be edited by hand to get out of this.

This could be worked on at the same time as https://github.com/crc-org/crc/issues/3641

**Comment by jsliacan** [comment]
@cfergeau This reminds me of https://github.com/crc-org/crc/issues/3098 in the sense that it was an invalid proxy-related setting and all `crc` commands were unusable.
