### ISSUE TITLE
[refactor] Fix import cycle caused by importing the pkg/crc/network package

### ISSUE THREAD

**Issue by anjannath** [crc-org/crc#3697]
For making any http network calls from CRC we use the transport from  `network.HTTPTransport()`, but this causes import cycles, most recently seen in #3693 and https://github.com/crc-org/crc/pull/3693#issuecomment-1573317258 mentions other instances we have seen this before.

It'd be good to fix the import cycles once and for all by doing some refactor

**Comment by cfergeau** [comment]
https://github.com/cfergeau/crc/tree/refactor this could look like this

**Comment by anjannath** [comment]
I rebased my PR #3693 on top of https://github.com/cfergeau/crc/tree/refactor here: https://github.com/anjannath/crc/tree/bundle-hash-refactored

(renamed the package to `httpproxy` instead of transport | proxy)

**Comment by anjannath** [comment]
done in #3693
