### ISSUE TITLE
MAC OS: failed to expose port 127.0.0.1:6443 -> 192.168.127.2:6443: listen tcp 127.0.0.1:6443: bind: address already in use

### ISSUE THREAD

**Issue by kc0olm** [crc-org/crc#3698]
I installed OpenShift local last week, ran through the setup and started crc successfully.

Came back this week, and everything works except crc start:

failed to expose port 127.0.0.1:6443 -> 192.168.127.2:6443: listen tcp 127.0.0.1:6443: bind: address already in use

I don't have anything on 192.168.127.2. My current address is 192.168.127.1. So I don't know where this is coming from.

I already tried

1. crc stop
2. crc delete
3. crc cleanup
4. crc setup
5. crc start

No success

**Comment by praveenkumar** [comment]
`127.0.0.1:6443 -> 192.168.127.2:6443` it means it is try to map `6443` port from host to VM and if the port is already in use then it will fail. Can you make sure you don't have `6443` port used by any other service on your mac. 

```
sudo lsof -i :6443
```

**Comment by kc0olm** [comment]
@praveenkumar Thanks so much for responding!

So, I did try checking for other services using that port, and it brought back nothing.  This is why I opened a ticket.  The error is pretty clear, which makes it confusing when there aren't other listeners on that port.  Even after I deleted the instance a couple of times, I still got the error.

My mistake could have been using the netstat command, but I don't know why.  I've always used netstat.

Anyway I just rebooted my laptop.  I have Docker Desktop installed and it is set to automatically run - I also have the kubernetes module installed there.  I shut this down as well, although I don't have any evidence that this was the cause.

In any case, I'm up and running again!  Thank you!

```
crc     1229 kameroncole   15u  IPv4 0x13e7794b47673dff      0t0  TCP localhost:sun-sr-https (LISTEN)
```

**Comment by praveenkumar** [comment]
> I have Docker Desktop installed and it is set to automatically run - I also have the kubernetes module installed there.

@kc0olm looks like `k8s` on docker desktop might be the culprit because it also use `6443` port on host (iirc). Glad that you are able to make it work. I am closing the issue for now.
