### ISSUE TITLE
[BUG] Host foo.apps-crc.testing is not added to /etc/hosts, causing install to fail

### ISSUE THREAD

**Issue by NickMRamirez** [crc-org/crc#3699]
### General information

  * OS: **Linux**
  * Hypervisor: **KVM  (libvert)**
  * Did you run `crc setup` before starting it? **Yes**
  * Running CRC on: **Laptop**

## CRC version
```bash
$ crc version
CRC version: 2.20.0+f3a947
OpenShift version: 4.13.0
Podman version: 4.4.4
```
  
## CRC status
```bash
$ crc status --log-level debug 
DEBU CRC version: 2.20.0+f3a947                   
DEBU OpenShift version: 4.13.0                    
DEBU Podman version: 4.4.4                        
DEBU Running 'crc status'                         
CRC VM:          Running
OpenShift:       Unreachable (v4.13.0)
RAM Usage:       722.8MB of 9.369GB
Disk Usage:      15GB of 32.68GB (Inside the CRC VM)
Cache Usage:     19.43GB
Cache Directory: /home/nick/.crc/cache
```

## CRC config
```bash
$ crc config view
- consent-telemetry                     : no
- nameserver                            : 8.8.8.8
```

## Host Operating System

Linux Mint / Ubuntu Jammy

```bash
   $ cat /etc/os-release 
   NAME="Linux Mint"
   VERSION="21.1 (Vera)"
   ID=linuxmint
   ID_LIKE="ubuntu debian"
   PRETTY_NAME="Linux Mint 21.1"
   VERSION_ID="21.1"
   HOME_URL="https://www.linuxmint.com/"
   SUPPORT_URL="https://forums.linuxmint.com/"
   BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
   PRIVACY_POLICY_URL="https://www.linuxmint.com/"
   VERSION_CODENAME=vera
   UBUNTU_CODENAME=jammy
```

### Steps to reproduce

  1. [Download OpenShift Local and the Pull Secret](https://console.redhat.com/openshift/create/local) from RedHat.
  2. Follow the [setup guide](https://access.redhat.com/documentation/en-us/red_hat_openshift_local/2.20/html/getting_started_guide/installation_gsg).
  3. When calling `crc setup && crc start`, there is the following error:

   ```
   WARN foo.apps-crc.testing resolved to [92.242.140.21] but 172.31.56.119 was expected
   ERRO Failed to query DNS from host: Invalid IP for foo.apps-crc.testing
   ```

### Expected

The startup should resolve the hostname `foo.apps-crc.testing` in order to install successfully. I noticed that during the installation process, OpenShift Local adds an entry to `/etc/hosts`, but this host is not included in that entry. Manually adding it to the entry and saving `/etc/hosts` solves the problem.

### Actual

During startup, the DNS host `foo.apps-crc.testing` is not resolved.

### Logs

https://gist.github.com/NickMRamirez/2c52039624ab35c5ce9c2fec0974272b

### Workaround

As a workaround, edit `/etc/hosts` and add `foo.apps-crc.testing` to the entry that OpenShift Local added automatically.

1. Edit `/etc/hosts`.
2. Change the line that looks like this:

   ```
   192.168.130.11 api.crc.testing canary-openshift-ingress-canary.apps-crc.testing 
     console-openshift-console.apps-crc.testing default-route-openshift-image-registry.apps-crc.testing 
     downloads-openshift-console.apps-crc.testing oauth-openshift.apps-crc.testing
   ```
   So that it includes  `foo.apps-crc.testing`:

   ```
   192.168.130.11 foo.apps-crc.testing api.crc.testing canary-openshift-ingress-canary.apps-crc.testing 
     console-openshift-console.apps-crc.testing default-route-openshift-image-registry.apps-crc.testing 
     downloads-openshift-console.apps-crc.testing oauth-openshift.apps-crc.testing
   ```

4. Save the file.
5. Stop and start `crc`:

   ```
   $ crc stop
   $ crc start
   ```

   The installation completes successfully.

**Comment by praveenkumar** [comment]
```
INFO Check DNS query from host...                 
DEBU api.crc.testing resolved to [192.168.130.11] 
DEBU foo.apps-crc.testing resolved to [143.244.220.150] 
WARN foo.apps-crc.testing resolved to [143.244.220.150] but 192.168.130.11 was expected 
```

As per following logs, looks like `foo.apps-crc.testing` not resolved with the dnsmasq or systemd setting which we provide, can you try to use `dig foo.apps-crc.testing` and `dig  bar.apps-crc.testing` and comment what is showing?

**Comment by NickMRamirez** [comment]
Yes, here is the output. Seems to be a DigitalOcean address, based on `whois`.

```
$ dig foo.apps-crc.testing

; <<>> DiG 9.18.12-0ubuntu0.22.04.1-Ubuntu <<>> foo.apps-crc.testing
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57619
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;foo.apps-crc.testing.		IN	A

;; ANSWER SECTION:
foo.apps-crc.testing.	60	IN	A	143.244.220.150

;; Query time: 48 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Tue Jun 06 18:21:36 EDT 2023
;; MSG SIZE  rcvd: 65
```

```
$ dig bar.apps-crc.testing 

; <<>> DiG 9.18.12-0ubuntu0.22.04.1-Ubuntu <<>> bar.apps-crc.testing
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45373
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;bar.apps-crc.testing.		IN	A

;; ANSWER SECTION:
bar.apps-crc.testing.	60	IN	A	143.244.220.150

;; Query time: 48 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Tue Jun 06 18:22:38 EDT 2023
;; MSG SIZE  rcvd: 65
```

**Comment by cfergeau** [comment]
Is this the case with other 404 addresses? `foo.example.com`

**Comment by NickMRamirez** [comment]
Indeed. For me, any fake / not existing domain name resolves to this same IP address. Some people on forums say it is ATT's fallback website when there is no DNS record found.

**Comment by praveenkumar** [comment]
@NickMRamirez can you try to use following with latest version of CRC and see if still have same issue.
```
$ crc delete
$ crc cleanup
$ crc config set network-mode user
$ crc setup
$ crc start
```

**Comment by NickMRamirez** [comment]
@praveenkumar I tried with this version:

```bash
$ crc version
     
CRC version: 2.28.0+e1f42d
OpenShift version: 4.13.14
Podman version: 4.4.4
```

After following the steps, the install succeeds and the issue seems to be resolved.

Thanks!

**Comment by praveenkumar** [comment]
@NickMRamirez Thank you, closing this issue now.
