### ISSUE TITLE
[BUG] Somethings launches a powershell terminal on Windows that stays around

### ISSUE THREAD

**Issue by anjannath** [crc-org/crc#3726]

**Comment by adrianriobo** [comment]
We are hitting this issue when we run `Podman Desktop` on the windows machine, after starting PD and close it if we run `crc setup` the crc process for the daemon is created on a visible window which leads to not being killed within `crc cleanup` 

When running PD the only process which may modify something during the installation process could be podman itself.. (On my tests that is the only thing installed through PD)

**Comment by anjannath** [comment]
After more reports from @gbraad and @themr0c this seems to happen when user chooses the "Windows  Terminal" as the default terminal app

need  to find a way to hide the terminal window, when "Windows Terminal" is used to launch powershell

**Comment by gbraad** [comment]
Note: this now also happens on win10

**Comment by anjannath** [comment]
Might find a solution from this stackoverflow post, https://stackoverflow.com/questions/74968665/hide-the-windows-terminal-console-window-with-powershell
