### ISSUE TITLE
Unable to install Openshift Local on MacBook Pro

### ISSUE THREAD

**Issue by nicolagiangiulio** [crc-org/crc#3731]
I tried to install OpenShift Local v2.20 on a MacBook Pro 2,3 GHz Quad-Core Intel Core i7
The installation GUI seems to hang and is doing no CPU/IO activity
I managed to install successfully via console with the "crc setup" command, and Openshift Local is now working fine
But I can't manage OpenShift via the tray icon...is there any way to fix this issue ? Thanks

**Comment by anjannath** [comment]
@nicolagiangiulio Tray icon from CRC is now deprecated, and is not maintained anymore, the suggested way to use a GUI is to use [podman desktop](https://podman-desktop.io/docs/Installation/macos-install) with the [CRC extension](github.com/crc-org/crc-extension/)
