### ISSUE TITLE
[Telemetry] Send preset value even there is early error during crc start

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/crc#3735]
Looking at amplitude matrix around preset, there is lot of number around `none` preset. Then I looked at the segment which have raw data around our telemetry and found out in case there is early error we are not sending the preset value to segment and hence this `none` happen.
```
client.Track(&analytics.Track{
  UserId: "xxxxxxxxxxxxxxxxxxxx",
  Event: "crc start",
  Properties: map[string]interface{}{
    "duration": 3558,
    "error": "Hyper-V Virtual Machine Management service not running",
    "error-type": "os.CodeExitError",
    "remote": false,
    "source": "cli",
    "success": false,
    "tty": true,
    "version": "2.20.0",
  },
})
```

or
 
```
client.Track(&analytics.Track{
  UserId: "xxxxxxxxxxxxxxxxx",
  Event: "crc start",
  Properties: map[string]interface{}{
    "duration": 2926,
    "error": "crc should be ran in a shell without administrator rights",
    "error-type": "os.CodeExitError",
    "remote": false,
    "source": "cli",
    "success": false,
    "tty": true,
    "version": "2.20.0",
  },
```

**Comment by gbraad** [comment]
> we are not sending the preset value to segment and hence this none happen.

Why is that actually not happening? As it seems, there is an 'error'. Any idea what the error is that prevents the preset to be sent? Or is this very generic?

It can't be just these:

> "Hyper-V Virtual Machine Management service not running"

> "crc should be ran in a shell without administrator rights",

as these are mostly part of the onboarding phase. At that moment the preset might not have been established. but I also know the number of these cases were not very minimal. I doubt these happen at the same rate as the 'none' being reported.

**Comment by praveenkumar** [comment]
We are now sending preset details for each event/interaction. hopefully with next release we will see less `none` around it.
