### ISSUE TITLE
Helm charts won't install in new install of crc

### ISSUE THREAD

**Issue by omkarkulkarni02** [crc-org/crc#3746]
### General information

  * OS:  macOS
  * Hypervisor: KVM / Hyper-V / hyperkit / vfkit
  * Did you run `crc setup` before starting it : Yes
  * Running CRC on: Laptop / Baremetal-Server / VM

## CRC version
```bash
2.22.1+e8068b4
```

### Steps to reproduce

  1. Installed crc version: 2.22.1
  2.  Did crc setup and crc start
  3. Logged in as kubeadmin
  4.  Trying to set up external-secrets using helm 
  5. adding chart repository using following command: `helm repo add external-secrets https://charts.external-secrets.io`
  6. installing helm charts for external-secrets: `helm install external-secrets external-secrets/external-secrets -n external-secrets --create-namespace --set installCRDs=true`
  7. external-secrets gets deployed successfully
  
![Screenshot 2023-06-30 at 09 23 29](https://github.com/crc-org/crc/assets/138199522/e71d58e5-af5c-4f1a-8af9-f730fd762627)
  
  8. checking pods for external-secrets `kubectl get pods -n external-secrets`
 
### Expected
It should list the 3 pods in running condition/status

### Actual
Received error: `No resources found in external-secrets namespace.`

Checked in Openshift console and found following error: 
<img width="333" alt="Screenshot 2023-06-30 at 09 25 34" src="https://github.com/crc-org/crc/assets/138199522/5e607a1f-6990-4522-8800-c27e8cb34d4c">

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by anjannath** [comment]
@omkarkulkarni02 from the error msg it looks like, the charts are not setting the expected `securityContexts`, Have you tried installing it via the operator, https://operatorhub.io/operator/external-secrets-operator ?

You can install operators using the web console UI by following the steps from: https://docs.openshift.com/container-platform/4.13/operators/admin/olm-adding-operators-to-cluster.html#olm-installing-from-operatorhub-using-web-console_olm-adding-operators-to-a-cluster

**Comment by cfergeau** [comment]
See also https://github.com/external-secrets/external-secrets/issues/2342

**Comment by praveenkumar** [comment]
Closing this, since it is not the  crc specific issue but more around specific helm chart on openshift.
