### ISSUE TITLE
[BUG] microshift preset only allows 15 Gi of PVCs

### ISSUE THREAD

**Issue by computate** [crc-org/crc#3747]
### General information

  * OS: RHEL 9.2
  * Hypervisor: OpenShift Local with `microshift` preset, Libvirt
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
$ crc version
CRC version: 2.22.1+e8068b4
OpenShift version: 4.13.3
Podman version: 4.4.4
```
  
## CRC status
```bash
$ crc status
CRC VM:          Running
MicroShift:      Running (v4.13.3)
RAM Usage:       8.47GB of 29.49GB
Disk Usage:      15GB of 198.6GB (Inside the CRC VM)
Cache Usage:     142.6GB
Cache Directory: /home/ctate/.crc/cache
```

## CRC config
```bash
$ crc config view
- consent-telemetry                     : yes
- cpus                                  : 7
- disk-size                             : 201
- memory                                : 29000
- preset                                : microshift
```

## Host Operating System
```bash
$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="9.2 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.2 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
```

### Steps to reproduce

```bash
crc config set preset microshift
crc config set cpus 7
crc config set memory 29000
crc config set disk-size 200
crc setup
crc start
crc stop
crc config set disk-size 201
crc start
```

### Expected

I expect more than 15Gi of PVCs to be status `Bound`. 

```bash
$ oc get pvc -A
smartvillage   data-default-solrcloud-0             Bound     pvc-e7fc13c6-5dad-4df2-92e9-7d46ce5605ba   25Gi        RWO            topolvm-provisioner   3h23m
```

### Actual

Additional PVCs above 15Gi remain in status `Pending`: 

```bash
$ oc get pvc -A
NAMESPACE      NAME                                 STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
smartvillage   data-default-solrcloud-0             Bound     pvc-e7fc13c6-5dad-4df2-92e9-7d46ce5605ba   5Gi        RWO            topolvm-provisioner   3h23m
smartvillage   data-default-solrcloud-1             Bound     pvc-90105135-a2db-4357-91f5-ef07b7221e4b   5Gi        RWO            topolvm-provisioner   3h23m
smartvillage   data-default-solrcloud-zookeeper-0   Pending                                                                        topolvm-provisioner   3h19m
smartvillage   postgres-repo1                       Bound     pvc-273080b0-a105-475c-9c41-6a9e56c74bb7   1Gi        RWO            topolvm-provisioner   4h45m
smartvillage   postgres-smartvillage-2htg-pgdata    Bound     pvc-95a4dd5d-42b2-43e2-bcd1-6065146c37ae   1Gi        RWO            topolvm-provisioner   4h45m
smartvillage   postgres-smartvillage-ktkj-pgdata    Bound     pvc-d2dfb6d8-ee74-47e2-865b-5d0a865c73da   1Gi        RWO            topolvm-provisioner   4h45m
smartvillage   zookeeper                            Bound     pvc-7d286403-8c88-4f31-92a3-f19ce97fd913   1Gi        RWO            topolvm-provisioner   4h45m
```

### Logs

And the node reports it did not have enough free storage:

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

Here is my gist: https://gist.github.com/computate/081aec10169bd7891bdffda05b67b0d9

Thanks for your help!

**Comment by praveenkumar** [comment]
https://github.com/crc-org/crc/issues/3624#issuecomment-1560892999 , looks like we need to re-evaluate our disk-resize logic.

**Comment by gbraad** [comment]
We have spoken about this in the team and did not come to a clear conclusion on how to handle this.

There seems to be two kinds of storage locations for Microshift; persistent and ephemeral. the filesystem that we currently enlarge is actually part of ephemeral, but this is where the OS and comtainer images live. The size that might have to be enlarged too, is the persistent storage, which is used for the PVs. though, what would be the best way to deal with this?

Do we need to offer parameters to start to allow resizing of these individual locations? or have we made the wrong choice to enlarge the container storage path?

**Comment by praveenkumar** [comment]
@computate what kind of behavior you expect as user?

**Comment by computate** [comment]
@praveenkumar I see how it might be possible to run out of container image space, but it's even easier to run out of Persistent Volume storage when there are only 10Gi available with the microshift preset. I would love to have parameters to configure both volume and image storage if possible, but for now I have to limit my projects to 10 Gi for volumes.

**Comment by praveenkumar** [comment]
@computate it is already fixed in 2.28 version of crc and now have option to specify `persistent-volume-size` which you can use to define how much space you require for PV. Please give it a try and let us know it works as expected.

**Comment by computate** [comment]
Thank you @praveenkumar , this works to add larger PVC storage than 15Gi, assuming you configure the `persistent-volume-size` before you `crc start` for the first time. Otherwise, it doesn't seem to resize the PVC storage after you've already started your cluster for the first time.

**Comment by praveenkumar** [comment]
> assuming you configure the `persistent-volume-size` before you `crc start` for the first time.

@computate yes that is expected because we can't free up disk size after allocate as part of initial crc start. I am closing this issue now.
