### ISSUE TITLE
[BUG] Enabling lingering for `core` (and `root`) user otherwise containers are killed after a timeout

### ISSUE THREAD

**Issue by gbraad** [crc-org/crc#3759]
## General information

When using CRC with Microshift and Podman from this bundle, I run into issues. On `bare-metal` (Linux) and did I run? `crc setup`. How else would it get the image to start... 

### Version

```
$ ./crc version                                          
CRC version: 2.23.0+ddcfe8
OpenShift version: 4.13.3
Podman version: 4.4.4
```
### Config

```
$ ./crc config view
- consent-telemetry                     : no
- memory                                : 6000
- preset                                : microshift
```

For the `podman-env` setting we use an SSH connection to start the container. It seems that containers get killed after a timeout.

After:

```
$ loginctl enable-linger core
```

this does not happen anymore. For podman, like on WSL, we use a socket and this shows very different behaviour.

### Steps
```
$ crc config set preset microshift
$ crc start 
$ eval $(./crc podman-env)
$ podman ps               
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
$ podman run -d --name=tailscaled \      
        --hostname microshift \
        --network=host --systemd=always \
        --cap-add=NET_ADMIN --cap-add=NET_RAW \
        ghcr.io/spotsnel/tailscale-systemd/fedora:latest
$ podman exec -it tailscaled tailscale up
```

### Actual
After a few minutes, the container gets stopped.

```
$ podman ps -a
CONTAINER ID  IMAGE                                             COMMAND     CREATED      STATUS        PORTS       NAMES
fb0bb4b683d7  ghcr.io/spotsnel/tailscale-systemd/fedora:latest              2 hours ago  Up 5 minutes              tailscale
$ podman ps -a
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.5.1/libpod/_ping": ssh: rejected: connect failed (open failed)
$ podman ps -a
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.5.1/libpod/_ping": ssh: rejected: connect failed (open failed)
$ ssh -i ~/.crc/machines/crc/id_ecdsa core@192.168.130.11
Script '01_update_platforms_check.sh' FAILURE (exit code '1'). Continuing...
Boot Status is GREEN - Health Check SUCCESS
Last login: Tue Jul 18 07:40:25 2023 from 192.168.130.1
[core@api ~]$ podman ps
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
[core@api ~]$ podman ps -a
CONTAINER ID  IMAGE                                             COMMAND     CREATED      STATUS      PORTS       NAMES
fb0bb4b683d7  ghcr.io/spotsnel/tailscale-systemd/fedora:latest              2 hours ago  Stopping                tailscale
[core@api ~]$ 
```

So, are the containers killed because of `linger`? `podman-env` uses an ssh connection to start/stop the containers, which most likely acts different when a process/container is started over the socket.

```
$ ssh -i ~/.crc/machines/crc/id_ecdsa core@192.168.130.11 -C loginctl list-users
 UID USER LINGER
1000 core no
```

For as long as the container is `Stopping` it is not possible to do anything externally.

### Expected

When changed:
```
ssh -i ~/.crc/machines/crc/id_ecdsa core@192.168.130.11 -C loginctl list-users
 UID USER LINGER
1000 core yes
```

the containers keep running when started with the system connection.

Ref: https://github.com/crc-org/crc/issues/3757#issuecomment-1639895533

**Comment by cfergeau** [comment]
Please follow the bug reporting template, otherwise it's hard to know what you've done
What preset? What steps did you follow? Unclear if it's with rootless or rootful containers? ...

**Comment by gbraad** [comment]
See reference issue for setup, but this is using the Microshift preset, latest version. Podman 4.4.4 (bundle 4.13.x)

**Comment by praveenkumar** [comment]
I checked on podman machine and there `core` user is has lingering enabled. I will check and enable it part of snc side.

```
$ podman machine ssh -- loginctl list-users
 UID USER LINGER
1000 core yes
```

**Comment by cfergeau** [comment]
podman 1.6.3 release notes has:
> Rootless Podman no longer enables linger on systems with systemd as init by default. As such, containers will now be killed when the user who ran them logs out, unless linger is explicitly enabled using [loginctl](https://www.freedesktop.org/software/systemd/man/loginctl.html)

and they indeed have some code in podman-machine to enable it.

**Comment by praveenkumar** [comment]
https://github.com/crc-org/snc/pull/781

**Comment by praveenkumar** [comment]
> and they indeed have some code in podman-machine to enable it.

Enabled by touching the file to `/var/lib/systemd/linger/` location. 

https://github.com/containers/podman/blob/7791ffd2150f75f5c6d3abac438b21afeeca1bd3/pkg/machine/ignition.go#L392-L399
