### ISSUE TITLE
[BUG] When daemon returns a non-200 code, add the message to the log

### ISSUE THREAD

**Issue by gbraad** [crc-org/crc#3766]
When the daemon returns a response, it only logs the actuall call and the code.
But in case of a 500, it might be helpful to actually include the message:

```
\\.\pipe\crc-http - - [24/Jul/2023:13:47:29 -0400] "GET /api/status HTTP/1.1" 500 52
```

In that case, the user might not have to share bots logs.

**Comment by anjannath** [comment]
We are using the `LoggingHandler` from gorrila for this: https://pkg.go.dev/github.com/gorilla/handlers#LoggingHandler, which o/p logs in apache CLF format, we'll have to switch to a custom logger (https://pkg.go.dev/github.com/gorilla/handlers#CustomLoggingHandler) if we want to have a conditional logging based on the status codes.

**Comment by rohanKanojia** [comment]
I'm interested in working on this issue. Could someone assign this to me?

**Comment by rohanKanojia** [comment]
@anjannath : Could you please close this issue?

**Comment by anjannath** [comment]
done via #4467
