### ISSUE TITLE
[CI] Create e2e job on openshift-ci for microshift bundle testing

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/crc#3773]
This job will make sure that microshift bundle is working as expected and we can also add some basic e2e feature which we use for openshift bundles.

**Comment by gbraad** [comment]
I would say; start with basics and build from there.

a "start, run container, stop" would have caught our current issue.

**Comment by jsliacan** [comment]
So maybe we can reuse what we have already. [This feature](https://github.com/crc-org/crc/blob/6b61c2ff0e23d92ec886bbc88205378b28cc80f3/test/e2e/features/minimal.feature) was created for similar quick checks of basic functionality. We are going to need a small modification to run *only* `microshift` case, maybe splitting the examples as below will work. Then filtering with `@minimal && @microshift-preset` should do the job.

```feature
@minimal @darwin @linux @windows
Feature: Minimal user story

    User starts CRC cluster and checks status.

    @cleanup
    Scenario Outline: Start OpenShift cluster:
        Given setting config property "preset" to value "<preset-value>" succeeds
        And executing single crc setup command succeeds
        And starting CRC with default bundle succeeds
        Then checking that CRC is running

        @podman-preset
        Examples:
            | preset-value |
            | podman       |

        @microshift-preset
        Examples:
            | preset-value |
            | microshift   |

        @openshift-preset
        Examples:
            | preset-value |
            | openshift    |
```

**Comment by jsliacan** [comment]
I checked, and it would work with those modifications and that filter.

```$ make e2e
Log successfully started, logging into: /home/jsliacan/Github/crc/test/e2e/out/test-results/e2e_2023-7-28_10-30-41.log
Running e2e test in: /home/jsliacan/Github/crc/test/e2e/out/test-run
Working directory set to: /home/jsliacan/Github/crc/test/e2e/out/test-run
Using existing bundle: /home/jsliacan/Downloads/crc_microshift_libvirt_4.13.6_amd64.crcbundle
Feature: Minimal user story
  User starts CRC cluster and checks status.

    Examples:
      | preset-value |
      | microshift   |
Deleted CRC instance (if one existed).

1 scenarios (1 passed)
4 steps (4 passed)
4m9.323780413s
ok  	github.com/crc-org/crc/test/e2e	249.349s
```

**Comment by gbraad** [comment]
That would be just a start scenario, right?

**Comment by praveenkumar** [comment]
Job creation PR on openshift CI: https://github.com/openshift/release/pull/41777

**Comment by praveenkumar** [comment]
Since we already have now job to start microshift bundle and also deploy a basic application.
