### ISSUE TITLE
[Question] is CRC available on linux arm64 based CPUs ?

### ISSUE THREAD

**Issue by ayoub-tl** [crc-org/crc#3774]
is CRC available on linux arm64 based CPUs ? and is this feauters planned ?
thank you

**Comment by praveenkumar** [comment]
> is CRC available on linux arm64 based CPUs ? and is this feauters planned ?

What is the usecase? As of now CRC is for running openshift cluster locally on developer's laptop/desktop and arm64 on linux is not as common for laptop/desktop. We deliver bundles for mac-M1 which is arm64 based.

**Comment by gbraad** [comment]
Not planned. If you want to run on an Ampere Altra, please consider using the openshift-installer for now. Images are possible to run on this target, though the main executable has not been built with this in mind at the moment.

> arm64 on linux is not as common for laptop/desktop.

There are some boards, like the Solidrun Honeycomb. Though availability is still an issue. Be aware, a RasPi just won't do it for OCP/OKD... only Microshift...
