### ISSUE TITLE
CRC giving error while running 'crc start'

### ISSUE THREAD

**Issue by shawgrey** [crc-org/crc#3791]
The BaseOS is Linux

> "NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"`

**Base Machine Specs**
>RAM: 12 GB
CPU: 4
Disk: 120 GB

**CRC Status**

> CRC VM:          Running
OpenShift:       Starting (v4.13.6)
RAM Usage:       6.173GB of 10.43GB
Disk Usage:      17.29GB of 32.68GB (Inside the CRC VM)
Cache Usage:     20.84GB
Cache Directory: /home/crcadmin/.crc/cache

Expected: Openshift should be in 'Running'

**CRC Version**

> CRC version: 2.24.1+81aeeb
OpenShift version: 4.13.6
Podman version: 4.4.4

**ERROR**
While running crc start after crc setup "Cluster is not ready error" 
> INFO 3 operators are progressing: image-registry, kube-storage-version-migrator, openshift-controller-manager 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
INFO 2 operators are progressing: image-registry, openshift-controller-manager 
**ERRO Cluster is not ready: cluster operators are still not stable after 10m22.207665834s** 
INFO Adding crc-admin and crc-developer contexts to kubeconfig...

**Reproduce error**
> crc stop
crc delete
crc cleanup
crc setup
crc start --log-level debug 

Still getting same "Cluster is not ready error"

**CMD output can be found here**
https://gist.github.com/shawgrey/d9669d29f0cac4fd210b1c5adebcddda

**Comment by shawgrey** [comment]
when running
> oc login -u developer https://api.crc.testing:6443

I am getting:
**The connection to the server oauth-openshift.apps-crc.testing was refused - did you specify the right host or port?**

**Comment by cfergeau** [comment]
If you wait a little longer, does the cluster finally stabilize? You can check with `eval $(crc oc-env)` followed by `oc get co`

**Comment by shawgrey** [comment]
**No, unfortunately, It does not.**
![image](https://github.com/crc-org/crc/assets/111870951/43aed8bb-5d6c-4a96-bf66-9970dac13435)
I am still getting this

**Comment by shawgrey** [comment]
Now, This is something new for me.

I have monitored status using watch command and my crc status out put keep changing "Starting changes to Degraded and then Unreachable then Stopped and the Running and this cycle continues."

![image](https://github.com/crc-org/crc/assets/111870951/04eb19cd-d94c-41aa-a717-9669a9d2a2e7)
![image](https://github.com/crc-org/crc/assets/111870951/f363a14f-fcf0-4b42-9e62-ff4f4b561029)
![image](https://github.com/crc-org/crc/assets/111870951/94c7dac8-13d3-4530-b8bc-2c044ef41890)
here Degraded
![image](https://github.com/crc-org/crc/assets/111870951/e9a76573-de53-4e85-976b-324b651c01ab)

**Comment by cfergeau** [comment]
OpenShift status is  based on what `oc get co` returns, and some operators can restart a few times during startup, causing other ones to then decide their state is no longer correct, or causing the api server to go down (->unreachable) and up again, ...
The status being unstable during cluster startup is not too worrying, but if the cluster never reaches and stays on a "running" state, that's a problem. `oc get co` and `oc get co -ojson` would help to get a better idea of what's going on.

**Comment by slemeur** [comment]
Hi @shawgrey, you closed the issue - does it mean the problem does not appear to you anymore?
