### ISSUE TITLE
[QE] Missing oc binary when verify the cert with CA

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/crc#3792]
There is some random behavior when login into the cluster, which is being tracked on #3741. In order to debug what is the cause some debug steps had been added to the e2e scenarios on #3782.  Unfortunately those steps do not include force the eval of `crc oc-env`.

On those target machines where oc is not installed the step is failing as so all the test.

So we need to:

- [ ] added eval of `crc oc -env` to ensure we can use oc to get the `ca.crt` 
- [ x] ~as those steps are intended for debugging purposes and also the issue from #3741 may not affect all scenarios in case of an error on those steps the scenario probably should not fail but record the debug information~

**Comment by praveenkumar** [comment]
>  may not affect all scenarios in case of an error on those steps the scenario probably should not fail but record the debug information

These debugging steps are part of `background` which means it is going to executed before each scenario so that's the reason it fails the complete feature instead of a specific scenario.

**Comment by adrianriobo** [comment]
yeah what I meant is b/c how is defined within the feature file each step of the background for the debug is expected to succeed, in case any of the fail it fails and then as a background everything fail, what I am suggesting is not to check the succeed but only log the information (if something fails, not thrown an error but just record it on the log, this would allow proceed with the scenarios, although some of them could fail due to the cert issue)

**Comment by praveenkumar** [comment]
> what I am suggesting is not to check the succeed but only log the information (if something fails, not thrown an error but just record it on the log, this would allow proceed with the scenarios, although some of them could fail due to the cert issue)

The point is having it `succeed/failed` as part of background itself to make sure the scenarios which suppose to fail due to cert issue should failed early. The real issue for this bug was `oc` not present in the path and with #3795 that should taken care of.

**Comment by adrianriobo** [comment]
yeah, actually you are right,  it is failing on each scenario b/c of the `oc` issue, once it is fixed it should only fail where we have some issue with the cert , and other scenarios should be tested. I was thinking on it wrong
