### ISSUE TITLE
[BUG] Red Hat OpenShift Local on window 11 error - CRC version: 2.27.0

### ISSUE THREAD

**Issue by tinlam007** [crc-org/crc#3860]
### General information

  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / Hyper-V / hyperkit / vfkit
  * Did you run `crc setup` before starting it (Yes/No)?
  * Running CRC on: Laptop / Baremetal-Server / VM

## CRC version
```bash
# Put `crc version` output here
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```

## CRC config
```bash
# Put `crc config view` output here
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.
D:\Red Hat OpenShift Local>crc cleanup
INFO Removing the daemon task
INFO Removing the daemon task powershell script
INFO Stop daemon process if it is running
INFO Removing crc's virtual machine
INFO Removing CRC Specific entries from user's known_hosts file
INFO Removing hosts file records added by CRC
INFO Removing pull secret from the keyring
INFO Removing older logs
remove C:\Users\User\.crc\bin\hidden_daemon.ps1: The system cannot find the file specified.
host file not writable, try running with elevated privileges
Failed to remove old log files: Failed to delete file: remove C:\Users\User\.crc\crcd.log: The process cannot access the file because it is being used by another process.

D:\Red Hat OpenShift Local>crc setup
INFO Using bundle path C:\Users\User\.crc\cache\crc_hyperv_4.13.12_amd64.crcbundle
INFO Checking minimum RAM requirements
INFO Checking if current user is in crc-users and Hyper-V admins group
INFO Checking if CRC bundle is extracted in '$HOME/.crc'
INFO Checking if C:\Users\User\.crc\cache\crc_hyperv_4.13.12_amd64.crcbundle exists
INFO Checking if the daemon task powershell script is present
INFO Creating the daemon task powershell script
INFO Checking if the daemon task is installed
INFO Installing the daemon task
INFO Checking if the daemon task is running
INFO Running the daemon task
INFO Checking admin helper service is running
Your system is correctly setup for using CRC. Use 'crc start' to start the instance

D:\Red Hat OpenShift Local>crc start -p pull-secret.txt --log-level debug
DEBU CRC version: 2.27.0+71615e
DEBU OpenShift version: 4.13.12
DEBU Podman version: 4.4.4
DEBU Running 'crc start'
DEBU Total memory of system is 137243262976 bytes
DEBU No new version available. The latest version is 2.27.0
DEBU Checking file: C:\Users\User\.crc\machines\crc\.crc-exist
INFO Checking minimum RAM requirements
DEBU Total memory of system is 137243262976 bytes
INFO Checking if running in a shell with administrator rights
DEBU Running '$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent());$currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)'
INFO Checking Windows release
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ReleaseId).ReleaseId'
INFO Checking Windows edition
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").EditionID'
DEBU Running on Windows Professional edition
INFO Checking if Hyper-V is installed and operational
DEBU Running '@(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent'
DEBU Running '@(Get-Service vmms).Status'
INFO Checking if Hyper-V service is enabled
DEBU Running '@(Get-Service vmms).Status'
INFO Checking if crc-users group exists
DEBU Running 'Get-LocalGroup -Name crc-users'
INFO Checking if current user is in crc-users and Hyper-V admins group
DEBU Running '(Get-LocalGroupMember -Group 'crc-users').Name'
DEBU Checking current user is in the 'crc-user' group
DEBU group members: TIMLAM-PC\User
DEBU Running '(Get-LocalGroupMember -SID 'S-1-5-32-578').Name'
DEBU Checking current user is in the 'Hyper-v Administrators' group
DEBU group members: TIMLAM-PC\User
INFO Checking if vsock is correctly configured
DEBU Running 'Get-Item -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization\GuestCommunicationServices\00000400-FACB-11E6-BD58-64006A7986D3"'
INFO Checking if the daemon task powershell script is present
INFO Checking if the daemon task is installed
DEBU Running 'Get-ScheduledTask -TaskName crcDaemon'
DEBU Running '(Get-ScheduledTask -TaskName "crcDaemon").Version'
INFO Checking if the daemon task is running
DEBU Running '(Get-ScheduledTask -TaskName "crcDaemon").State'
DEBU expected crcDaemon task to be in 'Running' but got 'Ready
'
WARN Preflight checks failed during `crc start`, please try to run `crc setup` first in case you haven't done so yet
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ReleaseId).ReleaseId'
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").EditionID'
expected crcDaemon task to be in 'Running' but got 'Ready
'

D:\Red Hat OpenShift Local>systeminfo

Host Name:                 TIMLAM-PC
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          User
Registered Organization:
Product ID:                00330-73745-00003-AAOEM
Original Install Date:     3/18/2023, 4:10:01 PM
System Boot Time:          10/6/2023, 2:17:53 PM
System Manufacturer:       ASUS
System Model:              System Product Name
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 151 Stepping 2 GenuineIntel ~3600 Mhz
BIOS Version:              American Megatrends Inc. 1402, 4/1/2022
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi
Total Physical Memory:     130,885 MB
Available Physical Memory: 109,194 MB
Virtual Memory: Max Size:  150,341 MB
Virtual Memory: Available: 122,747 MB
Virtual Memory: In Use:    27,594 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\TIMLAM-PC
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5029921
                           [02]: KB5012170
                           [03]: KB5030310
                           [04]: KB5028756
                           [05]: KB5030508
Network Card(s):           7 NIC(s) Installed.
                           [01]: TAP-NordVPN Windows Adapter V9
                                 Connection Name: Ethernet 3
                                 Status:          Media disconnected
                           [02]: Intel(R) Ethernet Connection (17) I219-V
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.15.1
                                 IP address(es)
                                 [01]: 192.168.15.124
                                 [02]: fe80::153b:668a:6725:f39e
                           [03]: Intel(R) Wi-Fi 6 AX201 160MHz
                                 Connection Name: Wi-Fi 2
                                 Status:          Media disconnected
                           [04]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [05]: Kaspersky VPN
                                 Connection Name: Local Area Connection
                                 Status:          Media disconnected
                           [06]: VirtualBox Host-Only Ethernet Adapter
                                 Connection Name: Ethernet 4
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.56.1
                                 [02]: fe80::732e:67e8:832e:c78a
                           [07]: WireGuard Tunnel
                                 Connection Name: NordLynx
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 10.5.0.2
                                 [02]: fe80::723e:7ca:789d:a5aa
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

D:\Red Hat OpenShift Local>crc version
CRC version: 2.27.0+71615e
OpenShift version: 4.13.12
Podman version: 4.4.4

D:\Red Hat OpenShift Local>

**Comment by anjannath** [comment]
@tinlam007 can you try to start the `crcDaemon` task from the `Windows Task Scheduler` GUI? It might show more information as to why the task is not starting.

One more thing to try is to run the daemon posh script directly, on powershell run `~\.crc\bin\hidden_daemon.ps1` and check in the task manager if a process named `crc` is running

**Comment by tinlam007** [comment]
It is running  already

**Comment by tinlam007** [comment]
I reboot the window 11

**Comment by anjannath** [comment]
@tinlam007 do you still the have the issue after reboot, or able to start crc now?

**Comment by anjannath** [comment]
@tinlam007 your last reply via email is not visible from the Github web UI! :(

**Comment by anjannath** [comment]
You can try to skip the check and proceed with crc start:
```
PS> crc config set skip-check-daemon-task-running
PS> crc start  -p pull-secret.txt --log-level debug
```

**Comment by anjannath** [comment]
Turned out, @tinlam007 also had `kaspersky` installed, and root cause is same as #3674
