### ISSUE TITLE
Should the preflight for daemon running try to access the api instead of checking the scheduled task is running

### ISSUE THREAD

**Issue by anjannath** [crc-org/crc#3863]
There are two use cases currently where this will be helpful:
1. While developing we want to run the daemon manually using `crc daemon` the preflight check gets in the way
2. when we move to using https://github.com/cfergeau/win32-background-launcher for starting the daemon, the task scheduler doesn't show the status a Running, but shows it as Ready

**Comment by cfergeau** [comment]
> Should the preflight for daemon running try to access the api

I think there's already such a check to verify that the running daemon version matches the crc binary version

> when we move to using https://github.com/cfergeau/win32-background-launcher for starting the daemon, the task scheduler doesn't show the status a Running, but shows it as Ready

Maybe it's possible to improve the launcher to get a `Running` status which would be more accurate

> While developing we want to run the daemon manually using crc daemon the preflight check gets in the way

But it can be disabled with `crc config skip-...`?

**Comment by cfergeau** [comment]
Not saying we should not make this change, but there are additional improvements which could be made to make everything smoother.

**Comment by gbraad** [comment]
the check could be;

 - check if accessible/available
    - return true
 - else check scheduled task state (windows only)
    - return according to state

the second state should not occur unless the named pipe is not responding, so it becomes less likely this gets touched, but if it does, the cause is definitive.

**Comment by gbraad** [comment]
The issue with background launching, where the main process is not tracked, can cause the state of the scheduled task to become irrelevant. this does not sound to me like a good idea. I believe it can and should be launched and tracked.

**Comment by praveenkumar** [comment]
@anjannath is it still relevant or because we moved to background launcher this going to fix automatic?

**Comment by anjannath** [comment]
yeah, not relevant anymore the background-launcher task is being shown as running, i only observed the state was not shown once and couldn't reproduce it again.
