### ISSUE TITLE
[QE] Openshift Pipelines story false positive

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/crc#3864]
After the release `1.12.0` for Openshift Pipelines our tests started to fail, this is due to some delay between the operator shows a state of `Succeeded` 

```
NAME                                      DISPLAY                       VERSION   REPLACES                                  PHASE
openshift-pipelines-operator-rh.v1.12.0   Red Hat OpenShift Pipelines   1.12.0    openshift-pipelines-operator-rh.v1.11.1   Succeeded
```

And the `tekton-operator-webhook` is fully operative, we should check this condition within the tests to proceed creating a task

**Comment by jsliacan** [comment]
Resolved when #3877 was merged. Hopefully
