### ISSUE TITLE
Start daemon task on windows using win32-background-launcher

### ISSUE THREAD

**Issue by anjannath** [crc-org/crc#3879]
- [x] move repo (https://github.com/cfergeau/win32-background-launcher) to crc-org 
- [x] add `version` flag for `win32-background-launcher`
- [x] add rpm spec and build on brew
- [x] update installer and preflight checks
- [x] update jenkins jobs/pipeline for windows installer

**Comment by cfergeau** [comment]
Since it's quite some work to do this change, can you confirm this is a useful simplification of the daemon startup code on Windows? The costs  VS benefits ratio has to be worth the time we spend on this :)

**Comment by anjannath** [comment]
I believe this is worth the time, the current solution works, but tbh i don't understand how the script works, also if this [script](https://github.com/crc-org/crc/blob/5863186a246fc31cb7c883307ff7350c9fcef60d/pkg/crc/preflight/preflight_daemon_task_check_windows.go#L58-L93) ever stops working _again_ we'll have to spend time to find an alternative or debug/fix it.

with background launcher this will be future proof, and the changes for the preflight checks and the installer is not complicated (for msi installer just one more file to copy to install dir), am all for it :)

**Comment by gbraad** [comment]
> believe

'This' is not enough. Please spike if this is useful, as I am not convinced yet; add a spike issue before these steps to determine if move repo or update build scripts, etc.

Relevant information: https://learn.microsoft.com/en-us/windows/win32/procthread/process-creation-flags which I am missing from the example code.

**Comment by anjannath** [comment]
> > believe
> 
> 'This' is not enough. Please spike if this is useful, as I am not convinced yet; add a spike issue before these steps to determine if move repo or update build scripts, etc.
> 
we did test it that it works as expected, it is starting the daemon, or do you mean to test this with the relevant code changes that are needed on crc preflight and the installer?

> Relevant information: https://learn.microsoft.com/en-us/windows/win32/procthread/process-creation-flags which I am missing from the example code.

thanks, the example code is setting the `CREATE_NO_WINDOW` flag

**Comment by anjannath** [comment]
I did the changes needed on crc in this branch, it can be tested on windows to make sure it works as expected https://github.com/anjannath/crc/tree/background-launcher-spike

**Comment by anjannath** [comment]
done in #3901
