### ISSUE TITLE
[BUG] [Integration] CRC not starting behind on-the-host proxy without host-network-access

### ISSUE THREAD

**Issue by jsliacan** [crc-org/crc#3880]
### General information

  * OS: macOS
  * Hypervisor: vfkit
 
## CRC status
```bash
CRC VM:          Stopped
OpenShift:       Stopped (v4.13.14)
RAM Usage:       0B of 0B
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     107.9GB
Cache Directory: /Users/crcqe/.crc/cache
```

## CRC config
```bash
- consent-telemetry                     : no
- http-proxy                            : http://127.0.0.1:8888/
- https-proxy                           : http://127.0.0.1:8888/
- no-proxy                              : .testing
- proxy-ca-file                         : /var/folders/y_/j9ntcdvn28db04l6v9zp5k3r0000gn/T/rootCA.crt1694295845
```

## Host Operating System
```bash
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
```

When starting crc behind a goproxy running on the same host, the status does not change from the one above. This affects integration `goproxy_test.go` on the MacOS platform. Strangely, Windows or Linux (user mode) remain unaffected. See a related comment by @cfergeau [here](https://github.com/crc-org/crc/pull/3821#discussion_r1341166985).

**Comment by praveenkumar** [comment]
@jsliacan Have you tested with `host-network-access` configuration also like it is mentioned in the comment by @cfergeau ?

**Comment by jsliacan** [comment]
Not an actual issue after discussion, just a peculiarity.
