### ISSUE TITLE
[QE] Custom bundles not honored when sanitizing non running cluster

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/crc#3882]
On e2e we run some sanitize cluster when it is not running, on that code we missed to pass the custom bundle option if tests were started with it. As so it ends up starting a cluster within the default bundle. 

This lead to unrelable results for the `e2e`.

**Comment by jsliacan** [comment]
Turns out this was caused by using old test code. It does not happen when using e.g. latest e2e image v2.28.0.
