### ISSUE TITLE
Microshift failing after install

### ISSUE THREAD

**Issue by putriarsyi** [crc-org/crc#3884]
### General information

  * OS: rhel 9
  * microshift 4.13
  * installed on vm
  * cpu 2 core
  * ram 4 GB
  * disk 16 GB

## Host Operating System
NAME="Red Hat Enterprise Linux"
VERSION="9.2 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.2 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"

### Expected
Microsfhit start and running well

### Actual
Mcroshift keep failing

### Log
journalctl -u microshift.service

Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? I1020 12:06:40.009299  138928 run.go:104] Starting MicroShift
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010012  138928 certchains.go:122] [admin-kubeconfig-signer] rotate at: 2032-10-21 12:05:27 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010071  138928 certchains.go:122] [admin-kubeconfig-signer admin-kubeconfig-client] rotate at: 2032-10-21 12:05:27 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010113  138928 certchains.go:122] [aggregator-signer] rotate at: 2024-06-20 12:05:28 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010146  138928 certchains.go:122] [aggregator-signer aggregator-client] rotate at: 2024-06-21 05:06:39 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010176  138928 certchains.go:122] [etcd-signer] rotate at: 2032-10-21 12:05:30 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010208  138928 certchains.go:122] [etcd-signer apiserver-etcd-client] rotate at: 2032-10-21 12:05:30 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010238  138928 certchains.go:122] [ingress-ca] rotate at: 2032-10-21 12:05:29 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010268  138928 certchains.go:122] [ingress-ca router-default-serving] rotate at: 2024-06-20 12:05:29 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010298  138928 certchains.go:122] [kube-apiserver-external-signer] rotate at: 2032-10-21 12:05:29 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010328  138928 certchains.go:122] [kube-apiserver-external-signer kube-external-serving] rotate at: 2024-06-20 12:05:29 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010357  138928 certchains.go:122] [kube-apiserver-localhost-signer] rotate at: 2032-10-21 12:05:30 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010390  138928 certchains.go:122] [kube-apiserver-localhost-signer kube-apiserver-localhost-serving] rotate at: 2024-06-20 12:05:30 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010421  138928 certchains.go:122] [kube-apiserver-service-network-signer] rotate at: 2032-10-21 12:05:30 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010455  138928 certchains.go:122] [kube-apiserver-service-network-signer kube-apiserver-service-network-serving] rotate at: 2024-06-20 12:05:30 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010486  138928 certchains.go:122] [kube-apiserver-to-kubelet-signer] rotate at: 2024-06-20 12:05:27 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010515  138928 certchains.go:122] [kube-apiserver-to-kubelet-signer kube-apiserver-to-kubelet-client] rotate at: 2024-06-20 12:05:27 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010545  138928 certchains.go:122] [kube-control-plane-signer] rotate at: 2024-06-20 12:05:26 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010575  138928 certchains.go:122] [kube-control-plane-signer cluster-policy-controller] rotate at: 2024-06-21 05:06:39 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010605  138928 certchains.go:122] [kube-control-plane-signer kube-controller-manager] rotate at: 2024-06-21 05:06:39 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010634  138928 certchains.go:122] [kube-control-plane-signer kube-scheduler] rotate at: 2024-06-21 05:06:39 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010664  138928 certchains.go:122] [kube-control-plane-signer route-controller-manager] rotate at: 2024-06-20 12:05:26 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010693  138928 certchains.go:122] [kubelet-signer] rotate at: 2024-06-20 12:05:28 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010722  138928 certchains.go:122] [kubelet-signer kube-csr-signer] rotate at: 2024-06-20 12:05:28 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010755  138928 certchains.go:122] [kubelet-signer kube-csr-signer kubelet-client] rotate at: 2024-06-20 12:05:28 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010785  138928 certchains.go:122] [kubelet-signer kube-csr-signer kubelet-server] rotate at: 2024-06-20 12:05:28 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010814  138928 certchains.go:122] [service-ca] rotate at: 2032-10-21 12:05:29 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? E1020 12:06:40.010844  138928 certchains.go:122] [service-ca route-controller-manager-serving] rotate at: 2024-06-20 12:05:29 +0000 UTC
Oct 20 12:06:40 localhost.localdomain microshift[138928]: ??? I1020 12:06:40.010972  138928 run.go:115] Started service-manager
Oct 20 12:06:40 localhost.localdomain microshift[138928]: network-configuration I1020 12:06:40.011056  138928 manager.go:114] Starting network-configuration
Oct 20 12:06:40 localhost.localdomain microshift[138928]: network-configuration I1020 12:06:40.012221  138928 netconfig.go:74] "network-configuration" is ready
Oct 20 12:06:40 localhost.localdomain microshift[138928]: etcd I1020 12:06:40.012310  138928 manager.go:114] Starting etcd
Oct 20 12:06:40 localhost.localdomain microshift[138928]: sysconfwatch-controller I1020 12:06:40.013209  138928 manager.go:114] Starting sysconfwatch-controller
Oct 20 12:06:40 localhost.localdomain microshift[138928]: sysconfwatch-controller I1020 12:06:40.014124  138928 sysconfwatch_linux.go:89] starting sysconfwatch-controller with IP address "192.168.12.40"
Oct 20 12:06:40 localhost.localdomain microshift[138928]: sysconfwatch-controller I1020 12:06:40.014191  138928 sysconfwatch_linux.go:95] sysconfwatch-controller is ready
Oct 20 12:06:40 localhost.localdomain microshift[138928]: etcd W1020 12:06:40.014905  138928 logging.go:59] [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {
Oct 20 12:06:40 localhost.localdomain microshift[138928]:   "Addr": "localhost:2379",
Oct 20 12:06:40 localhost.localdomain microshift[138928]:   "ServerName": "localhost",
Oct 20 12:06:40 localhost.localdomain microshift[138928]:   "Attributes": null,
Oct 20 12:06:40 localhost.localdomain microshift[138928]:   "BalancerAttributes": null,
Oct 20 12:06:40 localhost.localdomain microshift[138928]:   "Type": 0,
Oct 20 12:06:40 localhost.localdomain microshift[138928]:   "Metadata": null
Oct 20 12:06:40 localhost.localdomain microshift[138928]: }. Err: connection error: desc = "transport: Error while dialing dial tcp [::1]:2379: connect: connection refused"
Oct 20 12:06:43 localhost.localdomain microshift[138928]: etcd I1020 12:06:43.014866  138928 etcd.go:122] etcd is ready!
Oct 20 12:06:43 localhost.localdomain microshift[138928]: kube-apiserver I1020 12:06:43.014913  138928 manager.go:114] Starting kube-apiserver
Oct 20 12:06:43 localhost.localdomain microshift[138928]: Flag --openshift-config has been deprecated, to be removed

**Comment by praveenkumar** [comment]
@putriarsyi Can you provide more details and use https://github.com/crc-org/crc/issues/new?assignees=&labels=kind%2Fbug%2C+status%2Fneed+triage&projects=&template=bug_report.md&title=%5BBUG%5D as template?

**Comment by gbraad** [comment]
The question here is: are you using our image? Or are you installing microshift outside the use of CRC?

In short: no, we do not experience an issue with installing Microshift, as it is the base of our image we distribute.

**Comment by putriarsyi** [comment]
> The question here is: are you using our image? Or are you installing microshift outside the use of CRC?
> 
> In short: no, we do not experience an issue with installing Microshift, as it is the base of our image we distribute.

I installed from red hat rpm package, I registered subscription manager. I just follow this step https://access.redhat.com/documentation/en-us/red_hat_build_of_microshift/4.13/html/installing/microshift-install-rpm

**Comment by gbraad** [comment]
In that case, you are reporting it to the wrong project. We deal with pre-opinionated images for the developer usecase. These instructions are not.

**Comment by putriarsyi** [comment]
> In that case, you are reporting it to the wrong project. We deal with pre-opinionated images for the developer usecase. These instructions are not.

I will open the on other project. thanks

**Comment by gbraad** [comment]
Thanks for filing: https://github.com/openshift/microshift/issues/2493 though I would suggest adding more information, such as steps you performed, config you made, etc.
