### ISSUE TITLE
[BUG] Mac M2 arch reporting as M1

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/crc#3889]
AWS offers support for mac M2, when trying `crc` on an M2 the INFO message is identifying the CPU as a M1:

```
INFO Checking if running emulated on a M1 CPU
```

Checking the arch we can see the M2

```
ec2-user@Mac-mini ~ % sysctl machdep.cpu.brand_string
machdep.cpu.brand_string: Apple M2 Pro
```

**Comment by gbraad** [comment]
When we added this message, the M2 didn't exist. We check for arch64 on an Apple computer. Perhaps we just change this to 'Apple silicon' instead.

**Comment by adrianriobo** [comment]
Or use the output from that macro?

**Comment by cfergeau** [comment]
> Or use the output from that macro?

In some  instances, it would not be correct, for example `CRC can only run on AMD64/Intel64 CPUs and Apple silicon`. This cannot be changed to `CRC can only run on AMD64/Intel64 CPUs and M2 Pro`

**Comment by adrianriobo** [comment]
~~I meant the output from `sysctl machdep.cpu.brand_string`~~ Ok understood
