### ISSUE TITLE
access https://console-openshift-console.apps-crc.testing remotely

### ISSUE THREAD

**Issue by eliassal** [crc-org/crc#3925]
### General information

 * OS: Windows Server 2022
   * Hypervisor: Hyper-V
   * Did you run crc setup before starting it (Yes/No)? Yes
   * Running CRC on: VM

## CRC version
```bash
# CRC version: 2.29.0+da5f55
```
  
## CRC status
```bash
level=debug msg="CRC version: 2.29.0+da5f55\n"
level=debug msg="OpenShift version: 4.14.1\n"
level=debug msg="Podman version: 4.4.4\n"
level=debug msg="Running 'crc status'"
CRC VM:          Running
OpenShift:       Starting (v4.14.1)
RAM Usage:       8.104GB of 12.5GB
Disk Usage:      26.74GB of 32.68GB (Inside the CRC VM)
Cache Usage:     25.11GB
Cache Directory: C:\Users\salam\.crc\cache
level=debug msg="Running '(Get-ItemProperty -Path \"HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\" -Name ReleaseId).ReleaseId'"
level=debug msg="Running '(Get-ItemProperty -Path \"HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\").EditionID'"
```

### Steps to reproduce

  1. I have openshift up and runninng and able to access the console locally, my quesion is How can I access it remotely from anothe machine inside my network? Thanks
  I searched the documentation at https://access.redhat.com/documentation but not able to find any hint there

**Comment by gbraad** [comment]
Please read the documentation, especially the networking topic!

Latest version is available at: https://crc.dev/crc/getting_started/getting_started/networking/

Note: that the remote access is specifically described for Linux, but it is merely a semi-supported scenario. We do not support this as this is a network specific setup that depends on your own environment and needs.
