### ISSUE TITLE
[QE] Build and publish crc-e2e and crc-integration as a PR check

### ISSUE THREAD

**Issue by jsliacan** [crc-org/crc#3931]
Follow-up to #3875

**Comment by adrianriobo** [comment]
Can you create 2 different flows for that? I mean do not build the images within the testing flow but as separate flow which build the images (installer alike) and as so it willl be used as check to ensure nothing changed lets say on the Dockerfile would break nothing

**Comment by jsliacan** [comment]
Completed via #3933
