### ISSUE TITLE
[BUG] - CRC start on Windows fails with `expected crcDaemon task to be Running but got Ready` in `v2.29`

### ISSUE THREAD

**Issue by maulik-modi22** [crc-org/crc#3942]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V 
  * Did you run `crc setup` before starting it: yes
  * Running CRC on: Laptop

## CRC version
```bash
CRC version: 2.29.0+da5f55
OpenShift version: 4.14.1
Podman version: 4.4.4
```
  
## CRC status
```bash
CRC VM:          Stopped
OpenShift:       Stopped (v4.14.1)
RAM Usage:       0B of 0B
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     25.11GB
Cache Directory: C:\Users\[[SANITISED]]\.crc\cache
```

## CRC config
```bash
- consent-telemetry                     : yes
```

## Host Operating System
```bash
Host Name:                 HOMEPC
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          [[SANITISED]]
Registered Organization:   N/A
Product ID:                 [[SANITISED]]
Original Install Date:     24-12-2022, 19:18:46
System Boot Time:          06-12-2023, 15:03:56
System Manufacturer:       Acer
System Model:              Aspire A715-51G
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 154 Stepping 3 GenuineIntel ~1700 Mhz
BIOS Version:              INSYDE Corp. V1.04, 09-04-2022
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi
Total Physical Memory:     16,088 MB
Available Physical Memory: 8,570 MB
Virtual Memory: Max Size:  18,520 MB
Virtual Memory: Available: 8,394 MB
Virtual Memory: In Use:    10,126 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\HOMEPC
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5032007
                           [02]: KB5012170
                           [03]: KB5032288
                           [04]: KB5032393
Network Card(s):           3 NIC(s) Installed.
                           [01]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [02]: MediaTek Wi-Fi 6 MT7921 Wireless LAN Card
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.29.1
                                 IP address(es)
                                 [01]: 192.168.29.98
                                 [02]: fe80::c546:d641:c4fd:cce7
                                 [03]: 2405:201:2001:2b21:7567:8a72:6a27:c23e
                                 [04]: 2405:201:2001:2b21:101b:5d4a:81fe:f207
                           [03]: VirtualBox Host-Only Ethernet Adapter
                                 Connection Name: Ethernet 5
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.56.1
                                 [02]: fe80::8078:cbad:2119:a41a
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

### Steps to reproduce

  1. Run `crc setup`
  2. Run `crc start`

### Expected
crc start starts Openshift container platform on laptop

### Actual
CRC start debug fails with expected crcDaemon task to be Running but got Ready

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```
Tried above steps but it fails with same error

https://gist.github.com/maulik-modi22/0521ddd24cf09cc7b145f2a0a1c4c803

**Comment by gbraad** [comment]
Please update to 2.30 which was just released.

**Comment by gbraad** [comment]
Related to https://github.com/crc-org/crc/pull/3901, but this is not integrated.

@anjannath, possible workaround?

**Comment by maulik-modi22** [comment]
@gbraad or @anjannath or @adrianriobo 

1. what is the command to update `crc` version to `2.30`? Do i need to download `crc` `2.30` from [openshift mirror](https://mirror.openshift.com/pub/openshift-v4/clients/crc/2.30.0/) or [developer.redhat.com-latest](https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/latest/crc-windows-installer.zip)
2. Where can I find release note for `crc` version `2.30` stating above issue has been fixed, I can only find release note related to version [`2.29`](https://access.redhat.com/documentation/es-es/red_hat_openshift_local/2.29/html-single/getting_started_guide/index)

**Comment by anjannath** [comment]
@maulik-modi22 `2.30.0` was release today, you can find it here: https://github.com/crc-org/crc/releases/tag/v2.30.0
> what is the command to update crc version to 2.30? Do i need to download crc 2.30 from [openshift mirror](https://mirror.openshift.com/pub/openshift-v4/clients/crc/2.30.0/) or [developer.redhat.com-latest](https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/latest/crc-windows-installer.zip)

yes you have to download the MSI and install it from openshift mirror

about the issue with `2.29.0` can you please share the o/p of `crc setup --log-level debug`

**Comment by maulik-modi22** [comment]
@anjannath ,
here's o/p of `crc setup --log-level debug`
https://gist.github.com/maulik-modi22/c28ebff63ef94e105c6700ae23cd57c8

I believe `crc setup` debug log schedules task and assumes `crcDaemon` will be in a `running` state but actually when I went to Task scheduler, it shows in `Ready` state. Even I tried to `Run` manually, it still enters into `Ready` state 
```
INFO Running the daemon task
DEBU Running 'Start-ScheduledTask -TaskName crcDaemon'
```
![crcDaemon](https://github.com/crc-org/crc/assets/108735641/7bf29496-7ea2-4b99-9514-551e98cd1c18)

Then, When I tried to run `crc start`, It shows WARN 
```
WARN Preflight checks failed during `crc start`, please try to run `crc setup` first in case you haven't done so yet
expected crcDaemon task to be in 'Running' but got 'Ready
```

@gbraad , Kindly remove `status/Need more information` label 
  OR 
ask for more information that is required to troubleshoot the issue.

**Comment by anjannath** [comment]
Thanks for providing the logs, from the logs it seems `crc setup` was able to start the daemon (or it detects it as running and reports setup as successful)

> I believe crc setup debug log schedules task and assumes crcDaemon will be in a running state but actually when I went to Task scheduler, it shows in Ready state. Even I tried to Run manually, it still enters into Ready state

it also tries to start the task using powershell commands, but for some reason its not running, to find out what could be reason, can you check if you are able to run the daemon directly by running the command `crc daemon`

also check in the task manager that an existing instance of the daemon is not already running (only one instance of the daemon is allowed to run)

the scheduled task runs the daemon via the powershell script at `~\.crc\bin\hidden_daemon.ps1` you could try running this script directly to find out if there's a bug in that script

**Comment by maulik-modi22** [comment]
## Before running `crc daemon` - task manager - no crc daemon
![crc-taskmanager](https://github.com/crc-org/crc/assets/108735641/07828b33-f623-4df4-b94c-5c082ea4812a)


## After running `crc daemon` in terminal 1 & running `crc start` in terminal 2

![crc-daemon-crc-start](https://github.com/crc-org/crc/assets/108735641/a3428d4d-4bbb-411a-9132-4253b87e581f)

@anjannath , do let me know if this gives any hint?

**Comment by anjannath** [comment]
@maulik-modi22 daemon is able to start when the command is ran directly, can you try to run the powershell script `~\.crc\bin\hidden_daemon.ps1` and see if that throws any error, if it doesn't exit with an error, check again in task manager if `crc` daemon process was started.

**Comment by maulik-modi22** [comment]
@anjannath ,Looks like logs were insufficient to diagnose the problem in `v2.29`, you may want to add additional logging in upcoming releases especially when `debug` switch is `ON`; 

I gave up and decided to give `v2.30` a shot and I was able to get cluster Up and running;

Is there any special treatment required for egress / internet access to download public images from DockerHub?

**Comment by anjannath** [comment]
> @anjannath ,Looks like logs were insufficient to diagnose the problem in `v2.29`, you may want to add additional logging in upcoming releases especially when `debug` switch is `ON`;
> 
> I gave up and decided to give `v2.30` a shot and I was able to get cluster Up and running;
> 
glad the new version works for you, but this is strange as there's no changes to `v2.30` in the code to start the daemon
anyways we are working on improving the way the daemon is ran

> Is there any special treatment required for egress / internet access to download public images from DockerHub?

No, but if you need to pull from a private registry please refer to https://docs.openshift.com/container-platform/4.14/openshift_images/managing_images/using-image-pull-secrets.html#images-allow-pods-to-reference-images-from-secure-registries_using-image-pull-secrets

closing as the original issue is fixed for OP
