### ISSUE TITLE
[BUG] CRC fails to complete setup on mac m2

### ISSUE THREAD

**Issue by evgenymo** [crc-org/crc#3954]
### General information

  * OS: macOS
  * Hypervisor: hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
CRC version: 2.30.0+b6532a
OpenShift version: 4.14.3
Podman version: 4.4.4
```
  
## CRC status
```bash
DEBU CRC version: 2.30.0+b6532a
DEBU OpenShift version: 4.14.3
DEBU Podman version: 4.4.4
DEBU Running 'crc status'
crc does not seem to be setup correctly, have you run 'crc setup'?
```

## CRC config
```bash
- consent-telemetry                     : no
```

## Host Operating System
```bash
ProductName:		macOS
ProductVersion:		14.1.2
BuildVersion:		23B92
```

### Steps to reproduce

  1. Download latest DMG file for crc
  2. Install crc
  3. Run crc setup

### Expected
Crc Installed

### Actual
Crc Deleted and process killed

### Logs
```
INFO Using bundle path /Users/evgeny/.crc/cache/crc_vfkit_4.14.3_arm64.crcbundle
INFO Checking if running as non-root
INFO Checking if crc-admin-helper executable is cached
INFO Checking if running on a supported CPU architecture
INFO Checking if crc executable symlink exists
INFO Checking minimum RAM requirements
INFO Checking if running emulated on Apple silicon
INFO Checking if vfkit is installed
INFO Checking if CRC bundle is extracted in '$HOME/.crc'
INFO Checking if /Users/evgeny/.crc/cache/crc_vfkit_4.14.3_arm64.crcbundle exists
INFO Checking if old launchd config for tray and/or daemon exists
INFO Checking if crc daemon plist file is present and loaded
INFO Adding crc daemon plist file and loading it
[1]    65665 killed     crc setup
```

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```
Didn't help since i never completed setup.

**Comment by praveenkumar** [comment]
@evgenymo can you provide `crc setup --log-level debug` info because I am not sure why it get killed as part of adding the daemon plist file?

**Comment by evgenymo** [comment]
Hey @praveenkumar,
No need for logs i actually figured it out, we have SentinelOne installed and it's the culprit here, it quarantines and deletes both CRC and the plist file because it detects them as "persistence deception", seems to be a common issue:
https://github.com/lwouis/alt-tab-macos/issues/2725
https://www.sentinelone.com/blog/how-malware-persists-on-macos/

You can close the issue based on this or keep and to track your issue with SentinelOne.
Sorry for the false positive bug and have a nice day.

**Comment by praveenkumar** [comment]
@evgenymo Thanks you, I am going to close this issue. May be we should add in some kind of FAQ.
