### ISSUE TITLE
Removal of podman preset from config and codebase

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/crc#3970]
`Podman` preset was added when there was no podman machine and now it is not consumed by users and we also stopped updating the bundles from some time now. It would be better to remove it from crc codebase.

**Comment by cfergeau** [comment]
We could first start by warning or erroring out when the podman preset is used, this is easier to revert if there are unexpected blockers with it (I hope not!)

**Comment by gbraad** [comment]
I agree with Christophe to first error out, but the next release after this would be OK to remove this.

Would it be OK for Gunjan (@vyasgun) to look at this?

**Comment by anjannath** [comment]
erroring out will be better, we already announced that the preset will be removed in 2.28.0 release https://github.com/crc-org/crc/releases/tag/v2.28.0

i think we should also stop shipping the podman client and putting it on `~/.crc/bin/oc/podman` and adding to PATH?

**Comment by praveenkumar** [comment]
> i think we should also stop shipping the podman client and putting it on `~/.crc/bin/oc/podman` and adding to PATH?

podman client we ship for `microshift/openshift` bundle also to consume so that shouldn't be removed.

**Comment by praveenkumar** [comment]
> Would it be OK for Gunjan (@vyasgun) to look at this?

Sure, assigned.

**Comment by cfergeau** [comment]
> > i think we should also stop shipping the podman client and putting it on `~/.crc/bin/oc/podman` and adding to PATH?
> 
> podman client we ship for `microshift/openshift` bundle also to consume so that shouldn't be removed.

Maybe we should integrate better with podman installed through podman's official installer, or even ship/use podman iwndows/mac installer instead of shipping our own binaries?

**Comment by gbraad** [comment]
^^^ I agree, but let's first at messaging and have a new issue to discuss how to integrate/distribute.

**Comment by cfergeau** [comment]
> ^^^ I agree, but let's first at messaging and have a new issue to discuss how to integrate/distribute.

Yup, definitely a (long term) next step after we've dealt with the podman preset :)

**Comment by anjannath** [comment]
> i think we should also stop shipping the podman client and putting it on ~/.crc/bin/oc/podman and adding to PATH?

The main issue i faced while using `crc` and podman machine together can be solved if we fix #4022

**Comment by cfergeau** [comment]
#4062 has been merged, this can be closed.
