### ISSUE TITLE
[QE] Control which PRs should run e2e tests

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/crc#3971]
Right now any change across the code will run the win e2e test (i.e docs PRs will run them when it is unnecessary https://github.com/crc-org/crc/pull/3967) 

For win e2e the trigger comes from the windows installer, which again for doc it may make no sense to be build for certain changes (i.e docs)

So we need to add those as ignore-paths https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths

**Comment by praveenkumar** [comment]
We need to do same for openshift CI also.

**Comment by adrianriobo** [comment]
Fixed by #4071
