### ISSUE TITLE
Failed to ask for pull secret: cannot ask for secret, crc not launched by a terminal

### ISSUE THREAD

**Issue by bianchi2** [crc-org/crc#3977]
I am trying to install crc on a remote mac machine (GitHub actions) and get this error, even though I am passing `-p /path/to/pull-secret/file` when running crc start:

```
Failed to ask for pull secret: cannot ask for secret, crc not launched by a terminal
```

**Comment by gbraad** [comment]
why did you close the issue?

**Comment by bianchi2** [comment]
@gbraad it was a mistake on my end - malformed pull secret file. After rerunning in a debig mode, verbose logs shed more light on the problem.
