### ISSUE TITLE
Intermittent failures to start crc in GitHub Actions

### ISSUE THREAD

**Issue by bianchi2** [crc-org/crc#3980]
I wonder if anyone faced this in existing crc GitHub Workflows. My workflow yaml looks like this (basically a copy of https://github.com/crc-org/crc/blob/main/.github/workflows/test-okd-bundle.yml), runs on Ubuntu latest. crc version 2.31.0.

```
- name: Install required virtualization software
  run: |
    sudo apt-get update
    sudo apt install qemu-kvm libvirt-daemon libvirt-daemon-system
    sudo usermod -a -G libvirt $USER

- name: Set the crc config
  run: |
    crc config set consent-telemetry no
    crc config set network-mode user

- name: Setup the crc
  run: sudo -su $USER crc setup
        
- name: Start the crc
  run: sudo -su $USER crc start -p pull-secret.txt
```

From time to time, one particular oc apply returns 124. Maybe 1-2 times out of 10. It's always oc aply routes-controller. I wonder if anyone has clues on what may be going wrong. Looks like VM (or apiserver) becomes unreachable and the command just times out not getting any response?

```
level=info msg="Updating cluster ID..."
level=debug msg="Running SSH command: timeout 30s oc patch clusterversion version -p '{\"spec\":{\"clusterID\":\"057693e0-6ab5-49f6-8844-60f99b60cd8e\"}}' --type merge --context admin --cluster crc --kubeconfig /opt/kubeconfig"
level=debug msg="SSH command results: err: <nil>, output: clusterversion.config.openshift.io/version patched\n"
level=debug msg="Running SSH command: ls /opt/crc/routes-controller.yaml"
level=debug msg="SSH command results: err: <nil>, output: /opt/crc/routes-controller.yaml\n"
level=debug msg="Running SSH command: timeout 30s oc apply -f /opt/crc/routes-controller.yaml --context admin --cluster crc --kubeconfig /opt/kubeconfig"
level=debug msg="SSH command results: err: Process exited with status 124, output: "
level=debug msg="Making call to close driver server"
level=debug msg="(crc) Calling .Close"
level=debug msg="(crc) DBG | time=\"2024-01-30T03:26:56Z\" level=debug msg=\"Closing plugin on server side\""
level=debug msg="Successfully made call to close driver server"
level=debug msg="Making call to close connection to plugin binary"
ssh command error:
command : timeout 30s oc apply -f /opt/crc/routes-controller.yaml --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 124
```

**Comment by praveenkumar** [comment]
> Maybe 1-2 times out of 10. It's always oc aply routes-controller. I wonder if anyone has clues on what may be going wrong. Looks like VM (or apiserver) becomes unreachable and the command just times out not getting any response?

If it fails 10-20% time that means it mostly because of the resource limit on github runner side since it is still running as nested virtualization and on hypervisor side sometime it is overload. `124` exit code is timeout situation where within 30 sec API is not responding and it might be because of IO overhead for the runner. 

Can you let us know to which project you are trying to use it as part of CI? Can you try out microshift preset for your testing if that is enough?

**Comment by bianchi2** [comment]
@praveenkumar thanks fro your response. Yeah, that's what I thought - api not responding and 124 is the result of it. Basically, I need a minimalistic OpenShift cluster to verify 2 things:

* my containers start with restricted SCC and pass readinessProbes (we're validating that images are OpenShift friendly)
* routes are created and /status responds 200

Is MicroShift enough to deploy an app that will utilize ~1-2Gi of RAM + a Postgres pod.

**Comment by praveenkumar** [comment]
> Is MicroShift enough to deploy an app that will utilize ~1-2Gi of RAM + a Postgres pod.

Yes I think it should work, do try and let me know.

**Comment by bianchi2** [comment]
@praveenkumar thanks a lot! Yes, microshift proved to be a lot more stable (and faster to spin up). It's exactly what I need for the CI where I am validating image start in OpenShift and some Helm chart changes. Closing this ticket.
