### ISSUE TITLE
[BUG] Microshift version is not reported as part of version command

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/crc#4098]
Checking the `crc version` we can not see the microshift version even with the microshift preset 

``` bash
macmini-crcqe-2:2.34.1 crcqe$ crc setup --log-level debug
DEBU CRC version: 2.34.1+b470b5                   
DEBU OpenShift version: 4.15.3                    
DEBU Podman version: 4.4.4      
```

Not sure if that is on purpose, but during previous sprint it was discussed to release with versions out of sync, so then it had not been easy to see the microshift version

**Comment by praveenkumar** [comment]
fixed by https://github.com/crc-org/crc/pull/4269
