### ISSUE TITLE
[BUG] `Podman version` in `crc version` is meaningless?

### ISSUE THREAD

**Issue by cfergeau** [crc-org/crc#4099]
### General information

  * OS: Linux
 
## CRC version
```bash
# Put `crc version` output here
CRC version: 2.34.1+fa1b45
OpenShift version: 4.15.3
Podman version: 4.4.4
```

Recent OpenShift clusters use podman 4.4.1, my linux machine has a more recent podman, I suspect this 4.4.4 version is the version hardcoded there https://github.com/crc-org/crc/blob/2331271ac2ec679056e807d2e80a665c39032122/Makefile#L6 and has no meaning (it used to mean "if you download a podman bundle, the bundle version will be 4.4.4, and incidentally this corresponded to the podman version running in the bundle).

```bash
$ podman version
Client:       Podman Engine
Version:      4.9.3
API Version:  4.9.3
Go Version:   go1.21.7
Built:        Mon Feb 19 16:41:34 2024
OS/Arch:      linux/amd64
```

**Comment by cfergeau** [comment]
Kind of related to https://github.com/crc-org/crc/issues/4098

**Comment by rohanKanojia** [comment]
@cfergeau : is this issue resolved? I'm no longer able to see `Podman Version` in `crc version` output.

**Comment by cfergeau** [comment]
Must have been removed as part of https://github.com/crc-org/crc/pull/4062 or https://github.com/crc-org/crc/pull/4167

**Comment by rohanKanojia** [comment]
@cfergeau : I see this output on crc v2.42.0: 

```
CRC version: 2.42.0+261e97
OpenShift version: 4.17.0
MicroShift version: 4.16.14
```

I think we can close this issue as completed.
