### ISSUE TITLE
Pods in openshift-marketplace namespace crashing - cache requires rebuild: cache reports digest

### ISSUE THREAD

**Issue by JiriHusak-lab** [crc-org/crc#4119]
Hi,

I’ve installed CRC new version:
CRC version: 2.34.1+b470b5
OpenShift version: 4.15.3
Podman version: 4.4.4

Before installation I have run crc stop, crc delete, crc cleanup and rm -r .config; rm -r .crc as well.

Installation has been properly finished, cluster is running but 4 pods in namespace openshift-marketplace are crashing:

oc get pods:
NAME                                                                          READY   STATUS                           RESTARTS        AGE
certified-operators-tvk2q                                          0/1     CrashLoopBackOff   6 (2m51s ago)   23d
community-operators-z9bzg                                    0/1     CrashLoopBackOff   6 (2m46s ago)   23d
marketplace-operator-568756cbf5-654nq             1/1     Running            0               24d
redhat-marketplace-zf49d                                         0/1     CrashLoopBackOff   6 (3m26s ago)   23d
redhat-operators-9jb87                                              0/1     CrashLoopBackOff   6 (2m33s ago)   23d

Error:
time="2024-04-18T14:24:44Z" level=info msg="starting pprof endpoint" address="localhost:6060"
2time="2024-04-18T14:24:45Z" level=fatal msg="cache requires rebuild: cache reports digest as \"56b2b000157b2413\", but computed digest is \"f9fd589ccba6dca2\""

I have uninstalled crc, cleaned server and installed the same crc version again but the result is the same.

Any advice please?

Thanks and Regards,
Jiri

**Comment by adrianriobo** [comment]
You will need to workaround it with https://github.com/crc-org/crc/issues/4109#issuecomment-2042497411

**Comment by adrianriobo** [comment]
Closed as duplicated of #4109
