### ISSUE TITLE
CRC openshift local marketplace pods Failed to pull image failed to verify certificate: x509

### ISSUE THREAD

**Issue by dfollereau** [crc-org/crc#4159]
Hello

While deploying local on laptop Apple M1 pro with crc (latest version):

crc delete
crc cleanup
crc setup
crc start

crc status
CRC VM:          Running
OpenShift:       Running (v4.15.10)
RAM Usage:       6.574GB of 22.5GB
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     187.9GB
Cache Directory: /Users/dfollereau/.crc/cache

crc version
CRC version: 2.35.0+3956e8
OpenShift version: 4.15.10
Podman version: 4.4.4

I am having marketplace 8 PODs in failed state with this error message: 

namespace : openshift-marketplace
openshift-marketplace                                certified-operators-8sp8h                                       0/1      Init:ImagePullBackOff               0 10.217.0.60        crc      10m
openshift-marketplace                                certified-operators-l8fnj                                       0/1      Init:ImagePullBackOff               0 10.217.0.66        crc      2m3s
openshift-marketplace                                community-operators-g4btn                                       0/1      Init:ImagePullBackOff               0 10.217.0.67        crc      90s
openshift-marketplace                                community-operators-pcr5g                                       0/1      Init:ImagePullBackOff               0 10.217.0.58        crc      10m
openshift-marketplace                                redhat-marketplace-b59j9                                        0/1      Init:ImagePullBackOff               0 10.217.0.61        crc      11m
openshift-marketplace                                redhat-marketplace-wsm6z                                        0/1      Init:ImagePullBackOff               0 10.217.0.62        crc      11m
openshift-marketplace                                redhat-operators-djxv8                                          0/1      Init:ImagePullBackOff               0 10.217.0.63        crc      11m
openshift-marketplace                                redhat-operators-r5mpn                                          0/1      Init:ImagePullBackOff               0 10.217.0.64

Logs:
Normal   Pulling         11m (x4 over 12m)     kubelet            Pulling image "registry.redhat.io/redhat/certified-operator-index:v4.15"
Warning  Failed          11m (x4 over 12m)     kubelet            Failed to pull image "registry.redhat.io/redhat/certified-operator-index:v4.15": pinging container registry registry.redhat.io: Get "http │
│ s://registry.redhat.io/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority

Do you know how to fix this?
is there a way to set --tls-verify=false ?

Thanks a lot for your support
Denis

**Comment by praveenkumar** [comment]
This looks like dup to https://github.com/crc-org/crc/issues/4109 one? can you tell which version of crc  you are running and does https://github.com/crc-org/crc/issues/4109#issuecomment-2042497411 resolve for you?

**Comment by praveenkumar** [comment]
Closing as dup and already fixed in latest version. Please reopen if it is not the case
