### ISSUE TITLE
TRANSIENT_FAILURE with ibm-operator-catalog

### ISSUE THREAD

**Issue by aganagic** [crc-org/crc#4195]
HI,

I keep getting transient_failures for ibm-operator-catalog. It is over 50% in that state versus READY.
Is there any remedy for that?

Thanks,

Edin

**Comment by praveenkumar** [comment]
@aganagic Please use issue template to creating the bug (closing this one)  with this info we are not sure what is actual issue.

**Comment by aganagic** [comment]
Hi Praveen,

I am not quite clear how to work with the template. But, here is the issue. Whether I create dynamic or static ibm-operator-catalog, e.g.

oc apply -f https://raw.githubusercontent.com/ibm-mas/cli/master/catalogs/v8-240430-amd64.yaml

and then got to  Cluster Settings -> CustomResourceDefinition -> OperatorHub -> Instances -> Cluster  -> Sources

I can see that ibm-operator -catalog is in TRANSIENT_FAILURE state most of the time and it needs to be in READY state. Obviosly, I cannot work like this.

Redhat 8.9

$crc version
CRC version: 2.36.0+27c493
OpenShift version: 4.15.12
Podman version: 4.4.4
***@***.***:/home/aganagic

$crc config view
- consent-telemetry                     : no
- cpus                                  : 72
- host-network-access                   : true
- memory                                : 491520
- network-mode                          : user
- pull-secret-file                      : /cliconfig/pull-secret.txt
***@***.***:/home/aganagic

If you need any more info please let me know. I am trying t install IBM MAS on this cluster an d I can't.

Thanks,

Edn


________________________________________________

EDIN I. AGANAGIC



Cross Sustainability SME, IBM Sustainability Software

***@***.******@***.***>, 416.729.8476





________________________________
From: Praveen Kumar ***@***.***>
Sent: Wednesday, June 5, 2024 12:27 AM
To: crc-org/crc ***@***.***>
Cc: Edin Aganagic ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [crc-org/crc] TRANSIENT_FAILURE with ibm-operator-catalog (Issue #4195)

This Message Is From an External Sender
This message came from outside your organization.
Report Suspicious<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/AdhS1Rd-!9BFRGhxR-ecxFh8RxIdruQh9Ggv51UQFWw3YC4M8UKe3amKLenCOXlmGxDu-A6pGeSA05lQK-UC_ieLas3e7KQwHqn_WakE$>


@aganagic<https://github.com/aganagic> Please use issue template to creating the bug (closing this one) with this info we are not sure what is actual issue.

**Comment by aganagic** [comment]
Hi Praveen,

I am not quite clear how to work with the template. But, here is the issue. Whether I create dynamic or static ibm-operator-catalog, e.g.

oc apply -f https://raw.githubusercontent.com/ibm-mas/cli/master/catalogs/v8-240430-amd64.yaml

and then got to  Cluster Settings -> CustomResourceDefinition -> OperatorHub -> Instances -> Cluster  -> Sources

I can see that ibm-operator -catalog is in TRANSIENT_FAILURE state most of the time and it needs to be in READY state. Obviosly, I cannot work like this.

Redhat 8.9

$crc version
CRC version: 2.36.0+27c493
OpenShift version: 4.15.12
Podman version: 4.4.4
***@***.***:/home/aganagic

$crc config view
- consent-telemetry                     : no
- cpus                                  : 72
- host-network-access                   : true
- memory                                : 491520
- network-mode                          : user
- pull-secret-file                      : /cliconfig/pull-secret.txt
***@***.***:/home/aganagic

If you need any more info please let me know. I am trying t install IBM MAS on this cluster and I can't.

Thanks,

Edn

________________________________________________



________________________________________________

EDIN I. AGANAGIC



Cross Sustainability SME, IBM Sustainability Software

***@***.******@***.***>, 416.729.8476





________________________________
From: Praveen Kumar ***@***.***>
Sent: Wednesday, June 5, 2024 12:27 AM
To: crc-org/crc ***@***.***>
Cc: Edin Aganagic ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [crc-org/crc] TRANSIENT_FAILURE with ibm-operator-catalog (Issue #4195)

Closed #4195 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <crc-org/crc/issue/4195/issue_event/13044844909@ github. com> ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/AdhS1Rd-!9pFRGhxR-ecxFh8RxIdrudXlCDOYMQQuDoV5QtaEgn6FuP1_u0fl6EVGshByv8ypyxXxjG2TXeOP0o4Dczw7A8ULes02uxeFNAOSUIEj3SS5LK0$>
Report Suspicious

ZjQcmQRYFpfptBannerEnd

Closed #4195<https://github.com/crc-org/crc/issues/4195> as completed.

**Comment by aganagic** [comment]
[cid:c1376bac-2560-4416-9199-17ff74b064f5]


________________________________________________

EDIN I. AGANAGIC



Cross Sustainability SME, IBM Sustainability Software

***@***.******@***.***>, 416.729.8476





________________________________

**Comment by aganagic** [comment]
Hi,


Is there anything at all that can be done here? My project is 3-4 months behind  because of this issue.

Thank you for your help and time.

Edin


________________________________________________

EDIN I. AGANAGIC



Cross Sustainability SME, IBM Sustainability Software

***@***.******@***.***>, 416.729.8476





________________________________
