### ISSUE TITLE
[BUG] `crc setup` output: libvirt v8.0.0 or newer is required and must be updated manually

### ISSUE THREAD

**Issue by molivo123** [crc-org/crc#4202]
### General information

  * OS: Linux - Ubuntu 20.04.6 2024.05.07 LTS (Cubic 2024-05-07 09:58)
  * Hypervisor: KVM / Hyper-V / hyperkit / vfkit
  * Did you run `crc setup` before starting it (Yes)!
  * Running CRC on: Laptop

## CRC version
```bash
CRC version: 2.36.0+27c493
OpenShift version: 4.15.12
Podman version: 4.4.4
```

## CRC setup output
```bash
molivo@Precision-728:~/bin$ crc setup
INFO Using bundle path /home/molivo/.crc/cache/crc_libvirt_4.15.12_amd64.crcbundle 
INFO Checking if running as non-root              
INFO Checking if running inside WSL2              
INFO Checking if crc-admin-helper executable is cached 
INFO Checking if running on a supported CPU architecture 
INFO Checking if crc executable symlink exists    
INFO Creating symlink for crc executable          
INFO Checking minimum RAM requirements            
INFO Check if Podman binary exists in: /home/molivo/.crc/bin/oc 
INFO Checking if Virtualization is enabled        
INFO Checking if KVM is enabled                   
INFO Checking if libvirt is installed             
INFO Checking if user is part of libvirt group    
INFO Checking if active user/process is currently part of the libvirt group 
INFO Checking if libvirt daemon is running        
INFO Checking if a supported libvirt version is installed 
libvirt v8.0.0 or newer is required and must be updated manually
```
  
## CRC status
```bash
crc does not seem to be setup correctly, have you run 'crc setup'?
```

## CRC config
```bash
- consent-telemetry                     : no
```

## Host Operating System
```bash
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 2024.05.07 LTS (Cubic 2024-05-07 09:58)"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Steps to reproduce

  1. https://console.redhat.com/openshift/create/local
  2. downloaded linux package from above link
  3. https://crc.dev/crc/getting_started/getting_started/installing/
  4. ran commands a-c in "installing CRC"
  5. ran: crc config set consent-telemetry no
  6. ran crc setup and got output in CRC setup output section
  

### Expected
crc setup would actually run

### Actual
cannot update libvirt to v8.0.0

### Logs
N/A

**Comment by praveenkumar** [comment]
This is expected, we usually support 2 major releases and in case of ubuntu https://ubuntu.com/about/release-cycle it is 22.04 and 24.04 for LTS side. Can you please update your ubuntu system and try again? I am closing this issue since it is expected.
