### ISSUE TITLE
transient_falures with ibm-operator-catalog

### ISSUE THREAD

**Issue by aganagic** [crc-org/crc#4214]
Whether I create dynamic or static ibm-operator-catalog, e.g.

oc apply -f https://raw.githubusercontent.com/ibm-mas/cli/master/catalogs/v8-240430-amd64.yaml

and then got to  Cluster Settings -> CustomResourceDefinition -> OperatorHub -> Instances -> Cluster  -> Sources

I can see that ibm-operator -catalog is in TRANSIENT_FAILURE state most of the time and it needs to be in READY state. Obviosly, I cannot work like this.

Redhat 8.9

$crc version
CRC version: 2.36.0+27c493
OpenShift version: 4.15.12
Podman version: 4.4.4
[aganagic@meissa]:/home/aganagic

$crc config view
- consent-telemetry                     : no
- cpus                                  : 72
- host-network-access                   : true
- memory                                : 491520
- network-mode                          : user
- pull-secret-file                      : /cliconfig/pull-secret.txt
[aganagic@meissa]:/home/aganagic

If you need any more info please let me know. I am trying t install IBM MAS on this cluster an d I can't.

**Comment by cfergeau** [comment]
For the record, this was initially report as https://github.com/crc-org/crc/issues/4195

**Comment by cfergeau** [comment]
When this happens, does the `ibm-operator-catalog` also show as degraded in `oc  get all -n openshift-marketplace`?

**Comment by aganagic** [comment]
Hi Christophe,

This case can be closed, I resolved it. Many sources (including Redhat) were saying that this is most likely a network or NetworkPolicy issue . But, it wasn't - it was DiskPressure  issue. CRC VM uses around 30GB and it just ran out of space.
I just did

$crc config set disk-size 100

and TRANSIENT_FAILURES  were gone.

Thanks,

Edin

________________________________________________

EDIN I. AGANAGIC



Cross Sustainability SME, IBM Sustainability Software

***@***.******@***.***>, 416.729.8476





________________________________
From: Christophe Fergeau ***@***.***>
Sent: Wednesday, June 12, 2024 5:44 AM
To: crc-org/crc ***@***.***>
Cc: Edin Aganagic ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [crc-org/crc] transient_falures with ibm-operator-catalog (Issue #4214)

This Message Is From an External Sender
This message came from outside your organization.
Report Suspicious<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/AdhS1Rd-!9BFRGhxR-ecxFh8RxIdruQh9Ggv51URkWy3YC4N9EQe-pzI6Vp2_dzYfiMJ0ctdL4xgJlnFOwJw3ohQ9L3E2HPVxImYZx2o$>


When this happens, does the ibm-operator-catalog also show as degraded in oc get all -n openshift-marketplace?

?
