### ISSUE TITLE
Remote crc

### ISSUE THREAD

**Issue by cosmind-rusu** [crc-org/crc#4216]
Hello, I am installing a crc on a baremetal Debian 11, I want to be able to connect to the cluster from outside on a Windows machine, and I am not getting it, I have opened ports, I have exposed routes and the documentation does not have any effect when I apply it, could you please help me . The crc version is the latest, just like the oc cli.

**Comment by gbraad** [comment]
The documentation has a section about this. Please check https://crc.dev/crc/

Note: remote access is described as 'semi-supported' from Fedora, but this is a local network configuration issue. This is not something we can help with. Perhaps consider creating a discussion instead.
