### ISSUE TITLE
[BUG] Temporary error: pull secret not updated to disk

### ISSUE THREAD

**Issue by perdasilva** [crc-org/crc#4297]
### General information

  * OS: macOS
  * Hypervisor: vfkit
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop 

## CRC version
```bash
CRC version: 2.39.0+0849cb
OpenShift version: 4.16.0
```
  
## CRC status
```bash
DEBU CRC version: 2.39.0+0849cb
DEBU OpenShift version: 4.16.0
DEBU Running 'crc status'
CRC VM:          Running
OpenShift:       Unreachable (v4.16.0)
RAM Usage:       395.4MB of 10.94GB
Disk Usage:      20.75GB of 32.68GB (Inside the CRC VM)
Cache Usage:     38.84GB
Cache Directory: /Users/XXXXXX/.crc/cache
```

## CRC config
```bash
- consent-telemetry                     : no
- pull-secret-file                      : /Users/XXXXX/.crc/pull-secret.txt
```

## Host Operating System
```bash
ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79
```

### Steps to reproduce

From nothing:

  1. crc setup
  2. crc start

From a failed deployment:

 1. crc stop --force
 2. crc delete --force
 4. crc cleanup
 5. crc setup
 6. crc start

### Expected

A working cluster

### Actual

```
DEBU error: Temporary error: pull secret not updated to disk - sleeping 2s 
DEBU retry loop: attempt 13                       
DEBU Running SSH command: <hidden>                
DEBU Failed to create new ssh session: ssh: unexpected packet in response to channel open: <nil> 
DEBU SSH command failed                           
DEBU non-retriable error: failed to read /var/lib/kubelet/config.json file: ssh command error:
command : sudo cat /var/lib/kubelet/config.json
err     : ssh: unexpected packet in response to channel open: <nil>
:  
Failed to update pull secret on the disk: Temporary error: pull secret not updated to disk (x13)
failed to read /var/lib/kubelet/config.json file: ssh command error:
command : sudo cat /var/lib/kubelet/config.json
err     : ssh: unexpected packet in response to channel open: <nil>
: 
```

### Logs

[gist](https://gist.github.com/perdasilva/ae5297ef70fd35d358434f891abb897b)

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by perdasilva** [comment]
For added context: I _have_ managed to stand-up a crc cluster on this machine. I think the initial flow worked fine (download crc, crc setup, download and paste pull secret, etc. The problem started after nuking that cluster and trying to stand up a new one. Since then, it's been hit and miss (but overwhelmingly miss).

**Comment by praveenkumar** [comment]
```
err     : ssh: unexpected packet in response to channel open: <nil>
```

This looks like issue with `ssh` and hence networking side, can you able to ssh to this VM even after failure using https://github.com/crc-org/crc/wiki/Debugging-guide one?

**Comment by perdasilva** [comment]
@praveenkumar I've also tried again with crc delete --clear-cache. It required me to re-download the bundle, but it created a cluster XD once I run into the problem again, I'll try ssh'ing to the VM and poking around.

**Comment by perdasilva** [comment]
@praveenkumar after I brought my crc cluster down (stop + delete), then tried to start again:

```
DEBU Failed to create new ssh session: ssh: unexpected packet in response to channel open: <nil> 
DEBU SSH command failed                           
DEBU non-retriable error: failed to read /var/lib/kubelet/config.json file: ssh command error:
command : sudo cat /var/lib/kubelet/config.json
err     : ssh: unexpected packet in response to channel open: <nil>
:  
Failed to update pull secret on the disk: Temporary error: pull secret not updated to disk (x9)
failed to read /var/lib/kubelet/config.json file: ssh command error:
command : sudo cat /var/lib/kubelet/config.json
err     : ssh: unexpected packet in response to channel open: <nil>
: 
```

```
$ ssh -i ~/.crc/machines/crc/id_ecdsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222 core@127.0.0.1                                                                                                                                                                                                                                            
kex_exchange_identification: read: Connection reset by peer
Connection reset by 127.0.0.1 port 2222
```

**Comment by perdasilva** [comment]
@praveenkumar I use fish. Out of curiosity, I tried crc start in bash. Seems to work. Maybe something isn't sticking in the environment on fish...?

**Comment by praveenkumar** [comment]
> @praveenkumar I use fish. Out of curiosity, I tried crc start in bash. Seems to work. Maybe something isn't sticking in the environment on fish...?

That might be the case, we usually test out all those stuff in bash environment not any other. Also does ssh succeed in bash environment?

**Comment by perdasilva** [comment]
> > @praveenkumar I use fish. Out of curiosity, I tried crc start in bash. Seems to work. Maybe something isn't sticking in the environment on fish...?
> 
> That might be the case, we usually test out all those stuff in bash environment not any other. Also does ssh succeed in bash environment?

I think once it fails in fish, the ssh server is no longer reachable T_T. Bash did the trick though. I'll close this for now, unless you want me to reframe it as a fish bug? is that interesting to you guys to fix? Or if you could give me some pointers, when I have some free time, I can try to step through and see where it's choking.

**Comment by cfergeau** [comment]
Not clear from the logs what's going on, the ssh complaint is odd:
```
Failed to create new ssh session: ssh: unexpected packet in response to channel open:
```

I think it's the first time this issue with fish is reported, so it's not going to be a top priority on our side. If you want to investigate some more, we can try to help :)
