### ISSUE TITLE
Add self host runner from testing farm

### ISSUE THREAD

**Issue by lilyLuLiu** [crc-org/crc#4305]
Investigation on the testing farm: https://github.com/orgs/crc-org/projects/1/views/1?pane=issue&itemId=72048441 

How to add self-host runner from testing farm:
https://gitlab.com/testing-farm/infrastructure#:~:text=GitHub%20related%20infrastructure.-,GitHub%20Runners,-We%20optionally%20provide

**Comment by lilyLuLiu** [comment]
The self-hosted runner form testing farm have been added to CRC repository.

**Comment by lilyLuLiu** [comment]
The related MR:
https://gitlab.com/testing-farm/infrastructure/-/merge_requests/676 
https://gitlab.com/testing-farm/infrastructure/-/merge_requests/667

**Comment by praveenkumar** [comment]
@lilyLuLiu I can see it is added for x86-64 (https://gitlab.com/testing-farm/infrastructure/-/merge_requests/676/diffs#diff-content-a4ddc776e05a2d3431cd12825bc1549e75f802ee) didn't we try to have it for arm64?

**Comment by lilyLuLiu** [comment]
@praveenkumar , Hi, This self-host runner is used to provision machines from testing farm.  We will use this self-host runner to get the arm64 machines.
