### ISSUE TITLE
Machine disk file not deleted after crc delete

### ISSUE THREAD

**Issue by jeffmaury** [crc-org/crc#4319]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
CRC version: 2.40.0+a14925
OpenShift version: 4.16.4
MicroShift version: 4.16.4
```
  
## CRC status
```bash
DEBU CRC version: 2.40.0+a14925
DEBU OpenShift version: 4.16.4
DEBU MicroShift version: 4.16.4
DEBU Running 'crc status'
Machine does not exist. Use 'crc start' to create it
```

## CRC config
```bash
# Put `crc config view` output here
- preset                                : microshift
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1. crc start 
  2. crc delete

### Expected
The .vhdx file is removed from the .crc/cache folder

### Actual
```
ls crc_microshift_hyperv_4.16.4_amd64
crc-bundle-info.json  crc.vhdx  id_ecdsa_crc  kubeconfig  oc.exe  podman.exe
```

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@jeffmaury We don't remove disk image from cache folder as part of delete because it is used as part of start and every start we don't want to extract bundle. this disk image is copied to other location ( `$HOME/.crc/machine`) as part of start and then removed when delete happen.

I don't this this is a bug.

**Comment by jeffmaury** [comment]
Yeah I was just a bit puzzled by the disk space as every update and setup create such a folder
