### ISSUE TITLE
[QE] Integration resize test failed in step "check VM's memory size"

### ISSUE THREAD

**Issue by lilyLuLiu** [crc-org/crc#4325]
This is something around integration helper function which send commands to VM

> <failure message="Unexpected error: <*fmt.wrapError | 0xc000242020>: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain { msg: "ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain", err: <*errors.errorString | 0xc00069e1f0>{ s: "ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain", }, } occurred" type="failed">[FAILED] Unexpected error: <*fmt.wrapError | 0xc000242020>: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain { msg: "ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain", err: <*errors.errorString | 0xc00069e1f0>{ s: "ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain", }, } occurred In [It] at: /workspace/test/integration/resize_test.go:61 @ 08/21/24 08:35:38.573 </failure>
<system-err>> Enter [It] check VM's memory size - /workspace/test/integration/resize_test.go:59 @ 08/21/24 08:35:38.496 [FAILED] Unexpected error: <*fmt.wrapError | 0xc000242020>: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain { msg: "ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain", err: <*errors.errorString | 0xc00069e1f0>{ s: "ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain", }, } occurred In [It] at: /workspace/test/integration/resize_test.go:61 @ 08/21/24 08:35:38.573 < Exit [It] check VM's memory size - /workspace/test/integration/resize_test.go:59 @ 08/21/24 08:35:38.573 (77ms) > Enter [AfterAll] vary VM parameters: memory cpus, disk - /workspace/test/integration/resize_test.go:15 @ 08/21/24 08:35:38.573 < Exit [AfterAll] vary VM parameters: memory cpus, disk - /workspace/test/integration/resize_test.go:15 @ 08/21/24 08:35:44.333 (5.759s) </system-err>

**Comment by vyasgun** [comment]
Unable to reproduce this on my local machine:

```
make GINKGO_OPTS="--ginkgo.label-filter='vm-resize'" BUNDLE_PATH="--bundle-path=/Users/gvyas/.crc/cache/crc_vfkit_4.16.7_arm64.crcbundle" PULL_SECRET_PATH="--pull-secret-path=/Users/gvyas/Downloads/pull-secret.txt" integration
Running Suite: Integration - /Users/gvyas/work/crc/test/integration
===================================================================
Random Seed: 1724721794

Will run 20 of 36 specs
Ran 20 of 36 Specs in 703.655 seconds
SUCCESS! -- 20 Passed | 0 Failed | 0 Pending | 16 Skipped
```

**Comment by lilyLuLiu** [comment]
This issue is fixed with https://github.com/crc-org/crc/commit/80dcac9116d45037998d44337d622d9b2a89a06a
