### ISSUE TITLE
[CI] Disable e2e and integration github actions on PRs coming from dependabot 

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/crc#4355]
We are currently over testing, we can rely on check actions for the library updates to help us reduce testing cycles

**Comment by rohanKanojia** [comment]
@adrianriobo : Hello, can I work on this issue?

**Comment by rohanKanojia** [comment]
I already see a check in e2e test pipeline to not execute for dependabot:
https://github.com/crc-org/crc/blob/d9f83bcc27dc8717469091553c90d9b97c2b5105/.github/workflows/windows-e2e.yml#L13-L15

Do we want to add same check in other github actions?

**Comment by adrianriobo** [comment]
Ah sure, this was added to reduce the # of executions specially when provisioning machines on cloud. Definetly if you see any missing please go and filter them

**Comment by rohanKanojia** [comment]
As discussed internally, we already have this check on Windows envs, and OpenShift CI doesn't run on the dependendabot PRs.

I think we can close this issue as completed.
