### ISSUE TITLE
Add documentation that services running on the host can be connected to via the `host.crc.testing` hostname

### ISSUE THREAD

**Issue by bobbygryzynger** [crc-org/crc#4398]
There's an undocumented feature that services running on the host machine can be connected to from within the VM/cluster via using the `host.crc.testing` hostname and port of the service (e.g. `host.crc.testing:3306` for a MySQL server running on the host).

This feature should be mentioned in the documentation.

**Comment by gbraad** [comment]
currently we are limited in what we can change to the documentation. perhaps best to add this to the wiki or FAQ

**Comment by cfergeau** [comment]
For consistency with podman, might be worth using/documenting `host.containers.internal`
