### ISSUE TITLE
Add host.crc.testing to /etc/hosts

### ISSUE THREAD

**Issue by bobbygryzynger** [crc-org/crc#4410]
Related to #4398: because the host can be reached at `host.crc.testing` this should be added to CRC's `/etc/hosts` modifications. 

```txt
127.0.0.1    host.crc.testing
```

**Comment by cfergeau** [comment]
It is similar to this docker feature https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host, I'm  not sure this also can be resolved on the host?
However, this should be relatively easy to do in our case, so why not.

**Comment by praveenkumar** [comment]
> host.crc.testing this should be added to CRC's /etc/hosts modifications.

@bobbygryzynger if `host.crc.testing` already available to consume in the CRC VM then why we need to modify `/etc/hosts` to have this entry?

**Comment by bobbygryzynger** [comment]
@praveenkumar I have some scripts that run both on the host and within containers on the cluster that interact with host services. It would be convenient to be able to use the same hostname in both circumstances and not have to set the value in the host's `/etc/hosts` myself. This would also help other developers setting up my project locally, by removing a manual step.

**Comment by rohanKanojia** [comment]
Can I work on this issue?

**Comment by rohanKanojia** [comment]
This issue got fixed by #4471 . Could someone please close the issue?

**Comment by cfergeau** [comment]
"Fixes: https://github.com/crc-org/crc/issues/4410" in the PR should have triggered the closing automatically, maybe this needs to be formatted slightly differently.
