### ISSUE TITLE
CRC is unsupported using WSL2

### ISSUE THREAD

**Issue by johnbayo** [crc-org/crc#4449]
I get the following error when installing openshift local on wsl2 Ubuntu 24.04

$ crc setup --log-level debug
DEBU CRC version: 2.43.0+268795
DEBU OpenShift version: 4.17.1
DEBU MicroShift version: 4.17.1
DEBU Running 'crc setup'
INFO Using bundle path /home/jadebayo/.crc/cache/crc_libvirt_4.17.1_amd64.crcbundle
DEBU resolv.conf file path: /run/resolvconf/resolv.conf
INFO Checking if running as non-root
INFO Checking if running inside WSL2
DEBU Running inside WSL2 environment
DEBU CRC is unsupported using WSL2
CRC is unsupported using WSL2

$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.1 LTS"
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu

**Comment by praveenkumar** [comment]
@johnbayo you are trying to run crc on WSL environment and it need virtualization. Better to directly install CRC on windows and then run (this is the way we develop and test it).
