### ISSUE TITLE
[BUG] [sudo, tr] command not found

### ISSUE THREAD

**Issue by kaovilai** [crc-org/crc#4455]
### General information

  * OS: macOS 
  * Hypervisor: vfkit
  * Did you run `crc setup` before starting it (Yes/No)? yes
  * Running CRC on: Laptop 

## CRC version
```bash
CRC version: 2.42.0+6689ec
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```

## CRC config
```bash
❯ crc config view
- consent-telemetry                     : no
- cpus                                  : 8
- disk-size                             : 50
- pull-secret-file                      : /Users/tiger/pull-secret.txt

```

## Host Operating System
```bash
❯ sw_vers                     
ProductName:		macOS
ProductVersion:		14.7.1
BuildVersion:		23H222
```

### Steps to reproduce

  1. crc start --log-level debug
  2. 
  3. 
  4. 

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.
https://gist.github.com/kaovilai/f226386e2f1087067043a5455367a2f8

```
Failed to update pull secret on the disk: Temporary error: pull secret not updated to disk (x12)
failed to read /var/lib/kubelet/config.json file: ssh command error:
command : sudo cat /var/lib/kubelet/config.json
err     : Process exited with status 127
: /etc/profile.d/debuginfod.sh: line 9: tr: command not found

/etc/bashrc: line 79: /etc/profile.d/which2.sh: Input/output error
bash: line 1: sudo: command not found
```

**Comment by cfergeau** [comment]
The end of the log is odd... 
```
: /etc/profile.d/debuginfod.sh: line 9: tr: command not found

/etc/bashrc: line 79: /etc/profile.d/which2.sh: Input/output error
bash: line 1: sudo: command not found
```

Could there be VM disk corruption?

Let's first fix #4454 and then we will see if this one still occurs.

**Comment by kaovilai** [comment]
No longer hitting this. This is also v2.42.0 and yes I frequently have to delete stuff on this 500GB of a machine. Thanks rh. CRC disk images aren't small either.

**Comment by praveenkumar** [comment]
Since you are no longer hitting this so closing it. If you think this need to be track then we can reopen it.
