### ISSUE TITLE
Windows install best practice is to use Chocolately (e.g. `choco install crc`)

### ISSUE THREAD

**Issue by DonSchenck** [crc-org/crc#762]
### General information

  * Windows
  * Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? YES

The defacto standard for installing software on Windows is Chocolatey (chocolatey.org). This involved creating a chocolatey package, which in this particular case is simply a shim that drops the crc.exe into the C:\ProgramData\chocolatey\bin directory.

---
Moved from https://github.com/crc-org/crc/issues/762#issuecomment-1438104157

We submitted a package to the [chocolatey community feed](https://community.chocolatey.org/packages/crc/2.12.0) and got a review on the 16th feb, these were the requested changes:

- [x] The owners field is for the Package owners and should be your name / Chocolatey username.
- [x] Can you use a static CDN for your <iconUrl> - [githack.com](http://githack.com/) and [jsdelivr.com](http://jsdelivr.com/) are popular. See [https://docs.chocolatey.org/en-us/create/create-packages{#}package-icon-guidelines](https://docs.chocolatey.org/en-us/create/create-packages%7B#}package-icon-guidelines)
- [x] Can you add a bugTrackerUrl field in the .nuspec file?
- [x] Please add a From: <LICENSE URL> to the top of your LICENSE.txt file.
- [x] Please add instructions on how to verify the checksums of embedded files and the checksums themselves.
- [x] Please remove the comments from the PowerShell scripts.
- [x] On line 17 of chocolateyInstall.ps1, please use the Chocolatey helperSet-PowerShellExitCode`.
- [x] Please use $ErrorActionPreference = 'Stop' at the top of your PowerShell scripts. You can set -ErrorAction SilentlyContinue for individual cmdlets when needed.
- [x] As far as I can see in the code, if Hyper-V needs to be installed, it wil install it and Chocolatey CLI will register that the package has been installed even though Hyper-V requires a reboot? Will the rest of the package install if Hyper-V is not available? There is no message to tell the user they will need to reboot before using anything. This isn't a really good user experience from what I understand.

**Comment by gbraad** [comment]
While I agree, I also disagree... as the releases for Minishift were not controlled by us, this gave unexpected results. 

However, the same goes for macOS where the binaries for cask (brew) were even rebuilt making any guarantees about the quality very difficult.

**Comment by gbraad** [comment]
Don, can you login to the package repository? My account seems to fail now,
so unable to create the namespace.

**Comment by DonSchenck** [comment]
I don't have an account at Chocolatey.org.

**Comment by anjannath** [comment]
Moved to 1st message

**Comment by anjannath** [comment]
waiting for next review on https://community.chocolatey.org/packages/crc/2.12.0
